### ISSUE TITLE
Workstation main view not showing full image when opening in sagittal mode

### ISSUE THREAD

**Issue by nlessmann** [comic/grand-challenge.org#1004]
When starting a cirrus core workstation with the vertebra settings, the viewer opens in sagittal view as it should, but the viewer is zoomed in a little bit by default. Because of that, the image is not completely visible. That is confusing, especially since there is also no clear visual cue that the viewer is not zoomed out completely.

<img width="1800" alt="screenshot" src="https://user-images.githubusercontent.com/773597/69532711-b5ddf000-0f76-11ea-9dda-8444997e3c51.png">

The screenshot shows the workstation after opening, I only disabled the overlay but didn't change anything else. Compare the main view and the small sagittal view at the bottom on the right. The field of view is not the same.

When I worked on modifying cirrus core myself, I ran into the same issue and solved it by calling the `fitImageToViewer` method of the main view item object.

**Comment by jmsmkn** [comment]
Please make issues about CIRRUS in the https://github.com/DIAGNijmegen/rse-cirrus-core repo.

There is an issue about this already: https://github.com/DIAGNijmegen/rse-cirrus-core/issues/277 so closing as duplicate.
