### ISSUE TITLE
Ability to remove readers, editors (and users)

### ISSUE THREAD

**Issue by bramvanginneken** [comic/grand-challenge.org#1006]
We need to be able to remove Readers from a reader study as an Editor. Could this be added?

**Comment by MikeOverkamp-diag** [comment]
That should not be a problem. Do you think we should also give editors the option to remove other editors or should we leave that as a task for admins?

**Comment by jmsmkn** [comment]
> That should not be a problem. Do you think we should also give editors the option to remove other editors or should we leave that as a task for admins?

We let challenge admins do this, so yes, I would say this is fine.
