### ISSUE TITLE
Allow moving backwards in reader studies

### ISSUE THREAD

**Issue by MikeOverkamp-diag** [comic/grand-challenge.org#1013]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible for a reader to move back to previous cases in a reader study. However, if the reader has accidentally entered a wrong answer, it would be useful to be able to change it.

**Describe the solution you'd like**
An option could be added to a reader study to indicate whether or not readers are allowed to move backwards. It should be optional, because in some reader studies answers to previous cases might become apparent once the reader advances to the next one.

**Comment by jmsmkn** [comment]
We would also need to add a patch method to `Answers`. It would also be an idea to add object history to the answers when doing this. 

We should make a different issue for the work to the front end, this would be a significant change to support.

**Comment by xarion** [comment]
Hello, is there any update on this? I find it quite important for my upcoming studies.
