### ISSUE TITLE
Allow challenges to be closed while retaining result processing

### ISSUE THREAD

**Issue by GeertLitjens** [comic/grand-challenge.org#1015]
**Is your feature request related to a problem? Please describe.**
Currently, any submitted result by a user needs to be added to the leaderboard to be visible. However, after a certain period of time, the challenge organizers might want to close the challenge, but still, allow participants to submit and view results without adding those to the leaderboard.

**Describe the solution you'd like**
Add a close function to the challenge which disables the leaderboard. Participants can still submit results and see the metrics privately.

**Comment by bramvanginneken** [comment]
This is a bit like late submissions that Kaggle has. We should define precisely what is needed. In my mind, the leaderboard should remain visible for all in its final state. Teams who make a late submission just can see their own result. Everything else still holds, eg if an organizer wants to evaluate only when there is a description/valid paper, team gets to see their result only after approval by the organizer.

**Comment by jmsmkn** [comment]
Would be worth re-working this model as there are a few other feature requests for this, eg, #579, #708, #543

**Comment by jmsmkn** [comment]
This can now be achieved by setting up a new Phase for a challenge so you could have say a "challenge" and "post-challenge" phase, or by using the leaderboard history and linking to the leaderboard on a closing date.
