### ISSUE TITLE
As a user of Grand Challenge I would like to be able to create a workstation configuration

### ISSUE THREAD

**Issue by miriam-groeneveld** [comic/grand-challenge.org#1024]
Create forms for creating, list, detail and update of WorkstationConfig objects:

- You should be able to create WorkstationConfig objects if the user has the `add_workstationconfig` (?) permission.
- Anyone can view all workstation configs.
- The WorkstationConfig creator should be able to edit their config.

Do not add views for WindowPreset or LookUpTable.

**Comment by jmsmkn** [comment]
Closed by #1037
