### ISSUE TITLE
Builds are broken

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#1042]
It seems that the build is not reproducible right now, I retried master that was successful yesterday, fails today: https://travis-ci.org/comic/grand-challenge.org/builds/624157575 compare with https://travis-ci.org/comic/grand-challenge.org/builds/623723638

**Comment by jmsmkn** [comment]
It seems that Poetry 1.0.0 was released, probably the cause.

**Comment by MikeOverkamp-diag** [comment]
It seems poetry 1.0.0 was released yesterday: https://pypi.org/project/poetry/#history I assume this is related to that.

**Comment by MikeOverkamp-diag** [comment]
I'll try and see if pinning it to the beta version fixes the issue.
