### ISSUE TITLE
more information on profile page

### ISSUE THREAD

**Issue by bramvanginneken** [comic/grand-challenge.org#1050]
On my profile page, https://grand-challenge.org/accounts/BramVanGinneken/ I see only challenges I am participating in, but it would be nice if I can also see which reader studies, algorithms etc I have access to and in what role. Alternatively, if I go to https://grand-challenge.org/reader-studies/ I see all reader studies I can access as cards. It would be nice if  https://grand-challenge.org/challenges/ would show my all challenges I am participating in, organizing etc. as cards.

It would be nice if on those cards I could see my role(s) listed, now I have to click on a reader study to see that. Maybe also filter them. Same then for challenges,. algorithms.

It would also be nice if the menu on top, which now lists only All Challenges would read

All Challenges . My Challenges. My Algorithms . My Reader Studies

**Comment by bramvanginneken** [comment]
Very nice. On my profile page viewed without logging in, cause07 and crass are listed twice.

**Comment by jmsmkn** [comment]
Ah, that is because you are in both the admins and participants group for those challenges - that situation is handled for the other objects but not challenges, I will add it.
