### ISSUE TITLE
Ability to delete algorithm jobs

### ISSUE THREAD

**Issue by nlessmann** [comic/grand-challenge.org#1051]
It would be nice if algorithm editors and users could delete jobs themselves.

**Comment by jmsmkn** [comment]
Also ensure that the Image, Image files (and DZI directory) are cleaned from storage, if the image is not in use elsewhere (eg, as part of a reader study, challenge, etc).

**Comment by jmsmkn** [comment]
Thank you for the suggestion. I am gathering all of the feature requests elsewhere, and will consider this for inclusion a future development cycle.
