### ISSUE TITLE
Hide list of algorithm images or add button to switch back to old image

### ISSUE THREAD

**Issue by nlessmann** [comic/grand-challenge.org#1052]
Currently, there is a list of algorithm (processor) images on the algorithm page, but that list does not seem to have any purpose. It would be useful if it was possible to reactivate an older image in case a newer image causes jobs to fail. If that would be complicate to implement, it would in my opinion be nicer if the list was hidden.

**Comment by jmsmkn** [comment]
They're there as this is the only way that an editor can see the errors if a container import has failed. The algorithm admin page is complex now, so this should be separated out (like we have for challenges). I will add a separate issue for that.
