### ISSUE TITLE
Sharing of jobs with algorithm users

### ISSUE THREAD

**Issue by nlessmann** [comic/grand-challenge.org#1053]
A low priority feature request:

If I want to demo my algorithm to somebody, I can add them as algorithm users, but they currently start with an empty job list and would need to upload scans themselves to test the algorithm.

It would be a nice additional feature if I could also upload a few scans myself (as algorithm editor) and share the results with algorithm users, i.e., select for each job additional users that also see the job in their account and can inspect the results in a workstation.

**Comment by jmsmkn** [comment]
We have a few requests for this. Requirements:

- Sharing the results with other users. We then need to ensure that those users have permission to read the result, result images, input images, algorithm (but not algorithm execution) and workstation for that algorithm.
- Making a result available to any user (except Anonymous User). Same as above.

**Comment by jmsmkn** [comment]
You can now mark results as public (working on the UI)
