### ISSUE TITLE
Links to contact information on algorithm cards

### ISSUE THREAD

**Issue by nlessmann** [comic/grand-challenge.org#1069]
Since the algorithms are publicly visible, I started getting access requests from random people. They currently have no way of contacting me directly if they are interested in the algorithm - there are fields for contact information etc (added in #978), but these are only visible after the access request has been approved.

It would be useful if there was an option to have a "contact information" link in the algorithm card, next to the "view algorithm" and "try out" buttons. I would want to have this point at my profile on the DIAG website, for example.

**Comment by jmsmkn** [comment]
Agreed, publications we will solve in another issue.

**Comment by jmsmkn** [comment]
The algorithm detail page is now public (if set) so contact information can be added there.
