### ISSUE TITLE
More informative "results" column in algorithm job list

### ISSUE THREAD

**Issue by nlessmann** [comic/grand-challenge.org#1070]
The job list currently shows the entire "results.json" file that a algorithm job produced in the "Results" column. This can get messy, for example, the calcium scoring algorithm computes all kinds of scores:

![image](https://user-images.githubusercontent.com/773597/71962798-933c2980-31fa-11ea-96ca-8e2af1e68d8b.png)

Would be nicer if this was hidden by default. Instead, "results.json" could support something like a "results_message" key next to the "metrics" key, so that the algorithm can output a (short) string that is displayed in the job list. For example, in case of the calcium scoring algorithm, I would simply output the overall score, and the vertebra segmentation algorithm could output the number of detected vertebrae, etc.

**Comment by jmsmkn** [comment]
Agreed. For implementation see the evaluation config and json lookups there.
