### ISSUE TITLE
Add reader study evaluation (course) functionality

### ISSUE THREAD

**Issue by MikeOverkamp-diag** [comic/grand-challenge.org#1079]
We would like to be able to use grand challenge as an educational tool as well. In order to do so, we need to expand the current reader study functionality and add the ability to evaluate the answers given by the reader. This can be done either as the reader progresses through the study, or after all images have been completed. 

To evaluate the answers, they need to be compared to the ground truth, which editors need to be able to add. Initially this can be done by uploading a JSON file, but it might also be nice to add the option for editors to run through the images and add the ground truth that way. 

Initially we would support ground truth comparison for simple answer types (e.g. boolean and a to be added integer and/or classification/choice type). In a later stage we also need support for annotations, for instance by adding acceptable ranges for them.

After evaluation, the reader should get feedback on their performance and preferably be able to view the images that were answered incorrectly.

The scores for each reader should be added to the leader board for the study. It should also be possible to view the results for a study per case and sort these results on difficulty (i.e. the ration of correct:incorrect answers).

**Comment by MikeOverkamp-diag** [comment]
TODO: Add scoring and ground truth for all available answer types

**Comment by jmsmkn** [comment]
I think that the basics of this are done. Should we add separate issues for supporting the other answer types?

**Comment by MikeOverkamp-diag** [comment]
Agreed. The basic functionality for this was added / updated in #1094, #1104, #1121, #1122, #1144, #1149, #1150.

Added a new issue for the remaining answer types: #1178
