### ISSUE TITLE
Credit system for algorithms

### ISSUE THREAD

**Issue by nlessmann** [comic/grand-challenge.org#1085]
I think either Bram or James mentioned something similar a while back, but I couldn't find a feature request ticket for this: I'm getting now requests every day from people who want to try out my algorithms. It would be fantastic if I could grant them access with a limited "job budget" so that they can upload one or two of their scans but not more.

**Comment by bramvanginneken** [comment]
Yes, we need to implement something like that. The problem with a limited credit system where users get eg 3 credits a month and you as the algorithm developer can specify what running an algorithm costs, eg 1 credit (and maybe a price for running an algorithm with priority where it moves to the top of the queue, eg 2 credits) is that for sure users will create multiple accounts. We see this kind of hacking already now with challenges that limit the number of submissions people can make. So I think we need to set up a better way of checking identities of users if we are to grant them these kind of rights. We should discuss this.
