### ISSUE TITLE
Add option to remove reader study answers for a user

### ISSUE THREAD

**Issue by MikeOverkamp-diag** [comic/grand-challenge.org#1111]
**Is your feature request related to a problem? Please describe.**
Currently it is possible to remove a reader from a reader study. However, doing so does not automatically remove the answers created by that user. In case the user is added to the study at a later point in time, they cannot complete the study again, because their previous answers are still intact.

**Describe the solution you'd like**
The best option would be to add a new button to remove all answers for a user in a reader study. That way the editors can decide whether or not they want to leave the existing data intact or remove all data associated with a removed reader. Adding the button also has the added benefit that it offers the editors the possibility to allow an existing reader to redo the study.

**Describe alternatives you've considered**
Another option would be to automatically remove all answers for a reader upon deletion. However, that could be unwanted in some cases. For instance, in the courses functionality that is currently under development (#1079), statistics for each case are also available. By automatically removing answers, valuable historical information could be omitted from these statistics. I therefore think it would be best to leave this decision to the editors of the reader study.

**Comment by MikeOverkamp-diag** [comment]
Who should we allow to perform this action? All reader study editors?

**Comment by jmsmkn** [comment]
Yes, should we add `delete_answer` object permission to the reader study editors groups?
