### ISSUE TITLE
Improve annotation admin pages

### ISSUE THREAD

**Issue by HarmvZ** [comic/grand-challenge.org#1135]
The graders have asked me to delete all annotations for one user for a specific image. There is currently no easy way to do this in the admin pages. I will need to find a way to make this possible. Probably by adding certain search_fields or list_filters.

Also, I have noticed that some admin pages take extremely long to load. For example the change page for a polygon annotation set. I think this happens because it has to load a lot of data which it does not do efficiently and because it makes all inline model fields are editable by default. It will most likely never happen that we need to change this data manually so those fields can all be set to read_only. It might also be better to just have some statistics there about the number of inline models and not show the actual inline models at all.
Example loading time for an admin page:
![image](https://user-images.githubusercontent.com/2001094/73462398-08bf9380-437c-11ea-9116-a6170c114176.png)

**Comment by jmsmkn** [comment]
Sometimes it is easier to do this via the python shell, especially if it is a 1 off. More powerful, but more risky. 

If the model has a foreign key to an object that exists in a large table (eg, users, images or image files especially) then it is best to make those fields read only (`readonly_fields` in your custom admin model).

**Comment by HarmvZ** [comment]
The changes decreased loading time from 33.16s to 107ms and size from 4.8MB to 3.9KB! 🚀
