### ISSUE TITLE
Dicom importer should modify the imported pixel data if DICOM tags specify this

### ISSUE THREAD

**Issue by silvandeleemput** [comic/grand-challenge.org#1140]
**Is your feature request related to a problem? Please describe.**

The current 4D Dicom importer #614, #962 (and future 3D Dicom importer #1060) do not account for several data post-processing steps specified by the DICOM tags that should probably be performed on import. I.e. from the ApplyDicomPixelModifiers MeVisLab source: 
https://mevislabdownloads.mevis.de/docs/2.8/FMEwork/ReleaseMeVis/Documentation/Publish/ModuleReference/ApplyDicomPixelModifiers.html

MeVisLab DICOM image importers such as ImageLoad or DirectDicomImport typically do not modify the imported pixel data even if DICOM tags might specify it differently. The module ApplyDicomPixelModifiers actually implements some of these operations which are required by such DICOM tags. Currently, supported operations are:

* Translation of index pixel data to RGB data described in the DICOM tags RedPaletteColorLookupTableDescriptor, GreenPaletteColorLookupTableDescriptor, BluePaletteColorLookupTableDescriptor, RedPaletteColorLookupTableData, GreenPaletteColorLookupTableData, and BluePaletteColorLookupTableData if the tag PhotometricInterpretation is PALETTE COLOR. Independent of the setting of Apply Palette Information the base output connector provides the intensity to RGB LUT, which, for example, can be passed to ApplyLUT alternatively.
* Conversion of YBR_FULL image data to RGB if the PhotometricInterpretation tag is YBR_FULL.
* Inversion of single color channel image data if the PhotometricInterpretation tag is MONOCHROME1.
* Scaling of pixel data with the value of the tag DoseGridScaling if the Modality tag is RTDOSE. These scalings are performed slice/frame specific if the tag DoseGridScaling tag is specifically available for frames.
* Scaling and shifting of pixel data with the value of the tags RescaleSlope and RescaleIntercept, respectively. These scalings are performed slice/frame specific if they are specifically available for frames.
* Optionally adapting the DICOM tags appended to the output image such that they are corresponding to the transformed pixel data. DoseGridScale, RescaleSlope, and RescaleIntercept are set to 1.0 or 0.0, respectively. PhotometricInterpretation is set to RGB in the cases YBR_FULL and PALETTE, and to MONOCHROME2 in the MONOCHROME1 case.
* Possibly contained DICOM information available in the input image will be displayed at the second output connector. Only overlays according to the current DICOM standard is displayed; overlays according to the retired DICOM standard are not displayed. See http://medical.nema.org/Dicom/2011/11_03pu.pdf, section C.9 for details.

**Describe the solution you'd like**
It would be good to take these data post-processing steps into account when converting them to MHD files, or certain algorithms will get into problems. Especially the scaling and shifting of pixel data with the value of the tags RescaleSlope and RescaleIntercept, respectively seems very important. 

**Describe alternatives you've considered**
We could leave the data as it is, but this probably breaks a lot of algorithms, which will expect most of these data modifications.

**Comment by MikeOverkamp-diag** [comment]
Scaling and shifting of pixel data with the value of the tags RescaleSlope and RescaleIntercept, respectively. These scalings are performed slice/frame specific if they are specifically available for frames.

Has been implemented, the rest still needs to be done.

**Comment by jmsmkn** [comment]
Transferred to https://github.com/DIAGNijmegen/rse-panimg/issues/10
