### ISSUE TITLE
Add model manager for ground truth answers

### ISSUE THREAD

**Issue by MikeOverkamp-diag** [comic/grand-challenge.org#1154]
With the addition of ground truth answers to the reader studies app, a lot of logic to fetch ground truth answers for a reader study has been added in several functions in the `ReaderStudy` model. It would be cleaner to move as much of this logic as possible to a separate model manager for the `Answer` model.

**Comment by jmsmkn** [comment]
I'm going to close this as I think it's just an implementation detail. Can be tackled when next working on this part of the codebase.
