### ISSUE TITLE
Add ability to hide columns in reader study statistics table

### ISSUE THREAD

**Issue by MikeOverkamp-diag** [comic/grand-challenge.org#1155]
In https://github.com/comic/grand-challenge.org/pull/1150 a column that contains the round truth for each question in a reader study has been added to the statistics view. For reader studies with a high number of questions it might be a good idea to have the ability to hide (a number) of these columns in order to maintain a clear overview of the data. 

Example code for hiding columns can be found in `result_list.html`.

**Comment by jmsmkn** [comment]
Moved to pitch input document.
