### ISSUE TITLE
Reader study detail page is slow for editors

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#1158]
With many readers the reader study detail page has slowed down for the reader study editor (28 readers, almost 1s TTFB). 

We should try to optimise some of these queries, and split up the pages into separate views.

**Comment by MikeOverkamp-diag** [comment]
I think this is mainly caused by the reader progress queries, so that would be the first place to optimize.

**Comment by MikeOverkamp-diag** [comment]
This is mainly caused by a massive amount of duplicate queries. I should still have some local WIP for this, but I'd have to dig a bit to recover it. This will take quite a bit of time to properly debug and fix I think.
