### ISSUE TITLE
Make the default interpolation for overlay masks use nearest neighbors when no workstation config is selected.

### ISSUE THREAD

**Issue by silvandeleemput** [comic/grand-challenge.org#1166]
**Is your feature request related to a problem? Please describe.**
For preparing the DDH presentation on 12-2-2020 I noticed that the overlay segmentations generated for my algorithm template were using a strange interpolation because I didn't specify any workstation configuration file. After Miriam created a workstation configuration for me with nearest-neighbor interpolation the segmentation overlay looked fine. See image:

![image](https://user-images.githubusercontent.com/3715102/74356718-1a169000-4dbf-11ea-9975-a979fe424885.png)

Reader studies might also be affected by this.

**Describe the solution you'd like**
Shouldn't we have nearest neighbor interpolation for overlay images by default?

**Describe alternatives you've considered**
@miriam-groeneveld Miriam already created a workstation configuration file that resolves this.

**Additional context**
@jmsmkn  I am unsure if this should be solved in grand-challenge or within cirrus-core. I am also not sure who to assign for this.

**Comment by jmsmkn** [comment]
This keeps coming up, it should be the default in CIRRUS for all workstations. OK by me to change this as people can always revert back to the broken mode with a config file.

**Comment by jmsmkn** [comment]
Oh, an should be in CIRRUS: https://github.com/DIAGNijmegen/rse-cirrus-core/issues/450
