### ISSUE TITLE
Add ground truth / scoring for all reader study answer types.

### ISSUE THREAD

**Issue by MikeOverkamp-diag** [comic/grand-challenge.org#1178]
In #1079 ground truth and scoring were added to reader studies. Currently the ground truth (and thus the scoring) only works for boolean and single line text answer types. This should be expanded to all available answer types.

More options should also be added to the available scoring functions.

**Comment by MikeOverkamp-diag** [comment]
Ground truth now works for all answers types. Scoring still needs to be updated.

**Comment by miriam-groeneveld** [comment]
Is it possible to add ground truth for annotations as well?

**Comment by jmsmkn** [comment]
Ground truth for annotations is not implemented. As this has been open for 2 years I think we can say that this is not important, but if I'm wrong about that then a pitch should be created.
