### ISSUE TITLE
Stuck on launching a reader study

### ISSUE THREAD

**Issue by njmhendrix** [comic/grand-challenge.org#1179]
When launching a reader study, the software hangs at the following screen: 

![hanging_reader_study](https://user-images.githubusercontent.com/47858231/74932349-dc7abe00-53e1-11ea-96f6-fe1061de2b48.PNG)

I get this issue when using the Chrome webbrowser, version 63.0.3239.132 (official build) (64-bits). The issue persists when I use different accounts. Also, opening the reader study in a guest or incognito window does not help. Do you perhaps know what is causing this?

**Comment by njmhendrix** [comment]
The problem seems to be caused by the firewall / network configuration of the hospital where I am logged in. I am closing this issue.

**Comment by jmsmkn** [comment]
This is not a firewall issue - Chrome 63 was released in December 2017 and is now discontinued. You should be on at least Chrome 80 (current stable) by now. Check with the IT administrators of the machine that you were using as soon as you can as it's obviously not getting updated.

**Comment by njmhendrix** [comment]
Thanks for the reply James, I contacted the IT administrators and they are going to look into it.
