### ISSUE TITLE
Add feedback on progress

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#1187]
Add support for showing feedback on progress after reading n cases, and at any time via the cirrus help modal.

**Comment by jmsmkn** [comment]
We have this with the verify answers stuff now, right?

**Comment by MikeOverkamp-diag** [comment]
It's not exactly the same as what is meant in this issue, but good enough for now. So let's leave this open with the lower priority.

**Comment by bramvanginneken** [comment]
I would prefer to be able to select for a reader study that the title of the klappertje that now lists the name of the study and holds the question displays which case you are at, e.g. 23/300. This text could be displayed next to the i icon that gives the Help modal. It used to be like that in the old e-learning workstation.

**Comment by jmsmkn** [comment]
This is done.
