### ISSUE TITLE
Verified Users

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#1193]
Would be nice to give users a twitter style blue tick.

**Comment by jmsmkn** [comment]
We could maybe do this with ORCID login: https://github.com/python-social-auth/social-core/blob/master/social_core/backends/orcid.py

**Comment by jmsmkn** [comment]
ORCIDs are not verified so that is out.

Use this so that only verified users can make challenges, algorithms, etc.

**Comment by bramvanginneken** [comment]
Suggestion for initial implementation. We have a link on the profile page where users can apply for Account Verfiication. This leads to a page with the following text:

[will add later]

**Comment by jmsmkn** [comment]
I'd prefer to try and find a way to do this automatically, with tens of thousands of users manual inspection will bog us down. We could do it by academic email domains: `@*.edu` in the USA, `@*.ac.uk` in the UK, but for several countries including the Netherlands this does not exist, but then we could build up our own list of trusted domains including some companies. However, this would require signing up by email and not through social logins. We can then still have a manual process to catch the other users.

**Comment by bramvanginneken** [comment]
So when you use google login, your user account email is only your gmail? Can’t we add a second email to an account? We could say that be a verified users you need to use your real name, your mail address should correspond to a verified institution (radboudumc and radboudumc.nl email in our case) and we need a web source that matches name and institute, eg http://www.diagnijmegen.nl/index.php/Person?name=Bram_van_Ginneken in my case, or a linkedin page. And we’ll ask them for orcid, google scholar, etc not sure what exactly. This would be a manual process, but if we only require registered users for Editor roles in challenges, algorithms, and limit the algorithm/viewer usage for non-registered users we will not get that many verified users.

**Comment by jmsmkn** [comment]
> So when you use google login, your user account email is only your gmail? Can’t we add a second email to an account? 

Not without a lot of work - three things are involved in this: the Django user model from `django.contrib.auth`, `django-userena` which provides user email verification without social login, and `python-social-auth` which provides social authentication. The default user model only allows 1 email per user, and both the login libraries use this same field. Unfortunately, it is not possible to modify the built-in Django user model, and it's really very difficult to migrate to a custom user model once you have existing users so we're sort of stuck with decisions made when setting up the project. These days, Django recommends using a custom user model from day 0, often with the `django-allauth` library that does all of this well: https://django-allauth.readthedocs.io/en/latest/overview.html

> We could say that be a verified users you need to use your real name, your mail address should correspond to a verified institution (radboudumc and radboudumc.nl email in our case) and we need a web source that matches name and institute, eg http://www.diagnijmegen.nl/index.php/Person?name=Bram_van_Ginneken in my case, or a linkedin page. And we’ll ask them for orcid, google scholar, etc not sure what exactly. This would be a manual process, but if we only require registered users for Editor roles in challenges, algorithms, and limit the algorithm/viewer usage for non-registered users we will not get that many verified users.

This sounds fine, but I'm thinking of many users for when we have algorithm submission for challenges, then every participant will be an algorithm creator.

**Comment by bramvanginneken** [comment]
Not sure I understand why this is a problem. We could have a field Secondary email, like we have Institution and Department. If main email is gmail or some other general provider, we fall back to secondary in the verification.

**Comment by jmsmkn** [comment]
> Not sure I understand why this is a problem. We could have a field Secondary email, like we have Institution and Department. If main email is gmail or some other general provider, we fall back to secondary in the verification.

No, that is not possible. As mentioned above we do not have a custom user model. There is only a secondary `Profile` model that links to a user that contains all of that secondary information, but this model *cannot* be used to authenticate a user. Migrating to a custom user model is weeks of work. These are things that should have been set up correctly in 2012.

**Comment by bramvanginneken** [comment]
Let’s call tomorrow and tak it thourgh. I think we misunderstand each other.

**Comment by jmsmkn** [comment]
I wrote a [Python implementation of JetBrains/swot](https://github.com/DIAGNijmegen/rse-pyswot) that provides verification for users that use their academic email address. This covers 8k users, and you now get a green user tick everywhere the profile link is used: 

![image](https://user-images.githubusercontent.com/12661555/94339942-38ec2e80-fffe-11ea-9acc-f9c1cfef6f08.png)

Next steps:
- Extend this with trusted corporate domains (e.g. FME is non-academic)
- Add a model for manual verification where users can create requests
  - Support users at trusted institutions who use social login: Ask the user to enter their institutional email, ensure that it is not used by another user (either as primary email or linked institutional address)
    - if it is academic or trusted corporate then get the user to verify by sending an email and entering a nonce, when that is done update `is_validated`
    - if the institution is not trusted then email support for review, the institution can then be added to the lists, or the verification manually approved
