### ISSUE TITLE
Add latest build date to django front page

### ISSUE THREAD

**Issue by silvandeleemput** [comic/grand-challenge.org#1199]
**Is your feature request related to a problem? Please describe.**
It is at the moment cumbersome to find the latest date grand-challenge was updated to know which changes were included. This could be solved by putting the latest update date at the bottom of the page.

**Describe the solution you'd like**
Adding a new templatetag for the update date which we can grab from the git repository.

**Describe alternatives you've considered**
A version number, but this is a hassle to maintain and requires additional lookup

**Comment by jmsmkn** [comment]
The date isn't really informative and makes it hard to track back, the commit ID is more useful and is available from the deployment.
