### ISSUE TITLE
Group permissions to view all algorithms and reader studies

### ISSUE THREAD

**Issue by AjayPatel86** [comic/grand-challenge.org#1204]
It would be nice to be able to give certain users permission to view all algorithms and reader studies.

**Comment by cjacobs1** [comment]
In addition, I would really like it if I could see all private algorithms of our organization, such that I can request access to the ones I am interested in. Right now, I can only see the public algorithms, and the ones I have been invited to, but I cannot see the remaining private algorithms of our organization (DIAG). So, I guess my request concerns organization permission levels.
