### ISSUE TITLE
Preserve (Imager) Pixel Spacing attribute after uploading DICOM file

### ISSUE THREAD

**Issue by njmhendrix** [comic/grand-challenge.org#1216]
I created a processor for the Algorithms feature that takes DICOM files of x-rays as input. It requires the (Imager) Pixel Spacing attribute in order to scale a given input image (normalizing the size of the object of interest), but it seems that all attributes/headers are removed from the DICOM file after uploading it. Is it possible to put both the "Pixel Spacing" (tag: 0028,0030) and "Imager Pixel Spacing" (tag: 0018,1164) attribute on a whitelist, so that they are preserved after uploading the file? For now, perhaps I could ask users to resize the image themselves and upload a modified DICOM file.

**Comment by jmsmkn** [comment]
Can you share an example DICOM email with my radboud email? Thanks.

**Comment by MikeOverkamp-diag** [comment]
@njmhendrix The PixelSpacing attribute is used to set the spacing in the imported image (we use mha as an internal image representation for all files, so the dicom is converted to mha). 

James has forwarded the image you sent him to me, but in that one the Imager Pixel Spacing is the same as the normal Pixel Spacing. 

Could you maybe send me a file where they differ? And maybe give me some pointers on how to use the Imager Pixel Spacing to manipulate the size of the object of interest? We can discuss via Slack or Zoom if you want.

**Comment by njmhendrix** [comment]
Hi Mike, thanks for looking into it, I sent you an email (to your gmail account) with a new DICOM file and additional details about the resizing operation.

**Comment by njmhendrix** [comment]
I further investigated the problem and it appears that the pixel spacing is not removed after uploading the file, whereas the meta data keys are removed indeed. The GetSpacing function of the SimpleITK library correctly returns the pixel spacing, but the GetMetaDataKeys function returns no keys. Since I tried to get the (imager) pixel spacing by accessing the corresponding meta data key, I concluded that the pixel spacing attribute was removed and created this issue. 

Thus, this issue can be closed, but perhaps I can start another issue on the removal of the meta data keys. For instance, I also want to access the laterality tag so that the image can be automatically flipped (my algorithm only works on right hands).

**Comment by MikeOverkamp-diag** [comment]
> I further investigated the problem and it appears that the pixel spacing is not removed after uploading the file, whereas the meta data keys are removed indeed. The GetSpacing function of the SimpleITK library correctly returns the pixel spacing, but the GetMetaDataKeys function returns no keys. Since I tried to get the (imager) pixel spacing by accessing the corresponding meta data key, I concluded that the pixel spacing attribute was removed and created this issue.
> 
> Thus, this issue can be closed, but perhaps I can start another issue on the removal of the meta data keys. For instance, I also want to access the laterality tag so that the image can be automatically flipped (my algorithm only works on right hands).

Please do :slightly_smiling_face:. We currently omit all tags, except for a set of predefined ones in the code. I think for your use case, and probably a lot of future ones, it would make sense to have users submit a list that they would like to preserve in the file headers and make things more dynamic that way.

**Comment by njmhendrix** [comment]
Thanks for your reply, I will!
