### ISSUE TITLE
Cannot link annotations with file constructed from uploaded DICOM

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#1221]
Uploaded DICOM that is reconstructed from multiple 2D files is given a UUID for a filename, this makes it impossible to track back to the studyId when making an annotation. 

Single DICOM files are ok as the filename is passed.

Update the DICOM importer to somehow keep this link.

**Comment by xarion** [comment]
it'd be great if we could refer to the StudyInstanceUID, which is common among all of the cases in the same study.

**Comment by jmsmkn** [comment]
Discussed on slack, the format of the filename will be `{upload_session.pk}-{studyInstanceUID}`
