### ISSUE TITLE
Allow PatientID, PatientName and StudyDate through in metadata of mha/mhd,zraw

### ISSUE THREAD

**Issue by cjacobs1** [comic/grand-challenge.org#1228]
See title. This metadata is scrubbed of during import, but should stay, because it can be used by the ImageInfoPlugin

**Comment by jmsmkn** [comment]
Are you going to do the same for DICOM? Maybe extend the help text in `app/grandchallenge/cases/forms.py` L22-L25 to include a warning that data should be deidentified by the user?

**Comment by cjacobs1** [comment]
> Are you going to do the same for DICOM? Maybe extend the help text in `app/grandchallenge/cases/forms.py` L22-L25 to include a warning that data should be deidentified by the user?

Good idea. But I will create a separate issue for that
