### ISSUE TITLE
Store PatientID, PatientName and StudyDate in metadata of mha in dicom image builder

### ISSUE THREAD

**Issue by cjacobs1** [comic/grand-challenge.org#1233]
Related issue: #1228

**Comment by jmsmkn** [comment]
Also required is Patient Age and Sex. 

What is the status on this? It needs to be done today but we need to avoid double work, can I do anything to help?

**Comment by cjacobs1** [comment]
I am swamped with many other things. Based on the mha changes that I did yesterday, I think Mike could take this over?
