### ISSUE TITLE
Populate and rework Patient and Study models to become useful

### ISSUE THREAD

**Issue by pkcakeout** [comic/grand-challenge.org#1237]
The Patient and Study models exist but remain mostly unused in grand-challenge right now. There are several projects that would benefit from these organizational objects to be implemented.

Right now, the ticket is open for use-case collection. Please post:

- The application
- What kind of data structures you want to use for image management
- How they are going to be used/what kind of data needs to be stored in each of these objects.

**Comment by pkcakeout** [comment]
# Cirrus Oncology

For Cirrus Oncology, it would be ideal to have three levels for organizing images:

* Archives
* Studies
* Patients

## Archives

Archives should form the center of image management. Images are added to archives directly. The intermediate Patient and Study objects do not play a direct role here.

Archives should have names and an owner. New images (always DICOM) are uploaded to an archive (= _target archive_). Within a target archive, it can be assumed that all DICOM UIDs, including the PatientID are unique. This means that an uploaded Image will be compared to all other images in the archive and if there are Patients and Studies with corresponding IDs are existing already, they are reused for that objects (See sections below).

After an image is uploaded, images should be sharable with other archives. This means that an image uploaded for archive A can be copied into an archive B. 

## Study

A study is created from a DICOM image... 

## Patient

**Comment by cjacobs1** [comment]
For CIRRUS Lung Screening, the requirements are similar as for CIRRUS Oncology.
However, the Series level would also be needed. I can write it out more extensively later. @pkcakeout : I think you will also need the Series Level for CIRRUS Oncology

**Comment by bramvanginneken** [comment]
We also need some tag system, so a study does not belong to one archive or at least can be flexibly added to many collections.

**Comment by jmsmkn** [comment]
An image can belong to many archives, reader studies, or a job for any algorithm.

**Comment by jmsmkn** [comment]
Much of this can now be achieved with Archive Metadata (https://github.com/comic/grand-challenge.org/pull/1836). A pitch should be made for anything more substantial.
