### ISSUE TITLE
Mha writing takes a long time

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#1240]

**Comment by jmsmkn** [comment]
This upload session: https://grand-challenge.org/cases/uploads/197a2be8-38f6-4aa9-a3b4-fc1ab682ba35/

12 files, 11 minutes.

**Comment by jmsmkn** [comment]
This is the case for all files, and the culprit is itk compression, it is single threaded. It saves us 60% in storage space on a typical DICOM, and a lot more on segmentation files, so I would prefer to leave this as is. Maybe we can add it as a secondary import step?

**Comment by jmsmkn** [comment]
Timings - 1 minute 20s with compression, 4s without.

**Comment by bramvanginneken** [comment]
I noticed the mha I download from grand-challenge has float as datatype, short is enough.

**Comment by jmsmkn** [comment]
Going to short types cuts 1 minute off the compressed saving, leaving 20s per imported file. As the rescale slope and intercepts are applied this can only be done if they are all 1 and 0 respectively. I will do this as it is simpler to fix than the 2-stage approach.

**Comment by jmsmkn** [comment]
Transferred to https://github.com/DIAGNijmegen/rse-panimg/issues/9
