### ISSUE TITLE
Reader study answers mine needs to be filtered by the current reader study

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#1262]
When CIRRUS launches it will query the mine endpoint to get all of the answers. For people who have a lot of answers, this could mean iterating over 10,000+ answers, slowing down the startup and causing errors when creating answers with new features: 

https://github.com/DIAGNijmegen/rse-cirrus-core/blob/aaa81af6a6fc606405d804f49e74c63b2b2515a4/src/cirrus/DIAG/CIRRUSCore/Modules/Macros/CIRRUSCoreWeb/CIRRUSCoreWeb.py#L1707

We need to offer a filter by reader study pk on grand challenge, and use that filter in CIRRUS.

**Comment by MikeOverkamp-diag** [comment]
Closed by #1269
