### ISSUE TITLE
Improve the selection method for creating reader studies with subsets of archives

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#1267]
Requires:

- Indexing of patient and study (in metadata already)
- Filtering and adding items from a table (?)

**Comment by csital** [comment]
I would definitely be interested in this feature. I also know that the data team wants to start using archives to assist the clinical people from the hospital with conducting reader studies on GC. So it would be useful for that as well.

**Comment by jmsmkn** [comment]
Right now you can limit the selection with a bit of js. This feature will soon be overhauled and we will work on a better selection method as part of that.
