### ISSUE TITLE
Add pagination and server side search to archive cases list and upload list

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#1268]

**Comment by jmsmkn** [comment]
This was added for algorithm results in #1386 - would be good to re-use that implementation

**Comment by nlessmann** [comment]
Could this issue receive higher priority? The experiments page of the CORADS algorithm takes quite long to load now and on my phone it's completely unusable.

**Comment by jmsmkn** [comment]
That's a separate view to the ones mentioned in this issue and will be removed soon anyway as it creates a circular dependency between applications that we need to break. The only extra information there is the failed job status which we can add to the results which are already paginated instead.
