### ISSUE TITLE
Expand test suite for dicom loader

### ISSUE THREAD

**Issue by MikeOverkamp-diag** [comic/grand-challenge.org#1279]
The dicom loader is currently tested with a very limited number of test files. A lot more test images are available at Radboudumc, but not all of these can be included in this repository. 

It would still be very valuable to be able to test with these files locally, so for the test files that cannot be used publicly, we need to add a marker and a separate solution for automated testing (e.g. Jenkins).

**Comment by sjoerdk** [comment]
I ran into this problem when create anonqa. I wrote this for it.

https://github.com/sjoerdk/dicomgenerator

Might be useful if you want to generate arbitrary DICOM permutations. It generates pydicom datasets in memory so you can also generate without writing to disk.

**Comment by sjoerdk** [comment]
Currently it does only CT, but you can generate templates quite easily:
https://github.com/sjoerdk/dicomgenerator/blob/master/examples/collect_data_from_existing_dicom.py

**Comment by jmsmkn** [comment]
Transferred to https://github.com/DIAGNijmegen/rse-panimg/issues/8
