### ISSUE TITLE
DICOM importer should return a nicer error if the transfer syntax is not supported

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#1293]
Would be nice to get gdcm in here, otherwise, raise a proper error if the syntax is not supported: https://pydicom.github.io/pydicom/stable/old/image_data_handlers.html

**Comment by pkcakeout** [comment]
Not sure if there is a pip package for GDCM in the mean time. I f you need help configuring a build system for this, reach out to me. I think that we can automate building our own pip-packages in about 4 hours (I did that before).

**Comment by jmsmkn** [comment]
Could be handy: https://github.com/HealthplusAI/python3-gdcm#local-buildinstall-instruction

Be careful to link against the correct python interpreter

**Comment by jmsmkn** [comment]
Had a couple of hours to fill this afternoon so I've made quite a lot of progress on getting GDCM to work, in 6552d48 there is now a dockerfile that builds the latest release of GDCM against the python version that we use, and it seems ok. I'm using the release guide from here: https://github.com/malaterre/GDCM/blob/master/Utilities/Release/config.linux, here: https://github.com/malaterre/GDCM/blob/master/PACKAGER and some guidance from here: https://github.com/HealthplusAI/python3-gdcm#local-buildinstall-instruction. One thing is that it does not link to VTK, but I'm unsure if we need that.

This takes quite a while, so we should use this as a base image for the django build, and maybe incorporate the system libraries in there. But, maybe we can do that in a separate PR.
