### ISSUE TITLE
Feature request: support for text files

### ISSUE THREAD

**Issue by Whardian** [comic/grand-challenge.org#1295]
**Is your feature request related to a problem? Please describe.**
I am currently working on a reader study in which users have to label radiology reports from thorax CT studies, i.e. indicate whether suspicious lesions in the lungs are mentioned. However, I cannot upload texts to grand-challenge. 

**Describe the solution you'd like**
It would be great to add text files (.txt extension, utf-8 encoding) to a reader study and show them next to the questions (e.g. as an inline frame). 

**Describe alternatives you've considered**
I can bypass this problem by converting reports to fixed-sized png images. However, this solution does not work for long reports. Furthermore, the images need to be in a specific ratio and texts need to be wrapped so that reports are correctly loaded.

**Comment by jmsmkn** [comment]
You can use the case text field in the reader study settings, eg:

````
{
  "image_name.mha": "Radiology report in markdown format...",
  "image2.mha": "# Heading\n",
  ...
}
```

**Comment by Whardian** [comment]
![Knipsel](https://user-images.githubusercontent.com/50408624/79108045-ce0fa980-7d75-11ea-8dc8-2045e69a4e2b.PNG)

Hi James, case texts are not displayed correctly in my chrome browser. What can I do to fix this?

**Comment by jmsmkn** [comment]
That is an issue with CIRRUS then. Make a new issue in that repo https://github.com/diagnijmegen/rse-cirrus-core
