### ISSUE TITLE
DICOM importer does not check for missing slices / inconsistent slice spacing

### ISSUE THREAD

**Issue by MikeOverkamp-diag** [comic/grand-challenge.org#1301]
Volumes with inconsistent slice spacing should probably raise a `ValidationError`.

**Comment by pkcakeout** [comment]
I was wondering a little but. This will bite us again if we make this too strict. I am pretty sure that right we want the `ValidationError` but I also remember that is was super-hard in our old application to read scans where "one slice was missing" and we were frantically searching for a way to do it in our applications. Therefore, we could say that the current way it works "reading scans with missing slices" is a feature as well.

Just want to dump this here as a word of caution. This current "sloppyness" is a nice to have feature - especially for research. I have no idea how to retain this in one case though and disable it in the other. Maybe implement an internal flag for this to enable "sloppy" mode on demand? No idea.

Like I said, just a word of caution. Not sure what to do about this.

**Comment by bramvanginneken** [comment]
Instead of sort of redoing what we’ve done years ago, getting archives and dicom tools right, let’s not reinvent but discuss with Colin and use his approach from the past.

**Comment by jmsmkn** [comment]
Transferred to https://github.com/DIAGNijmegen/rse-panimg/issues/7
