### ISSUE TITLE
Algorithm: processor docker fails when setting num_workers > 0 in pytorch DataLoader

### ISSUE THREAD

**Issue by xieweiyi** [comic/grand-challenge.org#1305]
**Describe the bug**
If the processor docker is built using Pytorch DataLoader with num_workers > 0, the processing job will result in a timeout error. 

**To Reproduce**
Build a processor docker using Pytorch DataLoader with num_workers > 0.
Upload the docker as an algorithm
Upload a job.
Timeout

**Expected behavior**
Probably return results

**Screenshots**

**Versions(please complete the following information):**
 - Pytorch: 1.1.0

**Comment by jmsmkn** [comment]
Ok, the problem is within your containers, don't use that setting.

**Comment by pkcakeout** [comment]
Shared memory is 0 most likely!
