### ISSUE TITLE
Participants docker upload

### ISSUE THREAD

**Issue by mattmagic149** [comic/grand-challenge.org#1307]
"In 2020 we will start hosting challenges where participants can upload their algorithms in the form of Docker containers, which will be applied to the test data. This way of running challenges avoids that the test data is made available to challenge participants. We have also implemented the possibility to upload algorithms that users can try out with their own data, and web-based interactive browsers that can be used for reader studies. We plan a broader roll-out of this functionality in the near future."

Is this feature already available?

Cheers,
Matt

**Comment by bramvanginneken** [comment]
Hi Matt,

We're close to testing it in a new big challenge, but not yet available to
everybody.

Best, Bram
