### ISSUE TITLE
Multiple leaderboards

### ISSUE THREAD

**Issue by mattmagic149** [comic/grand-challenge.org#1310]
We are hosting a challenge including segmentation, detection, and classification. For the sub-challenges, we would like to have separate leaderboards. Is there any option to do so within one challenge, or should we host three individual challenges?

**Comment by jmsmkn** [comment]
You can display different metrics in the same table, but at the moment there is only 1 leaderboard per challenge. A PR to this repo that separates out the leaderboard configuration from the challenge would be welcome.

**Comment by mattmagic149** [comment]
Thank you for the quick response!
