### ISSUE TITLE
zoom with mouse wheel

### ISSUE THREAD

**Issue by aswolinskiy** [comic/grand-challenge.org#1311]
Currently, zooming is only possible by moving the mouse when in the toolbox 'ZoomOnMouse' is selected. To move to a different portion of the slide it is necessary to select 'Pan' in the toolbox. If zoom were possible with the mouse wheel it would be possible to do both actions without having first to select the corresponding tool in the toolbox. Most viewers, for example ASAP, support zoom via the mouse wheel. If a viewer has to watch different parts of the slide at different zoom-levels it will be very time-consuming (and annoying) for her to always have to go the toolbox for each switch between zoom and pan.

**Comment by jmsmkn** [comment]
This is an issue for [CIRRUS](https://github.com/diagnijmegen/rse-cirrus-core) or the workstation that you're using, not grand-challenge.
