### ISSUE TITLE
Allow null in annotation answers

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#1313]
For string answers we allow empty strings to represent that the question was skipped.

For annotations and choices the front end skips submitting an answer if skipped, causing this issue: https://github.com/DIAGNijmegen/rse-cirrus-core/issues/635

So, we need to represent a question being intentionally left blank, and the way to do this is to add optional `null` (JSON/in the db)/`None` (python) to the schema for the non-boolean & string answer types.

**Comment by jmsmkn** [comment]
@pkcakeout let me know if you agree with this approach

**Comment by pkcakeout** [comment]
Yes, storing an explicit `null`/`None` would be fine and a great solution. Alternatively (just in case that is easier to implement) and empty list or dictionary would also work from the cirrus side (for annotations).

**Comment by jmsmkn** [comment]
No difference in complexity I think - I will first go with explicit `null`/`None`.
