### ISSUE TITLE
Ability to display an additional image on answer submission (or verification)

### ISSUE THREAD

**Issue by MikeOverkamp-diag** [comic/grand-challenge.org#1322]
For educational reader studies there is a request to have a reader answer a question, then show a different image (or an added overlay) after the reader has submitted (or verified) their answers. 

An example use case for this would be that the reader has to indicate whether or not something is present in the image. Then on submission, an overlay can be shown that highlights the areas of interest.

**Comment by jmsmkn** [comment]
This can be achieved by disabling the no duplicate images check, and then adding a second hanging with the overlay.
