### ISSUE TITLE
Define output filenames of algorithms

### ISSUE THREAD

**Issue by AjayPatel86** [comic/grand-challenge.org#1326]
Some algorithms produce multiple segmentations. Currently they are all named 'output.mha'. Would be nice if we could define the output filename to be displayed on the results page.

![image](https://user-images.githubusercontent.com/15669173/80084020-9ca59380-8556-11ea-977c-8ef56116500a.png)

**Comment by jmsmkn** [comment]
This will be done as part of the interfaces update (https://github.com/comic/grand-challenge.org/tree/til_interfaces), but this is on hold for the COVID effort.

**Comment by bramvanginneken** [comment]
I think algorithms should be able to produce a variable amount of output files of different kinds. I think we should support txt, html, pdf, MD. And have plugins in CIRRUS that can display such output and can be configured to show certain output particular to an algorithms. We've always worked, and still work in bodyct, with a derived folder in an archive. The names of these folders would indicate the name of the output (eg 256 for a resampled version of the input, chunk for a cropped version of the input, cropped around a segmented object, cadm for txt files with cad marker locations, etc). The names of the files in these folder were the patientid, studyinstanceuid or the seriesinstanceuid, depending on the level at which the algorithm produces output.) I would be in favor of copying this logic in grand-challenge.
