### ISSUE TITLE
Allow challenge admins to hide all results at once

### ISSUE THREAD

**Issue by HarmvZ** [comic/grand-challenge.org#1331]
Clarisa has asked me to hide all results for the ICON challenge so it can be reused for the ISMI course this year. This can be done by manually clicking the "Hide result" button for each evaluation job but that is a tedious task if there are a lot of jobs. It would be easier if challenge admins have the ability to hide all results at once. To solve this we could add a button to the top of the `/evaluation/jobs/` page to hide all results at once.

**Comment by jmsmkn** [comment]
Users can email support and we can do this in the Django admin. If they accidentally click on this, then the state would be very hard to recover otherwise.
