### ISSUE TITLE
Add support for .nii and .nii.gz images

### ISSUE THREAD

**Issue by nlessmann** [comic/grand-challenge.org#1344]
This would be a useful feature since this format can be easily read and written with SimpleITK, has similar features to mha/mhd and is quite popular.

**Comment by nlessmann** [comment]
nrrd would also be useful, also supported by simpleitk

**Comment by jmsmkn** [comment]
I don't think that the RSE team should prioritise this as these are research formats, and researchers are capable of converting those images to mhd/mha themselves. However, if you would like this, contributions are welcome :-)

To get started, you would need to add a new image builder, probably the fallback builder is a good guide:

https://github.com/comic/grand-challenge.org/blob/master/app/grandchallenge/cases/image_builders/fallback.py

And then this would need to be enabled here:

https://github.com/comic/grand-challenge.org/blob/master/app/grandchallenge/cases/tasks.py#L161

Also, it would need some test data:

https://github.com/comic/grand-challenge.org/tree/master/app/tests/cases_tests

**Comment by bramvanginneken** [comment]
I think people uploading to Algorithms are mostly researchers and I think it would make sense to support image formats that simpleitk can read. It would also be good if many people in DIAG would be able to make these contributions.

**Comment by jmsmkn** [comment]
That's what I was trying to get at, I'm happy to guide a non-RSE through implementing this.
