### ISSUE TITLE
Readerstudy write initial user docs

### ISSUE THREAD

**Issue by sjoerdk** [comic/grand-challenge.org#1359]
**Is your feature request related to a problem? Please describe.**
For non-technical people it is currently hard to create a reader study from scratch. Where to start? what do you need to get started?

**Describe the solution you'd like**
Very basic documentation for non-technical users who want to set up a reader study. Which url to load, which buttons to click, what options there are for uploading images, getting readers to participate, etc. The aim is to answer the basic questions, leaving developers to focus on more complicated requirements.

**Describe alternatives you've considered**
Just letting the GUI speak for itself. This is fine to an extent, but does not answer broader questions like 'What should potential readers do to be able to participate'
I've looked at
https://grand-challenge.org/Support/, which did not cover this topic
and
https://grand-challengeorg.readthedocs.io/en/latest/reader-studies.html which seems targeted at developers

**Comment by sjoerdk** [comment]
Have I missed any location for current documentation?

**Comment by sjoerdk** [comment]
I think the best place for user documentation would be https://grand-challenge.org/Support/.  Do  you agree @MikeOverkamp-diag @jmsmkn ?

If so, could I get permissions to edit https://grand-challenge.org/Support/?

**Comment by jmsmkn** [comment]
Yes, Kiran is also adding documentation so sync with him, but it is delayed due to COVID. Maybe a new page - create your own reader study? I will give you permissions.

**Comment by jmsmkn** [comment]
Can this be marked as completed now that this page is here https://grand-challenge.org/create-your-own-reader-study/ ?

**Comment by sjoerdk** [comment]
Yes this is complete. Sorry forgot to update this issue.
