### ISSUE TITLE
Add endpoint to return image data

### ISSUE THREAD

**Issue by HarmvZ** [comic/grand-challenge.org#1363]
To work correctly with https://github.com/DIAGNijmegen/rse-cirrus-core/issues/699 I need an endpoint that returns image meta data for a specific image id.

**Comment by jmsmkn** [comment]
I don't really understand this, doesn't `/api/v1/cases/images/{pk}/` do this already? What metadata do you mean?

**Comment by HarmvZ** [comment]
It would be nice if I can use that endpoint, but there are a few issues with that. The metadata I need is defined here:
https://github.com/comic/grand-challenge.org/blob/f6e540054ced4586d09338db39422e372a6ebaca/app/grandchallenge/retina_api/serializers.py#L84-L91

So it would require me to make some more requests to get:
- The related archive names. This data can be fetched in one request using the retina archive endpoint, but then I would need to parse the hyperlinked related field to a uuid which seems a bit hacky.
- The related patient name and related study names which there is no endpoint for yet I think? There is also no nice way to get that data via the retina archive endpoint without knowing the parent id.
- The related modality name. I don't know if this field is used by clients that use this endpoint. If not then we can use the `ImagingModalitySerializer` here to include the related modality model.

Maybe a nice way to accomplish this is by overriding the `get_serializer_class()` method and using a retina-specific serializer if a certain query parameter is passed?

**Comment by jmsmkn** [comment]
> The metadata I need is defined here

All those fields are already available on the `ImageSerializer`. 

> The related archive names. This data can be fetched in one request using the retina archive endpoint, but then I would need to parse the hyperlinked related field to a uuid which seems a bit hacky.

You can fetch the url directly, no need to parse it, that's why we use hyperlink serializers.

> The related patient name and related study names which there is no endpoint for yet I think? There is also no nice way to get that data via the retina archive endpoint without knowing the parent id.

The serializers are there but I think the views were removed as the permissions for them were not clear. Probably we need to filter on image permissions.

> The related modality name. I don't know if this field is used by clients that use this endpoint. If not then we can use the ImagingModalitySerializer here to include the related modality model.

Probably not given there's not a way to look up the modalities from the API right now.

It would be good if we can stick to 1 API.

**Comment by HarmvZ** [comment]
I agree that it would be good if we could stick to 1 API, but I am a bit hesitant to use the existing endpoint as that it will require me to make at least 4 extra requests per image (archive, patient, study, modality). I would rather join that data on the backend and get it in one request.

**Comment by jmsmkn** [comment]
@HarmvZ Is this still needed?

**Comment by HarmvZ** [comment]
It's not quite solved but I used a workaround now and it remains low priority so it probably will never be solved.
