### ISSUE TITLE
Add perfusion map functionality

### ISSUE THREAD

**Issue by MikeOverkamp-diag** [comic/grand-challenge.org#1364]
For one of the demo cases for the educational features, we need to allow users to upload perfusion maps. 

The perfusion maps are a series of jpg-files, which should be presented as a single scrollable image. The order in which the images should be arranged seems to be embedded in the filename (at least at Radboudumc), but we could also opt to let the uploader indicate the desired ordering, which to me seems like the more robust option.

Readers should then be able to add the perfusion map as part of a hanging and view it in the workstation. The easiest way to do this would probably be to treat the map as any other image once it has been constructed.

**Comment by MikeOverkamp-diag** [comment]
I am currently investigating why separate jpgs are used for the perfusion map, rather than dicom. Ideally these should be provided as dicom files.

**Comment by bramvanginneken** [comment]
I do not think you should be making ad hoc tools for this. Please let us know who is the contact person, which software produces these maps, and involve Ajay Patel.

**Comment by jmsmkn** [comment]
They will export the data as DICOM.
