### ISSUE TITLE
Cannot import DICOM with non-integer window levels.

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#1367]
I think you can have non int window and level, please also check for the MHD loader
Dicom image builder: invalid literal for int() with base 10: '1906.5'

**Comment by MikeOverkamp-diag** [comment]
@jmsmkn do you think we should cast to int, or just accept floats? I don't think CIRRUS accepts floats, correct? Of course other workstations might.

**Comment by jmsmkn** [comment]
Yes, in DICOM these values are Decimal Strings, so we must accept them. CIRRUS should use them but that is another issue.

**Comment by jmsmkn** [comment]
Sorry - to be clear, do not cast to int in the backend, choose what to do with that data in CIRRUS.
