### ISSUE TITLE
Manual leaderboard update

### ISSUE THREAD

**Issue by mattmagic149** [comic/grand-challenge.org#1370]
Hi,

we are currently hosting a challenge on GC. At the moment we allow the participants to upload
the solution in two formats - the predicted results, which we evaluate with evalutils and the solution in form of a docker. The former format evaluation works perfectly fine.
For the docker upload we are planning to copy the uploaded zip to our own machine and execute the docker there. Since this is a very expensive operation we are looking for an option to update the results database manually or semi-automatic. Is there an option to insert results linked to a specific participant and show these results in the leaderboard?

Regards,

Matt

**Comment by jmsmkn** [comment]
Your best bet for this right now is to create a new page for your challenge, and then use a templating library to create the page html for you (eg, jinja2). It is possible to then post this automatically using say, requests (login, get the page update form, post the new data along with the csrf token).

We are actively working on adding algorithm submissions and executing them on our infrastructure. Depending on when your challenge is you might be able to use that, please email us if you would be interested in that.

**Comment by mattmagic149** [comment]
> Your best bet for this right now is to create a new page for your challenge, and then use a templating library to create the page html for you (eg, jinja2). It is possible to then post this automatically using say, requests (login, get the page update form, post the new data along with the csrf token).

Can you elaborate, what page I am creating? Is it an additional page for the docker upload?
We would also like to combine the evalutils results with the docker results on the leaderboard.

> 
> We are actively working on adding algorithm submissions and executing them on our infrastructure. Depending on when your challenge is you might be able to use that, please email us if you would be interested in that.

This is definitely of interest to us. However, the challenge is already live and will be due on July 5th.

**Comment by jmsmkn** [comment]
> Can you elaborate, what page I am creating? Is it an additional page for the docker upload?
> We would also like to combine the evalutils results with the docker results on the leaderboard.

It is not possible for you to update the generated leaderboard, you will need to combine it yourself if you want to do this on a new page. You can do that here https://<your_challenge_name>.grand-challenge.org/pages/create/. Then you will need to keep that page up to date.

All of the evaluation logic is based on there only being 1 type of submission per challenge, it breaks down when you have 2 (a set of predictions or a docker container image in your case).

**Comment by mattmagic149** [comment]
> It is not possible for you to update the generated leaderboard, you will need to combine it yourself if you want to do this on a new page. You can do that here https://<your_challenge_name>.grand-challenge.org/pages/create/. Then you will need to keep that page up to date.
> 
> All of the evaluation logic is based on there only being 1 type of submission per challenge, it breaks down when you have 2 (a set of predictions or a docker container image in your case).

I see. Alternatively, can I copy the docker at submission time to our machine, execute the docker remotely in a blocking call, get back the results and run the evaluation on GC?

**Comment by jmsmkn** [comment]
Creating a new submission each time? That would work, you would have the same user for the submission though.

I don't know what you mean by blocking call. In your evaluation container? They have no access to the internet.

**Comment by mattmagic149** [comment]
Ok thanks for the clarification.
I appreciate your help!

**Comment by jmsmkn** [comment]
No problem! Good luck with your challenge.
