### ISSUE TITLE
Look into various formats for window center and width in dicom files

### ISSUE THREAD

**Issue by MikeOverkamp-diag** [comic/grand-challenge.org#1376]
We added support to extract window levels from dicom files. However, we assume that these are numerical values, while they apparently can also be lists (#1374). For now we only add them if they are in fact numerical, but we should look into the meaning of other formats and support them as well.

**Comment by jmsmkn** [comment]
@nlessmann encountered this today: the value of WindowCenter in the header is `WindowCenter = [60, 60]`.

**Comment by nlessmann** [comment]
This can lead to the weird situation that mha files generated by the DICOM importer are rejected by the mha importer.

If there are multiple values, I think they are alternative window/level settings. So it should be fine to just store the first one in the database and to adjust the mha header whitelist to accept lists as well.

> If multiple values are present, both Attributes shall have the same number of values and shall be considered as pairs. Multiple values indicate that multiple alternative views should be presented.

From https://dicom.innolitics.com/ciods/digital-x-ray-image/dx-image/00281050

**Comment by jmsmkn** [comment]
Indeed, that is weird. The MHA importer is more strict when it comes to validating the content of headers, and it's always irked me that there is this difference between the DICOM and MHA header validation, this should be unified so that we don't get similar issues with other headers.

**Comment by jmsmkn** [comment]
Transferred to https://github.com/DIAGNijmegen/rse-panimg/issues/6 and https://github.com/DIAGNijmegen/rse-panimg/issues/5
