### ISSUE TITLE
Questions are obscured in Reader Studies

### ISSUE THREAD

**Issue by kiranvaidhya** [comic/grand-challenge.org#1384]
The questions in Reader Studies have some bugs. The text gets obscured and is not formatted properly. The Reader Study is available here - **[User Doc Test](https://grand-challenge.org/reader-studies/user-doc-test/)**

**To Reproduce**
Add yourself as a Reader for User Doc Test and try reading the images.

**Expected behavior**
Questions are expected to be formatted the right way. The question posed was "Is this a medical image?"

**Screenshots**
The formatting is quite unstable. Here it is "Is this a medical ...."

![image](https://user-images.githubusercontent.com/10166968/83746264-2456e580-a65f-11ea-93ba-5331669b0780.png)

And here it is ".... image?"
![image](https://user-images.githubusercontent.com/10166968/83746840-fb832000-a65f-11ea-996c-73861964b75c.png)

**Desktop:**
 - Windows 10
 - Chrome
 - 83

**Additional context**
I'm currently working on adding documentation for users of Reader Studies. I and Sjoerd have added User Doc Test as a new reader study to test, document, and guide new users.

**Comment by jmsmkn** [comment]
This is an issue with CIRRUS, not grand challenge. You should make a new issue there, but I'm pretty sure that one already exists for this, find that and make a comment.
