### ISSUE TITLE
Reader studies: incorrect progress indication

### ISSUE THREAD

**Issue by njmhendrix** [comic/grand-challenge.org#1391]
**Describe the bug**
My current reader study dataset consists of 200 cases, but when reviewing the first case, the information window indicates that there are 201 cases left to read. The progress indication of the navigation widget is correct though: 
<img width="221" alt="navigation_widget" src="https://user-images.githubusercontent.com/47858231/84133746-d1f33b80-aa47-11ea-85bf-e4537b56cd7f.PNG">.  

**To Reproduce**
1. Go to "Reader Studies".
2. Select any reader study.
3. Click "Launch this Reader Study". 
4. Click on the information button <img width="18" alt="info_button" src="https://user-images.githubusercontent.com/47858231/84133499-8b9ddc80-aa47-11ea-8fba-2fbcff79b2a1.PNG">.
5. The number of cases that are left to read should be incorrect.

**Comment by jmsmkn** [comment]
This is an issue with CIRRUS, not grand challenge. As a guide, if you can see a grey sidebar, that is CIRRUS. Please make your issue in the CIRRUS repo.
