### ISSUE TITLE
Reader studies: failure to store answers

### ISSUE THREAD

**Issue by njmhendrix** [comic/grand-challenge.org#1392]
**Describe the bug**
I am conducting a reader study with the "Allow answer modification" and "Allow case navigation" options enabled. When clicking the "next" button <img width="40" alt="next_button" src="https://user-images.githubusercontent.com/47858231/84161881-0aa70b00-aa70-11ea-9cc1-c2cdef94c27f.PNG"> after answering the required question, nothing happens. When clicking the same button again, an error is raised that states that the answer could not be stored (see screenshot). The answer disappears when going to a next case, but it reappears when relaunching the reader study, indicating that it was stored anyway.   

**To Reproduce**
1. Go to "Reader Studies".
2. Select any reader study.
3. Click on "Launch this Reader Study".
4. Answer the required question(s).
5. Click twice on the next button.

**Expected behavior**
I expect that the error will be raised, but that the answer will persist after relaunching the reader study. 

**Screenshots**
<img width="734" alt="save_failure" src="https://user-images.githubusercontent.com/47858231/84163981-535fc380-aa72-11ea-9078-7151e525d0db.PNG">

**Desktop**
 - OS: Windows 10
 - Browser: Chrome (version: 83.0.4103.61) and Firefox (version: 77.0.1) (64-bits)

**Comment by jmsmkn** [comment]
Again, this is an issue with CIRRUS, not grand challenge.

**Comment by njmhendrix** [comment]
I am sorry, I was not certain about this one. I have moved the issue to the CIRRUS repository.
