### ISSUE TITLE
Indicate that an image import is pending for an algorithm result

### ISSUE THREAD

**Issue by nlessmann** [comic/grand-challenge.org#1397]
If the image import queue is full, algorithm results can show up in the results list with the note "No output images were found" even if the algorithm produced an output image because the import is delayed. This changes once the result image has finally been imported, but until then the user has the impression that the algorithm failed. It would be nicer if the results page would indicate that the import of the results is not finished.

**Comment by jmsmkn** [comment]
Agreed - will be improved as part of #1354
