### ISSUE TITLE
legacy submission: ordered creator list

### ISSUE THREAD

**Issue by Borda** [comic/grand-challenge.org#1401]
**Is your feature request related to a problem? Please describe.**
I ti very time consuming to find a user to pair legacy submission, see e.g. https://anhir.grand-challenge.org/evaluation/submissions/create-legacy

**Describe the solution you'd like**
Just to have the list of creators alphabetically ordered

**Describe alternatives you've considered**
try to type the name and hope that more than two letters will be accepted the select box

**Comment by jmsmkn** [comment]
Closing as this is a duplicate of #748

**Comment by Borda** [comment]
ok, and is there any progress? it seems that the other is pending for more than a year and by the description, it shall be rather a simple switch of selection box...

**Comment by jmsmkn** [comment]
No, other issues have higher priority for my team, it is not so "simple". This is an open source project, if this is important to you then a PR would be welcome.

**Comment by jmsmkn** [comment]
Alternatively, we also have ways of funding development through our technology center, please contact support at grand-challenge.org and then you can fund the developers to implement this.
