### ISSUE TITLE
Migrate away from read the docs

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#1417]
The read the docs builds have been problematic for a while, the lack of support for c extensions means that we have to maintain a separate requirements list rather than using poetry, and now there is an error in #1416 that can be solved by a try ... except block on an import or mocking out openslide. I don't want to introduce that mess so I propose to move from read the docs to github pages, building the documentation ourselves in a github action and hosting it on github pages. We do not need the historical documentation that read the docs provides as this is a website that is being constantly updated.

**Comment by bramvanginneken** [comment]
Sounds good to me.
