### ISSUE TITLE
Reader study duplicated filenames overwrites in hanging list

### ISSUE THREAD

**Issue by xieweiyi** [comic/grand-challenge.org#1421]
**Describe the bug**
upload two cases with the exact same file name, it also has exact same key in hanging list, which causes reader study to be invalid.

**To Reproduce**
1. upload cases with the same file name.

**Expected behavior**
add automatically tailing on duplicated file names, say file_0.mhd and file_1.mhd, if both uploaded files are named as file.mhd

**Comment by jmsmkn** [comment]
I don't think that we want to add this feature. 

The image importer does not know where an imported image is going to be used - it could be in a reader study, archive, algorithm input or a challenge data set, etc. You can add images to reader studies at other times than import time, for example, from an archive. What would we do then? Renaming may have a bunch of side effects for users.

There is a workaround for this already - you can remove images from reader studies by clicking on the "View / Delete Cases" button - then rename the file and upload it again.
