### ISSUE TITLE
Educational reader study ROI

### ISSUE THREAD

**Issue by miriam-groeneveld** [comic/grand-challenge.org#1463]
Creators of reader studies would like to be able to define ROI's for the images, to limit the area that a reader needs to annotate.

After a reader study is created, the editor should have the option to go through the images and define one or more ROI's. These ROI's should then be displayed when a reader is going through the study. Only as a general hint, so the ROI can be editable and the reader can make annotations outside of the ROI.

Another option would be to have the editor upload a csv file with the ROI's defined for each image. The question then is if ROI's created in for example ASAP can be directly used for CirrusCore.

**Comment by jmsmkn** [comment]
How often do you think that this feature would be used? If it is a one-off, you could achieve this with an overlay.

**Comment by miriam-groeneveld** [comment]
It's a general function they would like to add, to train their students for various annotation tasks. So not a one-off

**Comment by jmsmkn** [comment]
I have created this for 2 studies in 1 year, this is manageable as a manual action for now, can revisit this if it gets used a lot.
