### ISSUE TITLE
Feature request: adding Pixel Spacing and Photometric Interpretation as optional DICOM/MHA headers

### ISSUE THREAD

**Issue by njmhendrix** [comic/grand-challenge.org#1464]
**Is your feature request related to a problem? Please describe.**
Some time ago, I created an issue for preserving the (Imager) Pixel Spacing attribute in a DICOM file (x-ray) uploaded to Grand Challenge (https://github.com/comic/grand-challenge.org/issues/1216). Pixel spacing is the distance between adjacent pixels in the patient, whereas imager pixel spacing is the distance between adjacent pixels on the sensor. I use the pixel spacing information to resize images that are put into my deep learning algorithm. After realizing that the pixel spacing could still be accessed in the output MHA file using the GetSpacing function from the SimpleITK Python library, I closed the issue. However, I found that in quite some cases the pixel spacing does not match the imager pixel spacing, and GetSpacing only returns the imager pixel spacing. Since the Pixel Spacing attribute accounts for corrections or calibrations, I prefer this attribute over the Imager Pixel Spacing attribute (if available).

Besides the Pixel Spacing attribute, I use the Photometric Interpretation attribute to modify pixel intensity values. If the photometric interpretation is MONOCHROME1 (minimum pixel value should be displayed as white), then the pixel intensities need to be inverted. I saw that this attribute is not in the list of additional DICOM headers that are preserved by Grand Challenge, so I assume that this attribute will be lost after uploading the DICOM file.  

**Describe the solution you'd like**
If possible, I would like that the Pixel Spacing attribute (tag: 0028,0030) and Photometric Interpretation attribute (tag: 0028,0004) are added as additional headers to the output MHA file.

**Describe alternatives you've considered**
I have considered using the Imager Pixel Spacing attribute only and instructing users to upload MONOCHROME2 DICOM files.

**Comment by jmsmkn** [comment]
Do you want to have a go at implementing this? See this PR for an example of how to add a tag: https://github.com/comic/grand-challenge.org/pull/1298

**Comment by jmsmkn** [comment]
The only thing to be careful of is the data type, see here for another example https://github.com/comic/grand-challenge.org/commit/25e25d8fb1a6696973a3231d0a16fc11b0d8ca04

**Comment by njmhendrix** [comment]
Hi James, thanks for your quick reply, sure! I am going to have a look at the examples and try to add the tags myself.

**Comment by bramvanginneken** [comment]
I think you should use this info when converting dicom to mha, good software will do this, and then there is no need to store this info in mha. There are many other dicom headers that you need to use to convert pixel value (Rescale, Intercept). These need to be applied during conversion from dicom to mha.

**Comment by jmsmkn** [comment]
The rescale slope and intercept are applied, we take the pixel spacing provided by PyDicom, if there are any issues with that then raise PRs against that library.
