### ISSUE TITLE
Keybindings store for workstations

### ISSUE THREAD

**Issue by pkcakeout** [comic/grand-challenge.org#1497]
**Is your feature request related to a problem? Please describe.**

We have a key bindings editor in cirrus, but no way of persisting modified keybindings. We need some sort of API end point to store this information

**Describe the solution you'd like**

We have two ideas to be considered:
- Store presets as part of workstation configurations
- Store workstation presets for users

Ultimately, I assume, that we want both, but we should pick one as a first solution. My preference would be to allow users to store custom keybinding presets, because we have a ready-to-be-used keybindings editor in cirrus that we can leverage without too much work.

Internally, cirrus uses three parameters to describe an action - an action is something that a shortcut can be bound to:
- action-name: A unique symbolic name for the action
- description: A user-readable string describing the action the keybinding triggers
- shortcuts: A list of strings describing the bound key combinations. Example: 
    - `["Ctrl+A", "B,A"]` would mean two shortcuts are assigned to an action. One shortcut is Ctrl+A, the other is a sequence of two key presses, namely "B" followed by an "A".

The available actions and keybindings differ per loaded application, however, I think we can consider action names to be unique because they are typically namespaced with the plugin name. So my suggestion would be to create a "keybindings" JSON field on users that CIRRUS can use to store alternative keybindings for workstations. The keybindings then could be edited right within CIRRUS and stored in grand-challenge. On loading, the keybindings list will be retrieved from grand-challenge and applied.

Because action names are generally shared across our applications, this would allow users to set personal shortcuts that apply to many workstations. I think this is a nice feature.

I do not know if the user is known to CIRRUS at this point however. Is the GRAND_CHALLENGE_AUTHORIZATION-key a per-user key?

**Describe alternatives you've considered**

Alternatively, an easier but less convenient solution might be to add another JSON structure to a workstation configuration. This will enable shortcut configuration on an algorithm or reader study level. This is little different from the feature I envisioned but it also allows some modifications of shortcuts. I think this is less nice, because keyboard shortcuts cannot be shared among CIRRUS applications, cannot be customized by a user, and therefore we cannot leverage the builtin keybindings editor in CIRRUS which was designed around the idea of shortcuts being assignable by _users_.

Maybe this is easier to implement however?

------------------

Another way would be to store the keybindings in a browser-local storage: https://www.w3schools.com/html/html5_webstorage.asp This would be by-far- the easiest way to persist keybindings, but this would only work on a browser+user basis. If a users moves to a different device or computer, keybindings will not transfer as well. This could be a nice feature in itself however. I am not super sure but I think that I would expect keybindings to carry over with my website profile.

**Additional context**

The CIRRUS side of this feature is ready to go for months now. This was repeatedly requested by Bram, so this might be worth picking up....

Also: I asked about a 1-2 day project in a different domain in chat. Maybe this would be a good candidate? After we decided _what_ the solution should be?

**Comment by jmsmkn** [comment]
I wouldn't use web storage for this, the advantage of that is that you can persist data locally and access it as a cache for when the client is offline, eg, reading your emails in Gmail whilst disconnected. Given CIRRUS is not usable when offline and accessing this data is cheap then we should use the database to store this.

IMO, adding another JSON field to the workstation configuration, adding this to the serializer is the easiest way forward and takes a couple of minutes. We can add validation if needed, and then split this into fields for easier configuration when we have more of a sense of how it will work. Having user based configurations for workstations is on the roadmap, but we need to think more about how the configuration cascade will work for each combination of image, archive, algorithm result, workstation, and user. It's something that should be done separately to this issue.

Let me know what field(s) you need.

**Comment by pkcakeout** [comment]
Alright, then let's go for the workstation configuration solution. I still think that user-configurations might be a bit more user friendly but I think we can get something nice out of this as well.

# What is needed

The most user-friendly suggestion I have would be to just add another JSON field. Instead of being handwritten, I could create an "export" button on the keybindings manager that automatically serializes the current keybindings to JSON. I think this is quite neat because this could be used as a basis for a simple import/export feature for keybindings that I can leverage in CIRRUS Oncology as well.

The JSON structure would have the following format:

~~~~~~~~~~
{
    "action-name": ["keybinding", ....],
    ....
}

action-name: An arbitrary string - the unique identifier to be used in CIRRUS to identify the action.
keybinding: A keybinding string

Note: A keybindings list assigned to an "action-name" can be empty to unbind a default keybinding!
~~~~~~~~~~

## Maybe keybinding string verification

Verifying the keybindings string could be done as well. I have JavaScript and Python code for this. Here the python code: https://github.com/DIAGNijmegen/rse-cirrus-core/blob/9fb5f02783e81ef9fb6e1ee0693de9fadd1e78aa/src/cirrus/DIAG/CIRRUSCore/Modules/Scripts/python/cirrus/keybindings.py#L95 This is custom written, because somehow nobody bothered to create a Keybinding-string normalizer that creates keybinding strings that are compatible with Qt5 and JavaScript. 

That said, we do not _need_ to do this, because this is done anyway when keybindings are imported in CIRRUS. However, I could image someone hacking these by hand so it might be handy to have verification here. Maybe, we can also write a REGEX for verification... I did not try that yet.

## No action-name verification

Getting proper verification for "action-names" is a bit tricky, because the list of supported actions is dynamically compiled out of an enumeration after a workstation launches. I think, the best I could do would be to extract them once during build and expose them as a container-label. However, I think this is way too cumbersome. I think we should just allow for arbitrary action names to work. CIRRUS can decide whether they match up with any given internal action or not. This allows us to include a single set of generic keybindings even for specialized workstations that might define extra actions or workstations that do not implement certain actions.

**Comment by pkcakeout** [comment]
> I wouldn't use web storage for this, the advantage of that is that you can persist data locally and access it as a cache for when the client is offline, eg, reading your emails in Gmail whilst disconnected.

Btw. I totally agree. This would be an easy fix though if we do not want to modify grand-challenge or want to wait until we support the user-settings feature on grand-challenge.

**Comment by bramvanginneken** [comment]
At this stage, I would not delay implementation and not make it all nice for the users with nice UI and verification etc. Just let us upload a set of settings in some format. Then you get user feedback, also on what kind of actions we should be able to link to keys.

**Comment by pkcakeout** [comment]
I implemented part of this feature in the linked issue (see above). I will implement loading of keybindings when this has been added to grand-challenge.
