### ISSUE TITLE
Pictures for messages on social media

### ISSUE THREAD

**Issue by bramvanginneken** [comic/grand-challenge.org#1498]
Challenges, algorithms, Reader studies and archive have a logo that is used in the cards. Would be great if when you'd post a link for these things on social media (eg linkedinb) this logo image is shown. For challenges the banner image is now shown but that image has a Recommended resolution 2200x440 px, and is too wide to fit nicely. For algorithms the default gc image is shown, whioch does not fit at all. For algorithms it would also be nice if the logo is shown on the page itself, on top.

**Comment by bramvanginneken** [comment]
Github has this as well: 
![image](https://user-images.githubusercontent.com/1818749/91708309-708fc400-eb81-11ea-8a61-dc79edca3fb3.png)
Note they recommend a higher resolution than what we recommend for logos (Should be square with a resolution of 640x640 px or higher.) I think we should ask for a higher resolution logo as well as challenges etc run for years and screens get higher and higher resolutions.

**Comment by jmsmkn** [comment]
What needs to be done:

- Add fields to all models that require this, migrate data, handle cases where these are not set
- Research what metadata tags are needed for each social media company we want to support
- Update this template https://github.com/comic/grand-challenge.org/blob/master/app/grandchallenge/core/templates/grandchallenge/partials/meta.html
- Migrate old images on S3 to correctly set the mimetype (currently octect stream) for old and new images

**Comment by bramvanginneken** [comment]
Wouter Bulten may know for the second point, I think he figured that out for the DIAG websites.
