### ISSUE TITLE
Selecting view all results causes negative index for pagination

### ISSUE THREAD

**Issue by bramvanginneken** [comic/grand-challenge.org#1506]
![image](https://user-images.githubusercontent.com/1818749/92088381-12572100-edcd-11ea-92b4-f502e09520e7.png)

**Comment by jmsmkn** [comment]
Thanks - I've not been able to work out what causes that error. Sentry details: https://sentry.io/organizations/grand-challenge/issues/1852890399/?project=303639&query=is%3Aunresolved
