### ISSUE TITLE
Leaderboard is not populated, gives error: "DataTables warning: table id=resultsTable - Cannot reinitialise DataTable...."

### ISSUE THREAD

**Issue by prash-p** [comic/grand-challenge.org#1510]
**Describe the bug**
I have a private challenge for which there are submissions that were previously shown on the leaderboard. Now when I visit the leaderboard, it is completely empty, and sometimes when I refresh the page in incognito mode I get the error:

> DataTables warning: table id=resultsTable - Cannot reinitialise DataTable

I haven't changed anything in the challenge for a few months so not sure why the leaderboard stopped working. I have other identical private challenges for which the leaderboard works as expected.

I can confirm that in the "Evaluation" page that is accessed from the Admin drop down menu, there are some methods that are set to be published to the leaderboard (see screenshot below)

**Expected behavior**
A working leaderboard

**Screenshots**
![tempsnip](https://user-images.githubusercontent.com/5707552/92124612-fd2dc280-edcb-11ea-9ac9-19e7023f2f23.png)

**Comment by jmsmkn** [comment]
You have spaces in the keys of your metrics.json for the elements "aggregates.Failure Rate" and "aggregates.Inadequacy Detection Rate", those cannot be used as valid jsonpaths. If you remove those from the extra results columns settings it will work again.

**Comment by prash-p** [comment]
But in my other challenges I use the same column settings without any issues, e.g. in https://sub-eval-1-ubc-us-bone-seg.grand-challenge.org/ the leaderboard works fine and has the same extra columns

**Comment by jmsmkn** [comment]
Ok, then it is because the values for "aggregates.Inadequacy Detection Rate" are `null`, so just remove that column.
