### ISSUE TITLE
Add a challenge checklist

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#1541]
Setting up a challenge is quite involved now, it would be good to have an active checklist for ensuring that the automated evaluation is correctly set up for a particular phase. Things to check:

- The method container is present and active
- If algorithm submission: that the archive is there and has cases, show how many cases would be there

For the participants:

- Add some more validation on the form to ensure that everything is ready

**Comment by bramvanginneken** [comment]
One mechanism that appeals to me is that when somebody submits an algorithm to be used in a challenge, they also submit the output of that algorithm on a few public test cases. The system can then check if running the algorithm on the same test cases produces the same results. We could use the terminology public and private test set, and also allow users to view the results of all algorithms on the public test data.

**Comment by jmsmkn** [comment]
> One mechanism that appeals to me is that when somebody submits an algorithm to be used in a challenge, they also submit the output of that algorithm on a few public test cases. The system can then check if running the algorithm on the same test cases produces the same results. We could use the terminology public and private test set, and also allow users to view the results of all algorithms on the public test data.

Agreed, maybe another feature request. As participants need to make an algorithm anyway (and can upload their data to that directly to check its working) maybe they can select a public archive to run their algorithm on before submission.

**Comment by jmsmkn** [comment]
Anne has added all of this to the submission page and phase update validation.
