### ISSUE TITLE
Show times in users local time, rather than UTC

### ISSUE THREAD

**Issue by pkcakeout** [comic/grand-challenge.org#1545]
**Describe the bug**
From the RTC Workshop Demo, Bram reported:

![grafik](https://user-images.githubusercontent.com/11632379/94120044-f4229500-fe4f-11ea-824a-134e1c3e8bbf.png)

It reports the time in UTC (it was 10:40 CEST when he received the machine). I am not sure if this is actually correct, but I would expect that it the UTC time stamps are rendered to the local user timezone setting before showing it to the user. I find it unlikely that Bram uses GMT or UTC on his machine, but maybe in his account settings?

**To Reproduce**

Generate the join-challenge-rejected-message. 

**Expected behavior**
Us local time instead of UTC.

**Desktop (please complete the following information):**
Don't know, I am reporting this on behalf of Bram. Likely does not matter.

**Comment by jmsmkn** [comment]
This is correct, we would need to add this: https://docs.djangoproject.com/en/3.1/topics/i18n/timezones/#selecting-the-current-time-zone

Probably as an option on the users profile rather than the session, update all the templates to use `tz`, and pass the users timezone to all emails that use times.

**Comment by jmsmkn** [comment]
BTW, we use UTC everywhere, so I think that this is a feature request.

**Comment by pkcakeout** [comment]
> Probably as an option on the users profile rather than the session

This is an interesting question. I personally was thinking about that a lot in the past. I think browser settings/parameters are the correct place to get these from, because if someone picks up their laptop and travels to the RSNA, for example, it is likely that they update their local clock. Not their profile on the the website they are using.

Unfortunately, that information does not seem to be sent through with the HTTP request header. So instead, one would need to use geo-ip tagging or something to guess the time zone(?) Or the JavaScript post processing way - that seems to be the most popular way doing a quick googling. That works by sending the UTC time and then using JavaScript to translate the received UTC time into local time. We use that on the SOL-cluster dashboard as well. Though this was a hack, seems to be the only true way to do this :-(

**Comment by pkcakeout** [comment]
That said: Profile settings might be a good proxy though! If it is easier, that is likely the way forward afterall!

**Comment by jmsmkn** [comment]
Is cross timezone travel something we have to worry about in COVID times? ;-) 

The easiest is definitely a profile field (recommended in the Django docs too) and using UTC for anonymous users. Auto setting can be a feature request that depends on a vaccine/herd immunity.

**Comment by jmsmkn** [comment]
> > Probably as an option on the users profile rather than the session
> 
> This is an interesting question. I personally was thinking about that a lot in the past. I think browser settings/parameters are the correct place to get these from, because if someone picks up their laptop and travels to the RSNA, for example, it is likely that they update their local clock. Not their profile on the the website they are using.
> 
> Unfortunately, that information does not seem to be sent through with the HTTP request header. So instead, one would need to use geo-ip tagging or something to guess the time zone(?) Or the JavaScript post processing way - that seems to be the most popular way doing a quick googling. That works by sending the UTC time and then using JavaScript to translate the received UTC time into local time. We use that on the SOL-cluster dashboard as well. Though this was a hack, seems to be the only true way to do this :-(

Apparently the way to do this is `Intl.DateTimeFormat().resolvedOptions().timeZone`.
