### ISSUE TITLE
Make reader studies visible without login

### ISSUE THREAD

**Issue by Kicksta** [comic/grand-challenge.org#1546]
Currently when signed out, when you click on a public reader study you have to login right away  before seeing any info about it. For algorithms this is not the case, you can read basic information while logged-out. Feature request from Bram and me as we would like to use the initial reader study page as an information page about our upcoming study to gather data from other hospitals. 

Would like the same flow as for the algorithms, where without an account, basic info for the reader studies is visible.

**Comment by jmsmkn** [comment]
Actually, this is quite a bit more work. For algorithms we created the `execute_algorithm` permission for using the algorithm, and use the `view_algorithm` permission for viewing the main detail page. For reader studies, we use the `view_readerstudy` permission for reading the study. So, we need to create a new permission and migrate this.

**Comment by bramvanginneken** [comment]
I think it is worth to use the same mechanism as much as possible for Archives, Challenges, Reader Studies, Algorithms, etc. But as a workaround we can ask radiologists who we ask to participate in Reader Studies to make an account first...

**Comment by jmsmkn** [comment]
> I think it is worth to use the same mechanism as much as possible for Archives, Challenges, Reader Studies, Algorithms, etc. But as a workaround we can ask radiologists who we ask to participate in Reader Studies to make an account first...

Agreed, in fact, both models were implemented in the same way before this feature was added to algorithms in February (https://github.com/comic/grand-challenge.org/pull/1163). Adding something like this everywhere would have increased the development time for the feature for algorithms, which we were under heavy pressure to implement. Given there was no explicit request for that functionality in reader studies then, it was not done, now there is, so we need to pay back that technical debt.
