### ISSUE TITLE
Algorithm results list AJAX view is slow

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#1559]
Following #1553 generating a page of results is slow, 5s for 100 results. Likely an n+1 queries resulting from `interface = ComponentInterface.objects.get(slug="results-json-file")`. Might need a similar solution as in #1477. My guess is that we need to run with the HistoryPanel of Django Debug Toolbar.

**Comment by jmsmkn** [comment]
The n+1 queries have been reduced but this is still slow, almost 40ms per row with a template.

**Comment by bramvanginneken** [comment]
Yes I notice this also as a user of grand-challenge.org
