### ISSUE TITLE
When doing user verification for a gmail user, error when using work email, because that email is already in use

### ISSUE THREAD

**Issue by bramvanginneken** [comic/grand-challenge.org#1561]
![image](https://user-images.githubusercontent.com/1818749/95426501-49799e80-0946-11eb-8415-9906d6b947dc.png)

I guess a solution would be to delete the account associated with my work email. But there is no way to do that. Maybe the solution is to let users delete their account.

A better message regarding this would be good.

**Comment by jmsmkn** [comment]
That's correct. As detailed in the ToS users can request deletion by emailing support, we will not expose a user-facing form to do that. In situations like this, I think that users would be aware to either email support or make an issue. I have removed your second account.
