### ISSUE TITLE
Images converted to tiff can get wrong image spacing.

### ISSUE THREAD

**Issue by miriam-groeneveld** [comic/grand-challenge.org#1564]
Images that are converted to tif files can get incorrect image spacing during conversion. Problem was found with certain svs files, where openslide found certain mpp propreties (micron per pixel) but these were not used to set the tiff tags ResolutionX and ResolutionY, resulting in these properties having a value of 1.

When used in algorithms that expect a certain image spacing, these images are then rejected.

**Comment by miriam-groeneveld** [comment]
Seems to be a problem of the libvips version we are using. We need 8.10, currently we are using 8.7

**Comment by jmsmkn** [comment]
We use the Docker python image, version 3.8: https://github.com/comic/grand-challenge.org/blob/master/dockerfiles/web-base/Dockerfile#L6 https://github.com/comic/grand-challenge.org/blob/master/Makefile#L3 

Currently, this uses Debian buster https://hub.docker.com/_/python which is the latest version. 

You can install it from unstable, or we could wait for it to be accepted into stable https://tracker.debian.org/pkg/vips

**Comment by miriam-groeneveld** [comment]
I think we can wait for the stable version, there's a work-around using ASAP to do the conversion. I'll check with the student

**Comment by jmsmkn** [comment]
It's up to you - this likely will not be done until mid 2021. If there is a work around I would say to wait and close this as it will automatically get fixed when it's available and we rebuild the base container.

**Comment by miriam-groeneveld** [comment]
I think we need to fix it now, people outside of Radboud are uploading these images as well and of course do not know about the work-around.

**Comment by jmsmkn** [comment]
Ok - not sure that to do then, on a pretty clean ubuntu box it drags in 254 dependencies. We would need to see what would change, I will try this afternoon.

**Comment by jmsmkn** [comment]
It's not possible to install this from testing without upgrading pretty much everything, and it is not available in backports. We could compile it ourselves. Can we add a workaround in Python?

**Comment by miriam-groeneveld** [comment]
We can fix it very simply by calculating resolution from openslide properties. That's just some code we can remove again when we've updated to 8.10. I'll create a PR.
