### ISSUE TITLE
Reorganize challenge overview page by showing external challenges after challenges hosted in grand-challenge 

### ISSUE THREAD

**Issue by ecemlago** [comic/grand-challenge.org#1571]
Hi,

Bram thought that we could show challenges hosted in GC before external challenges in order to encourage users to host their challenges in GC. As far as I know, right now, the order of challenges on the overview page is based on their date. We could still use the date, but reorder the challenges organized in the same year according to their host website.

@jmsmkn, what do you think about this?

**Comment by jmsmkn** [comment]
This is already the case - we show 40 challenges per page, the first 20 are on grand challenge:

![image](https://user-images.githubusercontent.com/12661555/96243074-85df7700-0fa4-11eb-9538-2a9edb19ba65.png)

and the 20 after that are external:

![image](https://user-images.githubusercontent.com/12661555/96243112-942d9300-0fa4-11eb-8ce1-5cede25e0c77.png)

See the hosted by link. PANDA is there as Wouter wanted some editable pages, but really it should be an external challenge until kaggle is done. Within those groups the challenges are ordered by date.

I'm going to close this issue as invalid but feel free to comment or reopen if you would like something different.
