### ISSUE TITLE
add transparency to Jet colormap (overlay lut in workstation viewer configuration)

### ISSUE THREAD

**Issue by njmhendrix** [comic/grand-challenge.org#1586]
**Is your feature request related to a problem? Please describe.**
My [scaphoid fracture detection algorithm](https://grand-challenge.org/algorithms/scaphoid-fracture-detection/) produces a bounding box surrounding the scaphoid bone and generates a saliency map for fracture localization. I use the Jet colormap for the overlay lut of the saliency map, so that the saliency map is displayed with a heat map colour coding. The current saliency map covers the entire input image, but I would like to restrict the saliency map to the bounding box region for better visibility of the surrounding regions. This means that the image region outside the bounding box must become transparent. 

**Describe the solution you'd like**
If possible, I would like that the Jet colormap is modified in such a way that overlay pixels with the value -1 become transparent. If the saliency map must be an 8-bit image (256 pixel values), then the value 0 could be selected instead.

**Comment by jmsmkn** [comment]
I think that I have made this change, please check.

**Comment by njmhendrix** [comment]
Thanks! I will update my algorithm and check if it works.
