### ISSUE TITLE
Add filtering to the Challenge List view

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#1591]
Filtering on Modality, Host, etc was removed when we had to implement serverside pagination, add this back.

**Comment by bramvanginneken** [comment]
Could we implement the same filtering options, at least at a low level, and with customizable visibilities/layouts for the UI, for all pages, i.e. Archives, Reader Studies, Challenges, Algorithms, Products?

**Comment by jmsmkn** [comment]
Yes, that is already the case, this issue is for activating it for challenges.
