### ISSUE TITLE
Docker container management for algorithms

### ISSUE THREAD

**Issue by njmhendrix** [comic/grand-challenge.org#1601]
Over time I have uploaded 30 docker containers to Grand Challenge for updating my algorithm, and I think it would be nice if users can (1) delete redundant containers (e.g. containing fatal bugs) and (2) select which container to use. This way, I could maintain a manageable list of (stable) algorithm versions to choose from and easily roll back when necessary.

**Comment by jmsmkn** [comment]
Implementation: 
- new foreign key on an algorithm to the active image 
- add this field to the algorithm update form, filter by ready images and algorithm
  - ensure that there is enough information in the drop-down for the editor to select the correct image
- when a new image is uploaded, set the active image after successful validation (celery canvas)
- remove direct usage of `latest_ready_image` from API and template views

**Comment by jmsmkn** [comment]
Thank you for the suggestion. I am gathering all of the feature requests elsewhere, and will consider this for inclusion a future development cycle.
