### ISSUE TITLE
Ordering of algorithm outputs

### ISSUE THREAD

**Issue by AjayPatel86** [comic/grand-challenge.org#1627]
Some algorithms produce multiple output files, such as overlays and intermediate images. We have noticed that the order in which they are created by the algorithm doesn't necessarily correspond to the order of outputs on GC. 

Would it be possible to order the outputs by time of creation by the algorithm?

**Comment by jmsmkn** [comment]
No - we use django many to many relationships to link algorithm outputs to algorithm jobs, these are not orderable. The image REST API tells you the name of the file that the heatmap originated from, use it, eg:

https://grand-challenge.org/api/v1/algorithms/jobs/8dd0bdfe-97b1-47a2-9fa9-22c6c525dd68/

returns:

```
{
  "pk": "8dd0bdfe-97b1-47a2-9fa9-22c6c525dd68",
  ...
  "outputs": [
    {
      "interface": {
        "title": "Generic Overlay",
        "description": "",
        "slug": "generic-overlay",
        "kind": "Heat Map",
        "pk": 2
      },
      "value": null,
      "file": null,
      "image": "https://grand-challenge.org/api/v1/cases/images/30c00629-6dbe-41cb-b55c-83920dca7dbb/",
      "pk": 74403
    },
    {
      "interface": {
        "title": "Generic Overlay",
        "description": "",
        "slug": "generic-overlay",
        "kind": "Heat Map",
        "pk": 2
      },
      "value": null,
      "file": null,
      "image": "https://grand-challenge.org/api/v1/cases/images/f49b9efd-1eb1-40f4-83d0-ca33a3c59823/",
      "pk": 74404
    },
    {
      "interface": {
        "title": "Results JSON File",
        "description": "",
        "slug": "results-json-file",
        "kind": "JSON file",
        "pk": 3
      },
      "value": [
        {
          "inputs": [
            "file:/home/user/temp-input/8c86d962-63f3-4442-918d-59159adc1eaf.mhd"
          ],
          "outputs": [
            "file:/output/images/wta.mhd",
            "file:/output/images/colormapping.mhd"
          ],
          "error_messages": []
        }
      ],
      "file": null,
      "image": null,
      "pk": 74405
    }
  ],
  "status": "Succeeded",
  ...
}
```

You can see that two overlays are generated and the information about the files is available at 

https://grand-challenge.org/api/v1/cases/images/30c00629-6dbe-41cb-b55c-83920dca7dbb/ and https://grand-challenge.org/api/v1/cases/images/f49b9efd-1eb1-40f4-83d0-ca33a3c59823/

Querying those URLs gives you the original filename:

```
{
  "pk": "30c00629-6dbe-41cb-b55c-83920dca7dbb",
  "name": "wta.mhd",
  ...
}
```

**Comment by SilvanQuax** [comment]
In the definition of start_algorithm_job_logic in viewing.py I can change the order of the overlays. But I don't know how to access the "name" key of the image files there. There are image handles and handle maps created, but not sure what code to use to access the image keys. Could someone show how to do this with a line of code?

**Comment by jmsmkn** [comment]
No idea if this is it but a quick glance at the code:
```
output_images = self._interface_values(slug="generic-overlay", assigned_to="outputs")
output_image_metadata = [self.app.grand_challenge_client(out["image"]) for out in output_images]
original_names = [o["name"] for o in output_image_metadata]
```

**Comment by SilvanQuax** [comment]
Thanks! but self.app.grand_challenge_client(out["image"]) seems to give an error:

`2020-12-02 10:05:29 ScriptError:  connection.py(196) ValueError: Method cannot contain non-token characters 'HTTPS://GRAND-CHALLENGE.ORG/API/V1/CASES/IMAGES/30C00629-6DBE-41CB-B55C-83920DCA7DBB/' (found at least ':')`

**Comment by jmsmkn** [comment]
Ok, here is how you can debug an error message like this.

It is a `ValueError`. Let's go to the python docs to work out what that is

> Raised when an operation or function receives an argument that has the right type but an inappropriate value
https://docs.python.org/3/library/exceptions.html#ValueError

Ok, so we know that the value is of the correct type, but the wrong value. The message is `Method cannot contain non-token characters 'HTTPS://GRAND-CHALLENGE.ORG/API/V1/CASES/IMAGES/30C00629-6DBE-41CB-B55C-83920DCA7DBB/'`. 

So, this tells you that the variable has something to do with `Method`, and that the value is probably a string with the value `'HTTPS://GRAND-CHALLENGE.ORG/API/V1/CASES/IMAGES/30C00629-6DBE-41CB-B55C-83920DCA7DBB/'`. 

Ok, so what went wrong? Take a look at the traceback, and you can see that the call to `self.app.grand_challenge_client` with 1 argument caused the problem, and that 1 argument is the suspect string. 

Well, what is `self.app.grand_challenge_client`? Use your IDE to find out, get it set up correctly and you can right click on the name of the function and click "Go to declaration". Or, attach a debugger and interact with it, find this piece of code where it is defined. Print the class. Whatever. Find a way to get at this information as you need to be able to do this by yourself.

You will end up at this piece of code: https://github.com/DIAGNijmegen/rse-gcapi/blob/master/gcapi/gcapi.py#L495

Where you can see the function signature:

```
    def __call__(
        self,
        method="GET",
        url="",
        path="",
        params=None,
        json=None,
        extra_headers=None,
        files=None,
        data=None,
    ):
```

So - the first argument to this method is `method` with a default value of `"GET"`. Ah, that's a problem as we're sending a url there, so we need to set `url` instead. Ok, lets do that with a kwarg:

```
self.app.grand_challenge_client(url=out["image"])
```

Please spend a little time working out how to solve these problems by yourself. If you do not know how to, please follow a course, there are some good guides out there, this is one https://realpython.com/python-debugging-pdb/ and I would recommend a lot of the other content on realpython.com.

**Comment by SilvanQuax** [comment]
Thanks that worked! I'll read up on HTTP since I had no idea what this GET method was and whether it was intended to be a url link.
