### ISSUE TITLE
Add support for Image answer types in Reader Studies

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#1628]
Some annotations are too large to be serialised to JSON and set directly on the answer, and the users are converting the cso's to masks anyway, so it would be better if we can store these directly. In the future, it would open up storing of secondary images, etc, that SATORI was hacking around by sending them to an archive.

Discussed the approach with @MikeOverkamp-diag today:

- We will implement this only for the Polygon annotations right now, and add splitting this back up later to #1357
- A new answer type needs to be added. The answer should store the following JSON as the answer: `{"upload_session_pk": <string, a UUID>}`
- A nullable foreign key to `Image` should be added. We need to validate that this is only going to be set for the correct new answer type.
  - Add this to the object history
  - Ensure the view permissions for the image are set correctly, these should match the groups for the answer view permissions
- The client will more or less need to implement this: https://github.com/DIAGNijmegen/rse-gcapi/blob/master/gcapi/gcapi.py#L593-L611
  - Stretch goal: upload the images asynchronously
- Once the answer has been created, the client will be able to call `self.raw_image_upload_sessions.process_images` with `json={"answer": <the answer pk>}`
- James will squash the migrations and can handle the API updates via Celery linked tasks once the models are in place

**Comment by michelkok** [comment]
Outputting masks directly sounds like a great solution for me.

I assume that if a reader wants to answer in two session the mask is stored in between, loaded into the Reader Study and can then be updated with the CSO tools. As such, you are implementing a mapping between CSOList and masks, is that right? 
If that is correct, is it easy to extend this functionality a bit to allow us to upload partial masks even before a reader has started? It would solve [this cirrus ticket](https://github.com/DIAGNijmegen/rse-cirrus-core/issues/887) immediately.

**Comment by jmsmkn** [comment]
Glad you mentioned this - this means that we would need to add the Image to the history as those are immutable. What we'd implement here would allow the workflow mentioned in the ticket, but the conversion from image to CSO would still need to be added on the CIRRUS side. 

@MikeOverkamp-diag you should integrate @michelkok's tools for converting from CSO to mask into CIRRUS Core.

**Comment by MikeOverkamp-diag** [comment]
Just to be clear: are we talking about this bit of code: https://github.com/DIAGNijmegen/msk-mevislab-modules/pull/1/files

**Comment by michelkok** [comment]
I am slightly confused now as well. So, we need a mapping between CSO and masks.

1. CSO -> Mask
This is the PR that @MikeOverkamp-diag references. You could maybe use it internally to make this direction of the mapping. I just use this to convert annotations that are currently returned from the Reader Studies to masks.

2. Mask -> CSO
This is the issue I reference above. I have not yet worked on this, I am planning to do this in the coming weeks.

**Comment by jmsmkn** [comment]
This issue (#1628) is about point 1 - the user will make a CSO, but CIRRUS will convert it and store a binary mask on grand challenge. The original CSO will be discarded.

The issue on CIRRUS (https://github.com/DIAGNijmegen/rse-cirrus-core/issues/887) is orthogonal to this, but for that you will need a mask -> cso function. However, implementing (#1628) will make one of the workflows described in https://github.com/DIAGNijmegen/rse-cirrus-core/issues/887 easier to implement.

**Comment by pkcakeout** [comment]
We need to figure out issue https://github.com/DIAGNijmegen/rse-cirrus-core/issues/908 before integrating anything like this because if this is a "deep issue" the mask creation is ambiguous. CSOs are buggy already, but masks will be unfixable after the fact.

Also the conversion Mask -> CSO is ambiguous. It is very likely that multiple repeated conversion of Mask -> CSO -> Mask -> CSO -> Mask will result in different results. However, right now we rely on these representations to not change. This is important for the "modifiable answers feature". The assumption here is "what is cached in CIRRUS == what would come out of grand-challenge". This needs to be accounted for and this is not trivial.

**Comment by pkcakeout** [comment]
Mmh... reading through the ticket one more time, I think this just means that we should maybe not tackle the CSO<->Image issue as part of this issue. It really complicates things. I think it would be easier to provide a "brush tool" to just paint overlays directly onto an image. That is super trivial and a direct 1:1 representation between CIRRUS and grand-challenge. - My proposal.

**Comment by jmsmkn** [comment]
Maybe speak to Alex about this as this was also a request from FME, so, they should know already how to handle that in MeVisLab. This issue only concerns CSO -> Mask, please keep this issue on topic and discuss Masks -> CSOs in the other issue.

**Comment by bramvanginneken** [comment]
The tools from Jan moltz provide a brush tool. Making that is not easy at all. That’s why years of work was put into it.

**Comment by jmsmkn** [comment]
Closed with #1657
