### ISSUE TITLE
Visualize algorithm results as annotations.

### ISSUE THREAD

**Issue by miriam-groeneveld** [comic/grand-challenge.org#1638]
There is a request for the option to show algorithm output as annotations in CirrusCoreWeb. For example the mitosis algorithm will output a point for each mitosis that has been detected. 

This data can be quite large, the proposal is to add it in the file parameter of the result.json ComponentInterfaceValue. This allows for separation of the result that should be shown in the front-end, and the data that should be used in the back-end as annotations.

The data should be validated to ensure the back-end can deserialize the json to cso's. We'll need some extra schema's for that, as currently cso's are only used in reader study schema's.

**Comment by miriam-groeneveld** [comment]
We probably need a way to group and label (groups of) annotations as well (can be done via the schema)

**Comment by jmsmkn** [comment]
Much of the work for this is already in place - you can add a `file` to the `ComponentInterfaceValue` from the algorithm output (https://github.com/comic/grand-challenge.org/blob/master/app/grandchallenge/components/models.py#L130). We shouldn't inspect the `results.json` but rather dictate where files should be put, this way we can ensure that they're unique and can more easily reuse them in pipelines.

What would need to happen is:
- Add file validation to `ComponentInterfaces`
- Update the algorithms to load data from the set `ComponentInterfaces`: at the moment it just follows the defaults of result json and many images
- Add CIV file serving with permissions
- Create a new `ComponentInterface`, set to file, set a path, set a validator

**Comment by miriam-groeneveld** [comment]
What about using the predictions-json-file ComponentInterface? Isn't that what the result of the mitosis algorithm is?

**Comment by jmsmkn** [comment]
The idea is that these interfaces should be specific. The ones we have already are general, we don't really know what is the content, and we need that in order to re-use them. The `predictions-json-file` are for a set of general predictions for a challenge evaluation, not what we want here. We want a new interface for `mitosis-locations` (say). We should use json as this is supported natively and there is a standard for validation that can easily be expressed and used (json schema).

**Comment by miriam-groeneveld** [comment]
Ok, so a new CI specifically for the mitosis algorithm. So the mitosis algorithm actually has several outcomes, a point for every mitosis, but also hotspot areas. Should we then define the schema accordingly? It would mean that if the algorithm changes, we would need to update that schema as well. Or should there be several json files?

**Comment by jmsmkn** [comment]
Algorithm editors should be able to define their own interfaces, so it's up to them, how they see the values being passed around, visualised and viewed later. It would be good if the schemas could follow something that CIRRUS knows how to visualise (a bunch of points, a bunch of bounding boxes, etc).

**Comment by miriam-groeneveld** [comment]
I think we need some tickets for this feature:

- [x] Update the algorithms to load data from the set ComponentInterfaces: at the moment it just follows the defaults of result json and many images: done in #1662 
- [ ] Save json output as files in stead of raw json in db(?)
- [ ] Add CIV file serving with permissions
- [ ] Add file validation to ComponentInterfaces
- [ ] Create a new ComponentInterface, set to file, set a path, set a validator

**Comment by jmsmkn** [comment]
Has everything on the backend been done for this?

**Comment by miriam-groeneveld** [comment]
Yes!
