### ISSUE TITLE
Show how many Algorithms are found, just like for Challenges

### ISSUE THREAD

**Issue by bramvanginneken** [comic/grand-challenge.org#1659]
![image](https://user-images.githubusercontent.com/1818749/102520857-7360e700-4094-11eb-81dc-549e86756aa2.png)

Below the filter option it is shown how many Challenges are found, this is not the case for Algorithms, but would be nice there too.

**Comment by GeorgeJoLo** [comment]
Hello! I'm very new in github (meaning this is my first repository visiting). I want to contribute to something. I think I can handle this one. What should I do? 
Is it still open right?

**Comment by jmsmkn** [comment]
Hi @GeorgeJoLo! Great that your interested in contributing to open source, and this project in particular. You don't seem to have any activity in your GitHub yet so I'm unsure how much guidance you would need. This is a web app built on Django, do you have any experience with Django, or web development? If not, I would start with the Django tutorial (https://www.djangoproject.com/start/ and/or https://learndjango.com/tutorials/how-learn-django) and build a couple of apps for yourself first. Once you're familiar with Django, then follow the developer documentation for this project to get up and running (https://comic.github.io/grand-challenge.org/development.html).

**Comment by jmsmkn** [comment]
Closed by #1681
