### ISSUE TITLE
Product search button is out of screen

### ISSUE THREAD

**Issue by GeorgeJoLo** [comic/grand-challenge.org#1666]
Notice that I have some knowledge in Human-Computer Interaction and I know how to find usability issues.

When the user tries to make a search in products at the 'Products' page, using his smartphone, he cannot see search textbox and button on his screen, because they are at the right.
![IMG_20210104_113150.jpg](https://user-images.githubusercontent.com/48959849/103521857-247fc380-4e82-11eb-9f90-1b4774eeec6b.jpg)
I assume this is because of the page's header width.
![IMG_20210104_114614.jpg](https://user-images.githubusercontent.com/48959849/103522047-79233e80-4e82-11eb-9dae-b3fa58133d13.jpg)
In order to find the search button, he needs to zoom out or scroll right.
I think this is a very important usability issue because this page is the main income source and you want to make customer's life easy.

1. Go to https://grand-challenge.org/
2. Click on menu
3. Select 'Products'
4. Look at search bar to see the error

The search button and textbox should be places inside the screen. So you need either to wide the screen or to place this components under the other fields.
![IMG_20210104_115517.jpg](https://user-images.githubusercontent.com/48959849/103522929-bdfba500-4e83-11eb-89c3-db3fe5aafe50.jpg)

**Smartphone**
 - Device: Xiaomi Redmi Note 8 pro
 - OS: MIUI Global 11.0.2
 - Browser: Chrome
 - Version 77.0.3865.92

**Comment by Kicksta** [comment]
Thanks for notifying and your suggestions! Will fix it.

**Comment by jmsmkn** [comment]
Still an issue but this has been open for a year, given the low mobile traffic to the site it's not very important.
