### ISSUE TITLE
Create vendor signup / login

### ISSUE THREAD

**Issue by MikeOverkamp-diag** [comic/grand-challenge.org#1671]
Currently, the products displayed on he products page can only be updated via an excel import. This means that for each change to any of the products the entire import needs to be run. In order to make things more user friendly, vendors should be able to update and add products themselves. To be able to do so, a login system for vendors should be added to the `products` app.

We can use the existing user and user profile models for this, but we need to add an extra `vendor` user group to which any user signed up as a vendor gets added automatically. We should also introduce a `products-admin` group. Users in this group will be able to approve new users as vendors and any changes made to products.

**Comment by jmsmkn** [comment]
Just to check my understanding, I think we have a very similar pattern in `Algorithm` and `AlgorithmImage`:

- Superusers can create new vendors using the django admin
- For each new vendor, there is a new `editors` group who have the `change_vendor` permission, plus the `add_product` permission which allows the editors group to create new products that will be foreign keyed to their vendor
- For each product, the `vendor.edtiors` group have the `change_product` permission

**Comment by MikeOverkamp-diag** [comment]
I think that should be how this is implemented. I'll discuss this afternoon with @Kicksta

**Comment by jmsmkn** [comment]
Closed due to inactivity.
