### ISSUE TITLE
Add draft property for products

### ISSUE THREAD

**Issue by MikeOverkamp-diag** [comic/grand-challenge.org#1674]
When vendors update or add products, the changes should not be published immediately. Instead, the changes should be approved by a `products-admin`. The products admin should get an email notification if a vendor has made any changes. 

The admin receives email when changes are made to be approved. There is a link included that leads to the added/adapted page. All adapted fields have a checkbox. On top there is a checkbox to (un)check all. On the bottom there is a button ‘Approve changes’ to approve all check-boxed changes. 

The admin is able to give an alternative suggestion when not approving the input. Also a comment section is present to explain the reason for non acceptance or change. Some changes may be enforced by the admin and only notified to the vendor as ‘for your information’. 

The admin may also ask for approval of the changes to the vendor. The vendor will receive an email with the (proposed) changes and a link to approve or edit. If the admin wants to propose a change they can click on ‘edit’ next to ‘read more’ on the product/company list to be redirected to the edit page of the specific company or product.

**Comment by jmsmkn** [comment]
Closed due to inactivity.
