### ISSUE TITLE
Image reader for .e2e and .fds

### ISSUE THREAD

**Issue by coendevente** [comic/grand-challenge.org#1689]
A lot of scanners in ophthalmology (especially for OCT) do not provide export functions to any of the image formats supported by grand-challenge.org at the moment. Because of this, most ophthalmologists cannot upload their own data, disallowing the use of the algorithms and archives in grand-challenge.org.

The solution for this would be to support image loading of two common formats in OCT scanners: .e2e and .fds. We already have readers available for these formats [here](https://github.com/DIAGNijmegen/retina-common/blob/master/python_modules/imageloading/decodeE2E_simplified_v2.py) and [here](https://github.com/DIAGNijmegen/retina-common/blob/master/python_modules/imageloading/decodeFDS.py), respectively.

**Comment by jmsmkn** [comment]
What are the licenses on those readers? The authors would need to make them available under the Apache 2.0 open source license that we use in grand challenge. 

Are the e2e and fds files de-identified? As detailed in the TOS the user is responsible for this before uploading to grand challenge.

Do you have any test data that we could include in the open-source test suite to use in CI?

**Comment by coendevente** [comment]
> What are the licenses on those readers? The authors would need to make them available under the Apache 2.0 open source license that we use in grand challenge.

At the moment it doesn't have a license. These readers are written by @HarmvZ together with a collaborator at Erasmus MC. I will ask them whether it is okay with them to publish it under the Apache 2.0 open source license.

In my experience [this repo](https://github.com/marksgraham/OCT-Converter) also works quite well. And it supports even more common OCT formats (.img from Zeiss and .fda from Topcon). It also does not have a license, so, even though it is a public Github repo, does that mean we cannot use it for grand-challenge without this license?

> Are the e2e and fds files de-identified? As detailed in the TOS the user is responsible for this before uploading to grand challenge.

The files are proprietary formats and all knowledge that we have about these files was retrieved using reverse engineering. As far as I know there are parts in these files for which we do not know what they encode, so there might be patient data in there. These file readers do not retrieve any patient information, however.

> Do you have any test data that we could include in the open-source test suite to use in CI?

I have examples of these files, but I will ask the data owners whether we can make some of these files public.

**Comment by jmsmkn** [comment]
> The files are proprietary formats and all knowledge that we have about these files was retrieved using reverse engineering. As far as I know there are parts in these files for which we do not know what they encode, so there might be patient data in there. These file readers do not retrieve any patient information, however.

It is not allowed to upload data that contains PII to grand challenge. Given this, and the high likelihood that these data would not be de-identified I do not think that these importers belong in the grand challenge codebase. Maybe offer your users a de-identification application that would produce de-identified mha that could be used in grand challenge, and even hooked up automatically via the REST API.

**Comment by csangut** [comment]
I don't think that this could be a solution for the Ophthalmology community as we can not provide this application to all users that would like to use GC. e2e and fds can be anonymized and it is the responsibility of the user to do so. As these are the widely adopted format for OCT in Ophthalmology (as DICOM for radiology or the propietary format from Pathology such as Aperio that is now converted to tif), I think GC should still address this. What happens now if a user upload a scan of that type not properly de-identified?

**Comment by coendevente** [comment]
> It is not allowed to upload data that contains PII to grand challenge. Given this, and the high likelihood that these data would not be de-identified I do not think that these importers belong in the grand challenge codebase. Maybe offer your users a de-identification application that would produce de-identified mha that could be used in grand challenge, and even hooked up automatically via the REST API.

Is it not just the user's responsibility to make sure they upload de-identified .fda's and .e2e's? What is the difference between this format and .mha in that regard?

**Comment by jmsmkn** [comment]
Hmm, ok, well, as long as it's abundantly clear that any uploaded data has been de-identified and that the user has permission (eg with a DTA) to upload the data that's ok. We should add a check box to try and get the user to think about this more. 

With `.mha` we have the specs for the files, so we know where PII can appear, and filter out every field that is not explicitly trusted. We still do not do anything about burnt-in information, but again, this is the responsibility of the user and grand challenge does not have any features for de-itentification.

**Comment by jmsmkn** [comment]
> In my experience this repo also works quite well. 

There's no license on that repo either, or tests...

**Comment by coendevente** [comment]
I think we can make sure that everything comes out of the reader is anonymous. The reader would then convert the .fds and .e2e files to .mha, but not writing any of the fields that could contain patient information. I think the only necessary things that should be included in the output .mha file would be pixel values, spacing and orientation. Besides the fact that the user should just not upload any files with patient information of course, I think as long as grand-challenge will not save the original .fds and .e2e files (but only the converted mha files), no patient information can be stored.

Then indeed patient information could still be burnt-in, which is the same for every other data that is currently uploaded to grand-challenge. As far as I know it is actually very uncommon in ophthalmology that patient information text gets printed into pixels.

So to be clear, if I understand correctly, what needs to be done before this can be implemented is:

- make sure the readers we use will get an Apache 2.0 open source license;
- provide test data that can be made publicly available.

Is that correct?

**Comment by jmsmkn** [comment]
> I think as long as grand-challenge will not save the original .fds and .e2e files (but only the converted mha files), no patient information can be stored.

The user uploads the data to grand challenge before these importers are invoked, the data is already in the system by the time it is read by an importer. The original data is stored whilst it is being uploaded and is then deleted after it has been imported, or 7 days in the case of an abandoned upload. So the data must be de-identified by the user before uploading, but of course, it depends on the data and what the user is allowed to do with it by their data agreements. Grand challenge is not a de-identification service, that needs to be solved with other tools configured per the local requirements. 

For any new code being contributed to the codebase, it needs to have a license that is compatible with the Apache 2.0 license (such as Apache 2.0, MIT, GPL is possible but would prefer not) so that legally we're allowed to incorporate it, and tests so that we're able to maintain it (although, you can write tests and use synthetic data, but as this is based on reverse-engineering a file format without specs that might be more difficult).

**Comment by jmsmkn** [comment]
Transferred to https://github.com/DIAGNijmegen/rse-panimg/issues/4
