### ISSUE TITLE
Add human readable columns for csv exports

### ISSUE THREAD

**Issue by MikeOverkamp-diag** [comic/grand-challenge.org#1725]
With the changes in https://github.com/comic/grand-challenge.org/pull/1718 a couple of minor issues have arisen in the csv export for reader study answers:

- Choice type answers now only display their pk, we should also add the actual textual value
- The associated images only show a url to download a csv, it would be useful to also include the image name for quicker parsing of the results

There may be more fields that need to be added. Feel free to add them in the comments.

**Comment by jmsmkn** [comment]
> Choice type answers now only display their pk, we should also add the actual textual value

Users can get this from the Questions CSV

> The associated images only show a url to download a csv, it would be useful to also include the image name for quicker parsing of the results

Users can get this from the Images CSV file

I don't think that we should do any extra parsing as this killed the server with a large study. All the information is there for the users already.

**Comment by bramvanginneken** [comment]
Yes, indeed, I now went over everything and found the names of the images. I do foresee that if you have to download files for every thousand answers this may be annoying. I have 300 images, 2 questions, 30 readers, so 18000 answers. But ok, I'll download 18 files and will glue them together.

**Comment by jmsmkn** [comment]
> But ok, I'll download 18 files and will glue them together.

Reading from multiple CSV files is trivial in Dask (https://examples.dask.org/dataframes/01-data-access.html#Read-CSV-files) or Pandas, even if you're using excel on windows you can use `copy *.csv all.csv` in `cmd`.

**Comment by bramvanginneken** [comment]
Sure, no worries, but at many places on grand-challenge limits like 1000 rows max in a csv file, or 258 pages of results on https://grand-challenge.org/algorithms/corads-ai/jobs/ is a bit annoying... You will tell me I should use the API of course :)
