### ISSUE TITLE
Annotation answers get parsed incorrectly in csv export

### ISSUE THREAD

**Issue by MikeOverkamp-diag** [comic/grand-challenge.org#1726]
For annotation type answers, the csv export looks like this currently:
![Screenshot from 2021-02-18 16-26-04](https://user-images.githubusercontent.com/57257130/108379339-1b666e00-7206-11eb-8adf-629acca14f74.png)

It appears the annotation json gets part as part of the export. We should probably add some escaping.

**Comment by jmsmkn** [comment]
Yeah, CSV does not handle nested data well at all. You can probably just override `flatten_item` in the `PaginatedCSVRenderer` we already define:

https://github.com/mjumbewu/django-rest-framework-csv/blob/master/rest_framework_csv/renderers.py#L127

and just never unwap, always return `{"": item}`. Please check the side effects of that...
