### ISSUE TITLE
add color white to Jet colormap (overlay lut in workstation viewer configuration)

### ISSUE THREAD

**Issue by njmhendrix** [comic/grand-challenge.org#1727]
I have a small request regarding the "Jet" overlay lookup table in the viewer configuration of the algorithms on Grand Challenge: could the color white (RGB = [255, 255, 255]) be allocated to pixel value/index 1? This way, I could make an overlay for my algorithm that looks like the example below. If other algorithms are also using this lookup table, perhaps a new profile needs to be created.

![zidane](https://user-images.githubusercontent.com/47858231/108519837-50d48f80-72ca-11eb-87ed-1d671cf9807c.jpg)
_Image source_: https://github.com/ultralytics/yolov5

**Comment by jmsmkn** [comment]
3 people are using this LUT - you, Miguel and Coen. I will create a new one.

**Comment by jmsmkn** [comment]
`Jet (1 white)` created.
