### ISSUE TITLE
Add link to statistics page to footer

### ISSUE THREAD

**Issue by MikeOverkamp-diag** [comic/grand-challenge.org#1741]
Currently there is a link to the statistics page (https://grand-challenge.org/stats/) on the home page only. It woould be nice to have this available on all pages in the footer in the `About` column.

**Comment by amickan** [comment]
Do I understand correctly, that this just requires adding a flatpage through the django-admin interface (and hence no changes in the code base)?

**Comment by MikeOverkamp-diag** [comment]
No the page already exists: https://grand-challenge.org/stats/

All that is needed is for a link to it to be added to: https://github.com/comic/grand-challenge.org/blob/master/app/grandchallenge/core/templates/grandchallenge/partials/footer.html

You should probably use django's url tag, as the url actuallycomes from here: https://github.com/comic/grand-challenge.org/blob/master/app/grandchallenge/statistics/urls.py, so something like `{% url 'statistics:detail' %}

**Comment by amickan** [comment]
Ok, I asked because I saw that currently in the about section it loops through all flat pages and so that's why I thought the easiest would be to just add a flatpage through the admin (linking the already existing stats page), but I can do it as you suggest.
