### ISSUE TITLE
xlsx upload fails, openpyxl missing

### ISSUE THREAD

**Issue by Kicksta** [comic/grand-challenge.org#1747]
**Describe the bug**
When uploading the product and company databases I get an error --> xlsx format is not supported. When I format the file to xls (excel 97-2003) it does work, but is not preferred. [xlrd](https://pypi.org/project/xlrd/) 2.0.1 now only reads xls. Could we use [openpyxl](https://openpyxl.readthedocs.io/en/stable/) instead?

**To Reproduce**
1. Go to aiforradiology.com/import-data
2. Upload xlsx product and company database (as usual)
3. ValueError: Your version of xlrd is 2.0.1. In xlrd >= 2.0, only the xls format is supported. Install openpyxl instead.

**Comment by jmsmkn** [comment]
@Kicksta could you:

1. `git checkout 1747_openpyxl`
2. `./cycle_docker_compose.sh` (this will take 5 mins to rebuild the containers)
3. Try the import out on gc.localhost.

I don't know if there are automated tests for this, they should have caught it if so, so I guess not.

**Comment by Kicksta** [comment]
Works flawless!

**Comment by jmsmkn** [comment]
Great! I've made a PR, could you approve it?

**Comment by Kicksta** [comment]
Wow, I have power to approve PRs?! This will be my first 🤩
