### ISSUE TITLE
Make ComponentInterface configurable

### ISSUE THREAD

**Issue by miriam-groeneveld** [comic/grand-challenge.org#1777]
The setting store_in_database is not editable when creating or editing a ComponentInterface.

**Comment by jmsmkn** [comment]
I thought that this wasn't editable by choice? Wouldn't you end up in a weird state if you changed half way through and some of your annotations are in the object store, the others in the db?

**Comment by miriam-groeneveld** [comment]
Well, now you can't set it at all, not when creating or updating. Maybe removing the default will let you set it at creation time?

**Comment by jmsmkn** [comment]
Editable False would always leave it out of creation and update forms so it should be true if we want to alter it at creation time. We should exclude this from the update views in the admin, I think you can override get_readonly_fields and check if you're in a create or update view, there is at least one example already in the code base.
