### ISSUE TITLE
Change order of the blog posts

### ISSUE THREAD

**Issue by vdgraafjasper** [comic/grand-challenge.org#1805]
Currently all blog posts that are published on grand-challenge are sorted based on the date the post was initially created. We would like to change this to the date the post was published such that the most recent post are shown on top. I had contact with @jmsmkn on slack after which he suggested a few changes I could make in the code to change this. After discussing this with Kiran we thought it might be best to first create an issue here.

**Comment by jmsmkn** [comment]
Note that they're already ordered by `post.created` (descending) https://github.com/comic/grand-challenge.org/blob/8128f42f200b68cd99dad5ba670df739def67ffd/app/grandchallenge/blogs/models.py#L31-L32. I have suggested updating the created date to `django.utils.timezone.now` when the `published` status changes from `False` to `True`.
