### ISSUE TITLE
Optional algorithm input images

### ISSUE THREAD

**Issue by nlessmann** [comic/grand-challenge.org#1811]
The interfaces for algorithm inputs can have default values for some types of inputs, but not for images. It would be very useful to be able to define optional image inputs as well. Forcing the user to upload a dummy image instead is not really workable, and inside the algorithm container it would be trivial to check whether the input was provided or not.

**Comment by jmsmkn** [comment]
Thank you for the suggestion. I am gathering all of the feature requests elsewhere, and will consider this for inclusion a future development cycle.
