### ISSUE TITLE
Feature request: add configurable file extension check

### ISSUE THREAD

**Issue by njmhendrix** [comic/grand-challenge.org#1865]
**Is your feature request related to a problem? Please describe.**
My scaphoid fracture detection algorithm (https://grand-challenge.org/algorithms/scaphoid-fracture-detection/) uses the pixel spacing information in a DICOM file to normalize the scaphoid size by rescaling the image. Therefore, I put on the information page that only DICOM and MHA files (with the pixel spacing attribute) are supported by the algorithm, but this is in contradiction with the listed file formats on the "Try-out Algorithm" page. Consequently, users keep uploading images with common file types such as PNG or JPEG, which cannot be properly processed by the algorithm. 

**Describe the solution you'd like**
(1) the ability to check the file extension of the uploaded images and to cancel the job if necessary, or 
(2) add a disclaimer to the "Try-out Algorithm" page that users need to check the information page of the algorithm to make sure that the uploaded images are supported by the algorithm. 

**Describe alternatives you've considered**
- I specified the input requirements on the information page.
- I added a warning to the algorithm output whenever I suspect that the uploaded image does not contain pixel spacing information (the SimpleITK library defaults to a pixel spacing of 1 mm when no pixel spacing information is present). I could make the warning more explicit to motivate users to upload compatible images.

**Comment by jmsmkn** [comment]
You can add a disclaimer on the job creation page by editing "Job create page markdown" in your algorithm settings. For checking metadata these are things that you need to check in your algorithm. You can pass messages to the users by writing to stderr, then if your algorithm cannot continue with the given images then exit with a non-zero exit code.
