### ISSUE TITLE
Redirect option after reader study has been completed

### ISSUE THREAD

**Issue by Kicksta** [comic/grand-challenge.org#1904]
When a reader study is finished, you get a message "Study completed". I notice the clinicians who tried it out were confused about what to do next. When you close the window you go back to the last case. 

**Describe the solution you'd like**
Option 1) E.g. add a button that says 'Return to Grand Challenge'  or 'See results' (if ground truth is given) which returns you the the respective reader study overview page showing your score if present. 
Option 2) Make the text in this popup customizable when setting up the reader study. Then admins can provide a personalized message saying thank you, telling them to go back to the main page manually to see the results, or providing a link, or ....
Option 3) Automated redirect to respective reader study overview page

**Comment by jmsmkn** [comment]
This is a CIRRUS issue, not grand challenge. Please create an issue at https://github.com/diagnijmegen/rse-cirrus-core (different org so I cannot transfer this one). Option 1 would be fine IMO.
