### ISSUE TITLE
Failed algorithm job notifications

### ISSUE THREAD

**Issue by amickan** [comic/grand-challenge.org#1907]
Currently, users receive emails about failed algorithm jobs. It would be nice to turn those into notifications instead.

Workflow: 
- create follow: `job creator` and `admins of algorithm` --> `job`
- replace message code in `send_failed_jobs_email` with action creation
- send action with `job` as actor 
- this means sending seperate notifications for failed jobs and excluded images, both in one is too long for a notification

**Comment by amickan** [comment]
What I suggest above has a few drawbacks, which made me rethink the workflow for this type of notification. 

The drawbacks of using `Job` follows are;
- We would create massive amounts of follows, one for each job. They would clutter up the follow admin and would need to remain hidden from users in the subscription overview to not overwhelm them there.
- There would be no way for editors or job creators to unsubscribe from these notifications, since with each new job, a new, unique follow is created. 

Another solution, with its own set of drawbacks, would be to make use of existing `algorithm` follows instead. We would send the action with the `algorithm` that the job pertains to as `actor`. This would result in notifications for all algorithm editors. No new follows would need to be created since editor-algorithm-follows are already taken care of. Opting out of these notifications would be possible for editors by unsubscribing from the algorithm. 
The problems with this solution, however, are the following:
- Unsubscribing from an algorithm would not only stop notifications about failed jobs, but would also stop notifications about access requests. Using the algorithm follow for both types of notifications makes it difficult to unsubscribe from only one of them. If we think that's ok, we should make sure that editors are aware of that when they unsubscribe. Maybe a warning text underneath algorithm follows on the subscription list view would do the trick. It's not very user-friendly though. To make unsubscribing from only the job notifications possible, we could also consider adding a checkbox somewhere in the algorithm settings, which would then turn of those types of notifications for all editors of the algorithm.... But that would then be a collective decision for all editors of the algorithm, not an editor-individual one, not super useful either? Also, the notification-creation signal would get more cluttered if we did that.  
- The creator also needs to be notified about the failed jobs. Adding a follow (creator - algorithm) would fix that, but that seems inappropriate given that we would then need to make sure that they do not receive notifications about access requests and possible other editor-only notifications we might add in the future. Alternatively, we could just modify the notification signal such that when the actor of an action if an algorithm, that we add the creator to the list of notification receivers. That would then also require adding the creator as target to the action because otherwise we no longer have a way to retrieve the creator of the job from the action. Either way, we will need to adjust the notification signal to account for these special notifications.... something which we would not need to do if we went with Job-follows. 

If there is a third way to get these notifications to work, I'd love to hear it. I can't seem to think of a different solution, unfortunately.

**Comment by jmsmkn** [comment]
We have to be super careful here as often we do not want users to know about jobs (for instance, in an evaluation of a challenge).

I wonder if we are hitting the limitations of actstream here and should modify the notification model as we're seeing some similar things with evaluation notifications.

**Comment by amickan** [comment]
Yes, adjusting the notification model to include (some of) the fields of the actstream.Action model, or writing our own custom Action model would be nice. I don't immediately see how it would solve the problem with the follows that we face here, but I will think about it. Intuitively, I think an Action model with a Type field and different action structure for different types (requests vs. forum activity vs. job status updates etc). would solve the semantics issues we had in past PRs and it would make notification rendering more straight-forward. To solve the issue with the follows here, maybe a recipients field on the Action model would help. Not sure yet. 

Do you think it still makes sense to implement the remaining notifications with the current architecture in place (as promised in this cycle's pitch) and then adjust and refactor, or should we pause all notification-related work until we have a better infrastructure in place?

**Comment by amickan** [comment]
Ha, just found out about the `flag` field on the `Follow` model. That allows us to further specify the follow and to distinguish between, for this specific case, Algorithm job-related follows and Algorithm access-request-related follows. I think this would solve one of the issues above.
