### ISSUE TITLE
Challenge evaluation-related notifications

### ISSUE THREAD

**Issue by amickan** [comic/grand-challenge.org#1908]
Currently, users and challenge admins receive emails about failed and successful challenge submissions. It would be nice to turn those into notifications. 

**Challenge evaluation success and failure**

- create follow: `submission creator` --> `submission`
- create follow: `admins of challenge` --> `submission`
- on success or failure: send `action` with `evaluation` as `actor` and `submission` as `target`
- _Notification template:_
  - on success, for admins: There is a new result `[evaluation]` for `[submission.phase.challenge]` from `[submission.creator]`
  - on success, for creator: You successfully submitted a new result `[evaluation]` for `[submission.phase.challenge]`
  - on failure, for admins: The submission `[evaluation]` to `[submission.phase.challenge]` from `[submission.creator]` failed.
  - on failure, for creator: Your submission `[evaluation]` to `[submission.phase.challenge]` failed.

**Missing method email**

- send action with `submission creator` as `actor` and `submission` as `target` --> this only notifies admins (followers of the target other than the actor)
- _Notification template:_ `[submission]` could not be evaluated because of missing evaluation container.

**Comment by jmsmkn** [comment]
This has highest priority for migration to notifications.
