### ISSUE TITLE
Challenge creation notifications

### ISSUE THREAD

**Issue by amickan** [comic/grand-challenge.org#1934]
At the moment, staff users receive emails about new challenges. It would be nice to turns those emails into notifications. 

**Challenge creation emails**

- create follow: `staff users` --> `gc.localhost Site`
- upon challenge creation: send `action` with challenge `creator` as `actor`, the created `challenge` as `action_object` and the `gc.localhost site` as `target`
- _Notification template:_ print action as is for normal challenges, for external challenges, make sure to link the `update_url` for the challenge in the notification rather than the challenge url

**Comment by jmsmkn** [comment]
This one doesn't have very high priority IMO as staff users are internal and we have very few of them. Also, there is no staff users group - this is controlled by a boolean on the user object.
