### ISSUE TITLE
Unwanted item added in archives

### ISSUE THREAD

**Issue by chrisvanrun** [comic/grand-challenge.org#2047]
**Describe the bug**
Archives items always adds a 'corrField Configuration'

**To Reproduce**
1. Create an Archive
2. Click on `Add Cases`, add an image
3. Click on `View Items`
4. Add a regular overlay (e.g. Heatmap)
5. Go back to `View Items`
**Expected behavior**
Only the Heatmap is added and visible under 'View Items'

**Screenshots**
![corrfield_capture](https://user-images.githubusercontent.com/7871310/135039131-f7085205-5828-4212-bfb8-7c8cb5490a5c.PNG)

**Comment by jmsmkn** [comment]
This can be replicated in development by adding a default value to an interface. Not a show stopper for running algorithms. I also think that something is up with the display of the Archive Items list.
