### ISSUE TITLE
Lock icon that indicates private algorithms, archives, etc. is not always visible

### ISSUE THREAD

**Issue by nlessmann** [comic/grand-challenge.org#2069]
For private algorithms with long titles, the lock icon is not visible, which I find confusing. For example, these two algorithms are both private:

![image](https://user-images.githubusercontent.com/773597/136191448-dd45ab06-aaa2-4989-a67f-dac3290696d9.png)

I'd like to suggest moving the lock icon to the front so that it's always visible, and I'd be happy to prepare a PR for that.

**Comment by jmsmkn** [comment]
Fixed in #2065, will be deployed today.
