### ISSUE TITLE
Syntax highlighting for GC

### ISSUE THREAD

**Issue by amickan** [comic/grand-challenge.org#2092]
It would be nice, especially for the documentation pages, to enable syntax highlighting. 

The Markdown editor we use already produces the correct html tags (`''''python` is correctly translated to `<pre><code class="language-python"> ... </code></pre>`

Getting the syntax highlighting to work is then a matter of adding some custom css. There are multiple options, one of them being [prism.js](https://prismjs.com/index.html). To use prism, we just need to add a few links to `base.html` and `style.html`: https://prismjs.com/index.html#basic-usage-cdn

**Comment by jmsmkn** [comment]
I would prefer to use something on the backend to do this. Why not `pygments` and the `codehilite` plugin for markdown? https://python-markdown.github.io/extensions/code_hilite/
