### ISSUE TITLE
repository list when creating an algorithm does not include needed repo name

### ISSUE THREAD

**Issue by keelinm** [comic/grand-challenge.org#2153]
For the algorithm named node21_detection_baseline_km I created it, then clicked "update linked repo".  The repository list provided there does not include the repo I want to link with (which I included when I created the algorithm).  The repo I want to link with is https://github.com/node21challenge/node21_detection_baseline

**Comment by MikeOverkamp-diag** [comment]
This was fixed here: https://github.com/comic/grand-challenge.org/pull/2161/files
