### ISSUE TITLE
Ask users whether they want to be put on mailing list

### ISSUE THREAD

**Issue by amickan** [comic/grand-challenge.org#2163]
Currently, under the GDPR rules, we are not able to send email updates to our users on Grand Challenge, because we do not have their explicit permission to do so. In order to make it possible to reach out to the user base in the future, it would be good to ask for their consent in retrospect. 

To do so, add a Boolean `receive_newsletter` field to the profile model.

For existing users, show a pop-up upon next log-in that asks for whether they want to be put on our newsletter mailing list and store their choice in the database. 

For new users, make this field obligatory upon sign-up.

**Comment by jmsmkn** [comment]
Just a note - it should be a nullable bool field so that you can tell between people who have opted in (True), opted out (False), or not answered (None, default).
