### ISSUE TITLE
ANHIR Challenge Submission Failure

### ISSUE THREAD

**Issue by ruqayya** [comic/grand-challenge.org#2169]
Hi,

I have been trying to submit my registration results on the ANHIR web portal. I have done it twice but getting the same error "Failed KeyError: ‘Target image’". The challenge organisers have provided a sample submission in zip format. This file seems to be corrupted as I am not able to unzip it. I am not sure if my submission is according to this sample but I have prepared it according to the description they have provided on the website. Can someone please guide me. 

Thanks.
Ruqayya

**Comment by Borda** [comment]
Hello @ruqayya, I am one of the ANHIR organizes.
 I guess that there is no issue on the platform side, rather your submission format is likely missing some mandatory items. This is the [docker image](https://github.com/Borda/BIRL/blob/master/bm_ANHIR/Dockerfile) used for evaluation (of course without the data which are kept private in the platform). For the debugging, you can use this public [CIMA dataset](https://cmp.felk.cvut.cz/~borovji3/?page=dataset)

**Comment by jmsmkn** [comment]
Thank you @Borda, indeed, this is not a platform issue and the organisers of the ANHIR challenge should be able to assist @ruqayya.
