### ISSUE TITLE
remove all superfluous calls to site_get_standard_vars

### ISSUE THREAD

**Issue by sjoerdk** [comic/grand-challenge.org#217]
Since we are now getting all standard vars to put into templates automatically from https://github.com/comic/comic-django/blob/master/django/comicsite/contextprocessors/contextprocessors.py#L27, any calls to get these again in views is not needed,

code in https://github.com/comic/comic-django/blob/master/django/comicsite/views.py can be greatly simplefied

**Comment by jmsmkn** [comment]
DONE!
