### ISSUE TITLE
Option to hide a challenge phase's leaderboard and submit page

### ISSUE THREAD

**Issue by amickan** [comic/grand-challenge.org#2226]
**Problem / Context** 
We have had a request from a user who would like to hide or remove one of the phases of his challenge. 
Context: The challenge has two phases. The second phase was created because the evaluation method changed. They would now like to hide the leaderboard associated with the first phase (which uses an incorrect / outdated evaluation method). 

**Solution**
Rather than deleting the first phase entirely, which would also require deleting all submissions to the phase, we could add a `hide leaderboard / submit page for this phase` option to the `Phase` settings, which can be enabled or disabled by challenge admins.

This would require hiding the respective submit and leaderboard tabs from the challenge navbars as well as retracting view and create permissions for submissions and evaluations in order to make sure that the respective submit and leaderboard pages are really not accessible anymore by participants of the challenge (and normal users of GC for public challenges). 

We should only implement this if there is enough use for this option. If it is a one time issue, this is probably not worth implementing.

**Alternative solutions**
Decoupling a phase from a challenge (in the admin, setting the `challenge` field on the `Phase` model to none), is not possible as far as I can tell.

**Comment by amickan** [comment]
Reopening this issue as I've received more such requests in the past weeks. 

On second thought, revoking `submission create permissions` is not necessary, we can just set the `submission_limit` to 0 to disable submissions to the phase. `View permissions` for old submissions are fine to keep I would say. For the evaluations, changing the view permissions (necessary to really hide the leaderboard) is pretty straigthforward.

**Comment by jmsmkn** [comment]
Please consider how a challenge admin will navigate and test out the submission and leaderboard if they are hidden.

**Comment by amickan** [comment]
Good point. Admins would keep the view and change permissions for evaluations regardless of wether the phase is hidden or not. In the phase navbar template we can check the challenge permissions and only show the respective phase tab if the phase is not hidden or if the current user has the `change_challenge` permission. That way the phase remains accessible for the admins, while being hidden for everyone else.
