### ISSUE TITLE
changing project name does not work properly

### ISSUE THREAD

**Issue by sjoerdk** [comic/grand-challenge.org#224]
Similar to #223. Creating a new ticket because previous one solved only the direct (crashing, 500 server error) type problem.  We should also solve the deeper problem

Which is: project name, in parameter short_name, is used throughout the code and outside the code as a key. Changing this key later on makes things not work. Everybody knows you should never use names as keys of course.. but this is the case anyway so lets solve it ok?

Items which are dependent on short_name:
- url for project
- file folder files are sought in
- name of permissions for admins and participants

**Comment by jmsmkn** [comment]
This is now fine except for the file folders which are hard coded. Nothing can be done about that with the dropbox setup, so, just disallow changing names for now.
