### ISSUE TITLE
Link reader study questions to all image ports

### ISSUE THREAD

**Issue by njmhendrix** [comic/grand-challenge.org#2265]
**Is your feature request related to a problem? Please describe.**
When using the reader studies functionality of Grand Challenge for making image-level annotations such as bounding boxes, the corresponding question needs to be duplicated for each image port. If you need to annotate multiple structures in several images, then the list of specified questions can become too long to be manageable. 

**Describe the solution you'd like**
If technically feasible, it would be convenient to specify 'image port agnostic' questions that allows the user to make annotations in any image port.

**Describe alternatives you've considered**
The problem can be circumvented by using a single image per case. However, in my PhD project I need to indicate the location of one or multiple fractures in a series of x-rays, and it is much easier to locate the fractures if you can see the images in a series (or entire exam) side-by-side. Furthermore, if one could select a bounding box and then select a label from a dropdown list, then this problem would also be mitigated to a certain extent.

**Comment by jmsmkn** [comment]
Thank you for the suggestion. This is not something we're going to be able to do right now but will keep this use case in mind.
