### ISSUE TITLE
Display set list view slow with a lot of images

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#2379]
**Describe the bug**
The display set list view is slow when there are a large number of images

**To Reproduce**
1. New reader study
2. Upload a bunch of images
3. Navigate to /display-sets/

**Additional context**
I don't think this is an N+1, but might be. More likely rendering all of the images in each drop down selection. If not an N+1 then needs moving to select2 autocomplete with appropriate permissions.

**Comment by MikeOverkamp-diag** [comment]
Shouldn't be an N+1, as that was resolved in #2369. I'll look into it though.
