### ISSUE TITLE
Users cannot map answers to images

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#2436]
With the introduction of Display Sets for reader studies there have been several users who have asked how to link answers to images:

- https://github.com/DIAGNijmegen/rse-gcapi/issues/129
- https://teams.microsoft.com/l/message/19:6daf914d105b412989baaffa5b066dfa@thread.tacv2/1650973157371?tenantId=b208fe69-471e-48c4-8d87-025e9b9a157f&groupId=97a88c45-447f-4147-9e80-5e7c013f7501&parentMessageId=1650973157371&teamName=DIAG&channelName=Grand%20Challenge&createdTime=1650973157371
- https://teams.microsoft.com/l/message/19:6daf914d105b412989baaffa5b066dfa@thread.tacv2/1651756065894?tenantId=b208fe69-471e-48c4-8d87-025e9b9a157f&groupId=97a88c45-447f-4147-9e80-5e7c013f7501&parentMessageId=1651756065894&teamName=DIAG&channelName=Grand%20Challenge&createdTime=1651756065894

To solve this:

- Display sets and Images CSV files need to be added to the Reader Study export tab
- Documentation needs to be added to https://grand-challenge.org/documentation/reader-studies/

**Comment by MikeOverkamp-diag** [comment]
Do we really need to also link the images csv? Since the answers are mapped to display sets won't that be enough? Or do we need to include the images csv to include the original source file?

**Comment by jmsmkn** [comment]
The display set CSV only contains links to images. The images are needed so that the user can map those links to the image name.

**Comment by jmsmkn** [comment]
This will need updating https://github.com/comic/grand-challenge.org/blob/2e676876e4b8ca815eeb5fe96bf820530057dd19/app/grandchallenge/cases/filters.py#L41

Obviously there is a test missing there too as it doesn't work right now!
