### ISSUE TITLE
Remove validation for shuffling cases + case navigation

### ISSUE THREAD

**Issue by chrisvanrun** [comic/grand-challenge.org#2442]
Continuing from:
- https://github.com/DIAGNijmegen/rse-roadmap/issues/12#issuecomment-1118667097

Disabling validation was based on the assumption that when shuffling an `index` would not be provided because of performance issues.

However, a quick test of the endpoint on a test reader-study would suggest it already works. Not sure if this was solved by @MikeOverkamp-diag since the validation was introduced in:
- https://github.com/comic/grand-challenge.org/pull/2415

From the CIRRUS side, it seems there are no explicit checks and it should already work.

**Comment by MikeOverkamp-diag** [comment]
It was not, the current index in the detail view when the ordering is shuffled is incorrect. The reason is that in order to determine the index in the case of shuffling, we need to determine the index in the full list of display sets. That means that we would need to load the entire list of display sets for a reader study to determine the index in the detail view.

**Comment by jmsmkn** [comment]
> It was not, the current index in the detail view when the ordering is shuffled is incorrect. 

That's when we return `None`, right? So that value is never used.

I still don't really understand why this combination isn't allowed. Can you walk me through this? Some documentation and a sequence diagram would really help.

**Comment by MikeOverkamp-diag** [comment]
The check in gc was added because of this comment: https://github.com/DIAGNijmegen/rse-roadmap/issues/135#issuecomment-1105199651 (ans the ones following that). There is no reason that it shouldn't be allowed, other than the fact that the index on the detail view is not set, so that cannot be used.

**Comment by jmsmkn** [comment]
So is it used? I don't see what the problem is. That comment does not make things any clearer to me.

**Comment by MikeOverkamp-diag** [comment]
As far as I know it is not used in cirrus, @chrisvanrun can you confirm? I just went off what was discussed in that issue and added  the check.

**Comment by MikeOverkamp-diag** [comment]
To clarify: this only holds for the detail view. Using the list view with a `limit=1` filter works as it should. I was under the impression that that would be used in cirrus.

**Comment by chrisvanrun** [comment]
It seems like some confusion happened between list and detail views and the support therein for `index`. (Since I didn't realise the detail view doesn't provide it.)

Detail view is never used by CIRRUS. At least, currently, that will likely change when we implement loading a specific display set per:
- https://github.com/DIAGNijmegen/rse-roadmap/issues/148

That puts us in a bit of bind:

## Regular reader-study loading
Can easily and already support `allow_case_navigation` even when shuffling the cases.

## Directly loading a display-set
No (current) way of knowing the index of the display-set in the reader study. This would break a few features in CIRRUS, including but not limited to:
* Case navigation plug-in, partial fixable but only by replacing it with a more naked got-to-index `x` functionality.
* Pre-loading images for next cases, thus resulting in slower case-to-case transitions

**Comment by chrisvanrun** [comment]
I suggest we bite the proverbial bullet and take the performance hit for a detail view and generate the index.

**Comment by MikeOverkamp-diag** [comment]
Already fixed here: https://github.com/comic/grand-challenge.org/pull/2450
