### ISSUE TITLE
Ground truth for optional choice questions

### ISSUE THREAD

**Issue by miriam-groeneveld** [comic/grand-challenge.org#2477]
**Describe the bug**
It's not clear how to provide a ground truth when a reader study contains optional questions. What should be the value if an optional question should remain empty?

**To Reproduce**
1. Open a reader study with an optional question of type choice
2. Go to ground truth, download the example, change the values and upload.

**Expected behavior**
A description of what is wrong with the csv and how to fix it.

**Screenshots**
Depending on the content of the csv, it either states invalid values (for example with '"None'):
![image](https://user-images.githubusercontent.com/51329283/171624569-838b3eed-8a6b-4558-8363-887889e71cb0.png)

or error (for example with ""):
![image](https://user-images.githubusercontent.com/51329283/171624398-05cc21e2-3b1f-4f85-99bc-5e16a4b40961.png)

**Comment by jmsmkn** [comment]
My guess would be to use `null` rather than `None` as it looks like you hit a JSON decode error. That 5xx error should anyway be handled too.

**Comment by miriam-groeneveld** [comment]
I tried `null` as well, results in the error on `None` not being valid.

**Comment by miriam-groeneveld** [comment]
Uploading a ground truth when a heading question is present is also not possible.

**Comment by MikeOverkamp-diag** [comment]
FYI: I'm working on this during downtime from https://github.com/DIAGNijmegen/rse-roadmap/issues/137. If you find any more issues, please continue to put them in the comments here.

**Comment by MikeOverkamp-diag** [comment]
Update on this:

The optional answers and heading type questions are fixed. I'm working on a delete button for all gt answers and tried to do so with an endpoint in the reader studies api, but ended up in a bit of a permission hell, so I'm going to rework that solution.
