### ISSUE TITLE
Challenge runtime statistics are not correct

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#2492]
Looking at the Tiger statistics, for Segmentation and Detection (Final) phase:

Average algorithm job duration for Segmentation and Detection (Final):	25 minutes
Total algorithm job duration for Segmentation and Detection (Final):	4 days

There has been 1 submission to this phase:

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/12661555/172356728-3c3656ca-cbf9-48e6-a886-29435e11e660.png)

Looking at a couple of those results they seem to take ~30 seconds each, and maybe 50 jobs. I think what is happening is that the algorithm was used for multiple phases, and there are different versions, which are inflating the runtime statistics.

**Comment by amickan** [comment]
Hm tricky. We could additionally filter on the viewer_groups when retrieving the jobs to calculate the average duration for. That would limit the jobs to jobs for that challenge, but it could still include jobs from another phase of the same challenge, so not really a solution to the problem. But I don't think we have any way of distinguishing jobs any further than this, or do you see another way?

**Comment by jmsmkn** [comment]
Maybe only include jobs that have input images from the archive that is linked to the phase?
