### ISSUE TITLE
Image names are not shown in display sets

### ISSUE THREAD

**Issue by miriam-groeneveld** [comic/grand-challenge.org#2495]
**Describe the bug**
Display set with multiple images does show image and pk in card header, but image names are missing in the card content. 

**To Reproduce**
1. Go to a reader study
2. Upload a new image
3. Go to Cases > View/Delete Cases
4. Expand display set. Not all images are shown (see screenshot)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/51329283/172311283-af88ba8d-c12b-496a-bbbf-049d07aa8174.png)

**Comment by jmsmkn** [comment]
@MikeOverkamp-diag is re-working this in #2488, is it still an issue there?

**Comment by MikeOverkamp-diag** [comment]
This is no longer an issue in the PR @jmsmkn mentioned. My guess is that this happened due to the harsh caching which got removed in that PR.
