### ISSUE TITLE
Validation error for display set update form is suppressed

### ISSUE THREAD

**Issue by HarmvZ** [comic/grand-challenge.org#2498]
**Describe the bug**
Validation error for display set update form is suppressed.

**To Reproduce**
1. Go to the cases list view for a reader study.
2. Open a display set and click on edit.
3. Enter an invalid value for one of the component interface fields and click on save.
4. The changes are not saved because there is a validation error but that error is not visible to the user. It can only be seen in the network tab.

**Expected behavior**
The error is shown to the user.

**Screenshots**

https://user-images.githubusercontent.com/2001094/172578489-353579cd-03e3-49d8-b5bb-fa2dd1d60b95.mp4

**Comment by MikeOverkamp-diag** [comment]
Working on this now. The problem here is that django does not actually return an error status code, but just a 200 with the form re-rendered with integrated error messages, so we cannot use ajax `success` and `error` out of the box.
