### ISSUE TITLE
JSONEditor fails to load for component interface in display set form

### ISSUE THREAD

**Issue by HarmvZ** [comic/grand-challenge.org#2499]
**Describe the bug**
JSONEditor fails to load for component interface in display set form.

**To Reproduce**
1. Create a reader study containing a question where component interface field is set to an interface that is defined using JSON.
1. Go to the cases list view for that reader study.
1. Open a display set and click on edit.
1. The JSONEditor widget is not loaded for the interface field.
1. An error is shown in the console.

**Expected behavior**
JSONEditor widget loads correctly.

**Screenshots**

![image](https://user-images.githubusercontent.com/2001094/172585070-00d0d4bd-b22d-476c-9b11-9700d9b16a5c.png)

See the empty space below "Region-of-interest". The JSONEditor widget should show up there. As the error in the console indicates, the following files (JSONEditorWidget dependencies) are somehow not loaded:

https://github.com/comic/grand-challenge.org/blob/5a193d8970a66cfd53617262414da90b1ab0b2aa/app/grandchallenge/core/widgets.py#L17-L19

**Comment by MikeOverkamp-diag** [comment]
I think `{{ form.media }}` is not included anywhere, as the forms are loaded dynamically. I'm looking into a clean way to include it just once in the main list template and not for each form that is loaded.

**Comment by MikeOverkamp-diag** [comment]
Update: should have a fix, just waiting for mij terribly slow connection to pull in all the docker layers so I can test it.
