### ISSUE TITLE
Users cannot create archive items without images in the html templates

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#2508]
**Describe the bug**
The only way for a user to create a new archive item through the html templates is to upload an image. Some algorithms work without images, so a user needs a way to upload non-image files directly to new archive items. I think that they can use the API client to work around this, but unsure, @MikeOverkamp-diag could you confirm ASAP?

**Expected behavior**
A user uploads non-image interfaces and archive items are created for them.

**Additional context**
Related to #2506

**Comment by MikeOverkamp-diag** [comment]
Yes, they should be able to use `client.archive_items.create` to create an
item and then add the values using `client.update_archive_item`.

**Comment by jmsmkn** [comment]
Great - can you create a code snippet and test it - eg I have a bunch of pdf files in a folder, upload them all to an archive.

**Comment by MikeOverkamp-diag** [comment]
Ah sorry, that doesn't work. The archive item viewset is currently a ReadOnlyModelViewSet with the UpdateModelMixin, so create is not allowed on the gc side. Do you want me to create a pr to add the create mixin as well?

**Comment by MikeOverkamp-diag** [comment]
Currently testing against my local gc instance and making changes to make this work.

**Comment by jmsmkn** [comment]
What are the implications of this approach? At the moment the only way to create an Archive Item is by uploading images, so I think that it means that we never have empty Archive Items. There might be assumptions about Archive Items being empty or not elsewhere in the codebase - in particular with type 2 challenges and algorithm linking.

**Comment by MikeOverkamp-diag** [comment]
That may very well be true, I'll have a look at what happens if there are archive items with no values. If that turns out to be problematic we need to implement a proper create function in the serializer that can handle nested values and error out if no values are supplied on create.

**Comment by MikeOverkamp-diag** [comment]
An intermediate solution would be to add a feature flag to the archive model that allows users to create display sets, then tell the user we set this for to always fill them and warn them about possible unexpected behavior while we work on the proper create serializer?

**Comment by amickan** [comment]
I think a convenience method in gcapi like we have for updating archive items would be nice and shouldn't be too hard to implement (but that also requires a create endpoint for archive items on the GC side, of course).

**Comment by MikeOverkamp-diag** [comment]
Ok, I can now create an empty archive item via the api locally. I like Anne's suggestion, but that would still leave us with temorarily empty archive items. I'll have a look at the implications of that.

**Comment by MikeOverkamp-diag** [comment]
For algorithm jobs, any items with invalid values for the algorithm are filtered out before the job is created in the task, so that should not lead to any issues.

**Comment by MikeOverkamp-diag** [comment]
I cannot easily find how challenges are connected to archives, I assume through algorithms? In that case there should be no issue there either. Can someone confirm?

**Comment by amickan** [comment]
It's through evaluations: https://github.com/comic/grand-challenge.org/blob/70d9ad3b4e98f4b94e54f489e826040cd6329e96/app/grandchallenge/evaluation/tasks.py#L123 and it uses the same way of creating algorithms jobs, so should be fine indeed.

**Comment by MikeOverkamp-diag** [comment]
Everything works via gcapi locally now, just not in the tests. PR should be out soon.

**Comment by MikeOverkamp-diag** [comment]
PR is ready. Code snipper for gcapi:
```
from gcapi import Client 

```

**Comment by MikeOverkamp-diag** [comment]
Should I create a utility function for this in gcapi? It's not a lot of code and it needs to be changed based on use case (e.g. with multiple values per ai), so I'm leaning towards letting users do this themselves.

**Comment by jmsmkn** [comment]
No not worth it for a two liner.
