### ISSUE TITLE
Display set does not expand

### ISSUE THREAD

**Issue by miriam-groeneveld** [comic/grand-challenge.org#2512]
**Describe the bug**

**To Reproduce**
1. Go to https://grand-challenge.org/reader-studies/demo-educational-reader-study/
2. Click on 'Cases', 'View/Delete Cases'
3. Try and expand the display sets
4. Console errors:
Response Status Error Code 500 from /reader-studies/display-sets/REDACTED/ 

Sentry issue:
https://sentry.io/organizations/grand-challenge/issues/3345009229/?project=303639&query=is%3Aunresolved&statsPeriod=24h

**Expected behavior**

**Screenshots**

https://user-images.githubusercontent.com/51329283/173305909-d1a5b0f0-06d6-43be-86c3-47cf2917909b.mp4

**Comment by jmsmkn** [comment]
Was writing the same issue then realised the fix was quicker ;-) #2513
