### ISSUE TITLE
Algorithm output to stdout/stderr is no longer captured

### ISSUE THREAD

**Issue by nlessmann** [comic/grand-challenge.org#2526]
For all recent jobs, the logs are empty even though I'm sure that the algorithms print something to stdout.

**Comment by jmsmkn** [comment]
This is not an issue with this repo, rather the infrastructure we run on. Moving to https://github.com/DIAGNijmegen/rse-grand-challenge-admin/issues/59.

**Comment by jmsmkn** [comment]
This has now been resolved, failed algorithm jobs and evaluations run between June 13th 1700 UTC and June 17th 2022 1100 UTC may be erroneously labelled as "No logs produced".
