### ISSUE TITLE
2FA reports failure for login but succeeds

### ISSUE THREAD

**Issue by chrisvanrun** [comic/grand-challenge.org#2544]
* Enable 2FA as per request at first login of my 'admin' account
* Try to log in with my 'admin' account, which is a google account (for extra security).
* Provide 2FA code

Get reported:
<img width="886" alt="Screenshot 2022-06-24 093215" src="https://user-images.githubusercontent.com/7871310/175486165-ca9584f8-ce57-4f47-a46f-6a32fde11ec9.png">

But it seems indeed successful as I can continue to GC.

**Comment by chrisvanrun** [comment]
Suspected (based on timing) sentry issue:
https://sentry.io/organizations/grand-challenge/issues/3374906811/?project=303639&query=is%3Aunresolved

**Comment by chrisvanrun** [comment]
_Browser_: MS Edge Version 102.0.1245.44 (Official build) (64-bit)
_Authenticator_: Microsoft Authenticator

(oh dear, I've fallen to the MS side)

**Comment by miriam-groeneveld** [comment]
Issue reported again by @cjacobs1, using Microsoft authenticator

**Comment by jmsmkn** [comment]
Using social logins or a normal account?

**Comment by jmsmkn** [comment]
May be solved with #3215

**Comment by jmsmkn** [comment]
@amickan Is this solved with #3333?

**Comment by jmsmkn** [comment]
Closed by #3333
