### ISSUE TITLE
UI optimizations

### ISSUE THREAD

**Issue by miriam-groeneveld** [comic/grand-challenge.org#2571]
**Is your feature request related to a problem? Please describe.**
A few issues:
1. Adding and deleting certain objects is cumbersome. For example, when deleting a question in a reader study, the user gets redirected to the overview page of the reader study. This is annoying when deleting several questions. This happens when deleting questions, readers, editors but also when adding readers and editors (also in other contexts like algorithms) 
2. Interfaces are not sorted or searchable in the drop down control when adding CIVs.
3. When setting the view content, there's no overview which interfaces are used in the reader study/algorithm/archive. It would be nice if this is displayed, or if there is an option to create a view content with all available interfaces, so the user does not have to copy or type them.

**Comment by jmsmkn** [comment]
1. Can you specify on which pages/URLs these occur on, and which page/URL they should redirect to when done
2 & 3. What page/URL is that on?
