### ISSUE TITLE
Overlay Segments can be `None` in Question Update view, causes transaction error

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#2608]
https://sentry.io/organizations/grand-challenge/issues/3453755278/

**Comment by chrisvanrun** [comment]
Also here: https://grand-challenge.sentry.io/issues/3810511568/?project=303639&query=is%3Aunresolved&referrer=issue-stream

**Comment by chrisvanrun** [comment]
Deep in the cleaning methods, this is return `None`:
`form.fields['overlay_segments'].to_python([])`
