### ISSUE TITLE
Listing interfaces in archive update form does not work with empty archive items

### ISSUE THREAD

**Issue by amickan** [comic/grand-challenge.org#2609]
Listing the interfaces used in an archive (on the archive update form) does not work if there are empty ArchiveItems:

https://sentry.io/organizations/grand-challenge/issues/3455239880/?project=303639&query=is%3Aunresolved

The same issue might be there for algorithms and reader studies?

**Comment by jmsmkn** [comment]
> The same issue might be there for algorithms and reader studies?

Indeed, may be related to #2608

**Comment by jmsmkn** [comment]
Confirmed that the same problem exists for Reader Studies so that needs to be fixed too.
