### ISSUE TITLE
Cannot create segmentation interface

### ISSUE THREAD

**Issue by chrisvanrun** [comic/grand-challenge.org#2664]
When trying to create a **new** segmentation interface via the admin. backend I get the following clean error:
`Overlay segments cannot be changed, as values or questions for this ComponentInterface exist.`

This is weird because the interface does not exist yet.

**Comment by chrisvanrun** [comment]
Directly replicable in local dev instance.

**Comment by MikeOverkamp-diag** [comment]
Found the issue: `Question.objects.filter(interface=self).exists()` evaluates to `True` if there are questions with no interface set.

I'll add an `if self.pk is not None` tot the check.

**Comment by MikeOverkamp-diag** [comment]
`ComponentInterface` is not a UUID model though, sot it works here.
