### ISSUE TITLE
Remove apache url rewriting dependency from subdomain based project handling

### ISSUE THREAD

**Issue by sjoerdk** [comic/grand-challenge.org#267]
Make it possible to show project1 content for project1.comicframework.org, without relying on apache url rewriting. Url rewriting is hard to debug and introduces additional logs to check, etc. Django is capable of redirecting itself using some kind of middleware

**Comment by jmsmkn** [comment]
I have simplified this a lot on the branch. The remaining tasks are to:

- [ ] Allow lookup based on the request challenge for the subdomain views
- [ ] Fix the favicons on subdomains
- [ ] Move the MAIN_PROJECT to [django flatpages](https://docs.djangoproject.com/en/2.1/ref/contrib/flatpages/) as having this special challenge results in a lot of confused code

**Comment by jmsmkn** [comment]
Development is done, needs to be checked in staging and deployed when I'm back
