### ISSUE TITLE
'Clear all' button in 'add to reader study' form for archives

### ISSUE THREAD

**Issue by leandervaneekelen** [comic/grand-challenge.org#2673]
**Is your feature request related to a problem? Please describe.**
The 'add to reader study' button in the archives of Grand Challenge allow you to export archive items from your archives to your reader studies. The page notes that it helpfully pre-selects all cases in the archive for you to transfer to a reader study of choice. However, when you /don't/ want to use all cases, you have to hold CTRL+backspace in the 'Items' field, especially in my case, since my archive contains ~400 cases and I only want to select 10.

**Describe the solution you'd like**
A 'clear all' button to clear all pre-selected cases so I can select the specific cases I want.

![image](https://user-images.githubusercontent.com/47320151/193030995-d97455c3-da52-4d73-8bbe-30a810548352.png)

**Comment by jmsmkn** [comment]
Thanks for the suggestion, we will keep it in mind. As a workaround you can filter and update the selected elements by using a bit of JavaScript in the console: `$('#id_items').val(null).trigger('change');`
