### ISSUE TITLE
Feature Request: Allow user/admin to edit comments/supplementary files on submissions

### ISSUE THREAD

**Issue by jasonkena** [comic/grand-challenge.org#2697]
I am currently hosting the [SNEMI3D](https://snemi3d.grand-challenge.org/evaluation/challenge/leaderboard/) challenge and it would be great if I were able to add new comments/alter supplementary files/publication metadata on previous submissions.

Any help would be greatly appreciated.

**Comment by jmsmkn** [comment]
You can contact support if you would like to update any of these.
