### ISSUE TITLE
Users should not be able to use their email address as a username

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#2705]
We display users usernames in a lot of places. Some users use their email address as their username, this should fail a validation check.

**Comment by james-milburn-crowe** [comment]
Can grab this as a first issue! (but can't assign myself yet!)

**Comment by jmsmkn** [comment]
What is the status of this?

**Comment by james-milburn-crowe** [comment]
Have a single unrelated test failure here, https://github.com/comic/grand-challenge.org/tree/username_not_email
I'm trying to work out why

**Comment by james-milburn-crowe** [comment]
Just moved all the validation logic to a separate validator, and it seems to be working. Just waiting for tests to complete on jenkins,

**Comment by jmsmkn** [comment]
> Just waiting for tests to complete on jenkins,

FYI we aren't using Jenkins for our CI (for anything we do now), for this repo everything is run using GitHub Actions.
