### ISSUE TITLE
Old page slugs don't get capitalized. 

### ISSUE THREAD

**Issue by daangeijs** [comic/grand-challenge.org#2708]
**Is your feature request related to a problem? Please describe.**
I noticed in a NOS article that there is a change in the link formatting, therefore breaking the link to our camelyon17 challenge. 

**Describe the solution you'd like**
Capitalize the slugs in the request, so it always start with a capital. 

**Describe alternatives you've considered**
None

**Additional context**
This is the link:
https://camelyon17.grand-challenge.org/ **background/**
News article: https://nos.nl/artikel/2161091-computer-kan-kanker-beter-herkennen-dan-patholoog

Should be:
https://camelyon17.grand-challenge.org/ **Background/**

**Comment by jmsmkn** [comment]
We don't change, and have never changed, the slugs. Precisely for this reason. The URL for this page has always been capitalised (https://web.archive.org/web/20170315135036/https://camelyon17.grand-challenge.org/Background/). My guess is that the link from NOS was always broken.
