### ISSUE TITLE
Getting up to speed on grand challenge - James C

### ISSUE THREAD

**Issue by james-milburn-crowe** [comic/grand-challenge.org#2724]
As requested by @jmsmkn - a log of what I'm doing/have done to get up to speed on grand challenge, and learn the codebase and things around it.
Django tutorial - from tutorial 3, as a refresher: https://docs.djangoproject.com/en/4.1/intro/tutorial03/

Ran through terraform tutorials for aws: https://developer.hashicorp.com/terraform/tutorials/aws-get-started 

Upcoming:
AWS cloud practitioner course
Figure out how to make Kubernetes backend, as per https://github.com/comic/grand-challenge.org/blob/d1c29a80f788a2fb8500ed3bf640183c93361abe/app/grandchallenge/components/backends/base.py

**Comment by jmsmkn** [comment]
It's better to do this in the Roadmap repo, can't move this as it is cross-organisation.
