### ISSUE TITLE
Make answer colors persistent across sessions/allow for default display colors

### ISSUE THREAD

**Issue by leandervaneekelen** [comic/grand-challenge.org#2729]
**Is your feature request related to a problem? Please describe.**
My readers or histopathology cases indicated that, understandably, the color of answers such as points, polygons or bounding boxes have the tendency to blend into the background, making them hard to find. While the colors of answers are alterable, this change is not persistent between sessions, causing one my readers to, quote, 'give up' changing the colors every time he hopped back into a reader study. You can also not specify the default color of answers to solve this issue for the readers.

**Describe the solution you'd like**
Make the color of answers in the GC viewer persistent across sessions or allow for specifying the default display color associated with an image.

**Comment by jmsmkn** [comment]
Will keep the request in mind, this is the wrong place for it. Users can create feedback directly in the viewer for issues like that using the option in the top right drop down menu, it’s not something we would be able to automatically detect.

**Comment by jmsmkn** [comment]
Roadmap issue here: https://github.com/DIAGNijmegen/rse-roadmap/issues/205
