### ISSUE TITLE
Feature request: default brush size

### ISSUE THREAD

**Issue by brambozz** [comic/grand-challenge.org#2734]
**Is your feature request related to a problem? Please describe.**
I recently ran a short pilot reader study for adhesion detection on cine-MRI. Readers were asked to annotate with a brush (answer type Mask). Since adhesions are very small structures, I would like the readers to use a small brush size, e.g. 4 mm. Currently the default brush size is very big for my use-case.

**Describe the solution you'd like**
An option to set a default brush size for a reader study.

**Describe alternatives you've considered**
Instructing the readers to set the size themselves. Main drawback here is that readers will not do this consistently, so I get varying brush sizes in the answers.

**Comment by jmsmkn** [comment]
Roadmap issue here: https://github.com/DIAGNijmegen/rse-roadmap/issues/205
