### ISSUE TITLE
Default text in a multi line text answer 

### ISSUE THREAD

**Issue by vdgraafjasper** [comic/grand-challenge.org#2751]
**Is your feature request related to a problem? Please describe.**
I have a lumbar spine reader study in which a radiologist has to score certain features for all vertebral levels. For most features, the radiologist has to fill in the number of the vertebral level if that feature is present at that specific level in a single line text field. However, for other features, there are specific grading (e.g. from one to five). If I do it in the same manner, it would mean that I need 5 questions with a single line text field which is not intuitive to use and looks cluttered. 

**Describe the solution you'd like**
A multi line text field with default text. If I can use a multi line text field where the radiologist fills in all the different gradings for the different vertebral levels. The field is already filled with:
Grade 1:
Grade 2:
Grade 3:
etc.
And the radiologist has all the results and grades together in one clear field.

**Comment by jmsmkn** [comment]
To gather 5 different values use 5 different number fields, then you get validation of the values returned. You can opt for horizontal layouts to reduce the vertical space.

**Comment by vdgraafjasper** [comment]
That won't work since the amount of numbers filled in per grade differs. It can be between 0 and 10. For example:
Grade 1: 3,5,6,7
Grade 2: 1,2
Grade 3: 
Grade 4:
Grade 5: 4

I'm open for any other suggestions!

**Comment by jmsmkn** [comment]
Then use multiple choice question types.
