### ISSUE TITLE
Starting a workstation session should not log JS errors by default

### ISSUE THREAD

**Issue by chrisvanrun** [comic/grand-challenge.org#2771]
A catch should be introduced to prevent showing the expected failure when all regions are tried:

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://ca-central-1.grand-challenge.org') does not match the recipient window's origin ('https://eu-central-1.grand-challenge.org').

Do note: Firefox throws this in the grand-challenge console whereas Edge throws it in the CIRRUS console.

**Comment by chrisvanrun** [comment]
It might not be possible: https://stackoverflow.com/questions/17080447/javascript-try-catch-trouble-capturing-window-postmessage-errors

**Comment by jmsmkn** [comment]
Can we set a wildcard only for the subdomain in the `postMessage` request? There should not be a problem with doing that on challenge subdomains as we do not allow custom JS there (and obviously never will).

**Comment by chrisvanrun** [comment]
I played around a bit with this past week, and it is either `"*"` or a full origin. No regex options possible. 

An extreme fix would be to add a `"*"` wildcard with asymmetrical cryptography over the data but that seems a lot to just fix an error in the console.

Maybe there is some way of doing a manual preflight check to the window.

**Comment by jmsmkn** [comment]
I don’t think that we can inspect the origin on the window apriori unless we explicitly allow the parent domain access from the subdomain. There might be a header we can set server side to allow it, I will check.

**Comment by jmsmkn** [comment]
As Chris described we cannot catch or silence the error. The only way to suppress this would be to not send the message to the wrong sub-domain in the first place. It is not possible to find out what the origin of the new window is unless it is on the same domain as the caller. We cannot broadcast to all subdomains, only all domains which we do not want to do for privacy reasons.

The only way around this that I can see now would be to know on which subdomain the workstation would be launched/is running for the user. That would be a lot of work, and would save a small amount of time when starting the workstation, but honestly not worth it just to suppress a message in the console.
