### ISSUE TITLE
Validation of an empty JsonField fails when the field is required despite the schema allowing null values

### ISSUE THREAD

**Issue by amickan** [comic/grand-challenge.org#2807]
**Describe the bug**
Validation of an empty JsonField fails when the field is required despite the schema allowing null values.

**To Reproduce**
1. Try to create a job for an algorithm with the "spacing" interface as input interface while leaving the spacing json field empty. 
2. The form fails validation with "This field is required" error

On the display set create / update forms an empty value for this field is accepted, because there the field is not required. 

**Expected behavior**
The form should pass validation whether required or not.

**Comment by jmsmkn** [comment]
Ah, I see. Quick workaround would be to make an algorithm configuration interface, an use an object instead rather than null or number directly:

```json
{
  "spacing": null | number
}
```

Otherwise, this will get quite tricky as we do not have direct support for optional inputs.
