### ISSUE TITLE
Loading gif is confusing

### ISSUE THREAD

**Issue by miriam-groeneveld** [comic/grand-challenge.org#2829]
**Describe the bug**

There are several places in Grand Challenge where a loading gif is used (trying out an algorithm for instance):
![image](https://user-images.githubusercontent.com/51329283/230577694-869f24c8-1eaa-40ce-9120-726b8b63e8fd.png)
This incorrectly suggests that it will be updated once done, but the user needs to refresh the page to get the updated status. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jmsmkn** [comment]
It is suggesting that something is actively happening on the system, not that it will be automatically updating. Implementing polling for all of the places it is used would be a tremendous amount of work.

**Comment by miriam-groeneveld** [comment]
We could aslo show a different icon that does not suggest it will update without refresh? It's not consistent, in the overview in the screenshot it will not update, in the view below it does update. 
![image](https://user-images.githubusercontent.com/51329283/230586754-8b8b5a65-0905-4549-8c8a-2e2d2b4020ee.png)
