### ISSUE TITLE
Removing reader studies requires a lot of button clicks

### ISSUE THREAD

**Issue by chrisvanrun** [comic/grand-challenge.org#2864]
Removing a reader-study requires a lof button clicks:

<img width="33%" src="https://github.com/comic/grand-challenge.org/assets/7871310/7c23d017-063b-4ae9-9086-fba3efa20663" />

Perhaps the check should be simplified to:
- Deleting all objects automatically except when:
  - there are any answers since these are unique results from a reader study, then just straight up deny removal
- Before doing so do a deep-processing confirmation (by copying the reader-study name copy) before actually removing the reader study

Since removal isn't commonly done, this would have a low priority.

**Comment by jmsmkn** [comment]
This is intentional, we had complains that delete was too easy, and that delete really meant delete. Data was lost so now we make it obtuse so users are really sure they know what they're doing.
