### ISSUE TITLE
Unclear where to see the Archive Item or Image UUID

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#2869]
Users have trouble setting up their archive and often need to remove images and/or archive items. Finding the correct UUID is often difficult. They should be more obvious on the archive pages, possibly an Archive Item detail view is also needed.

**Comment by chrisvanrun** [comment]
Same holds for reader studies / display sets. Can't even copy the uid from the overview because the CSS doesn't allow for that. Rather you need to go into the HTML itself to copy it.

**Comment by chrisvanrun** [comment]
We could be inspired by the way GitHub goes about it by adding a nice way to copy it, but that would require some JS magic so maybe plain text is safer:
![image](https://github.com/comic/grand-challenge.org/assets/7871310/69588953-f04d-4e93-a030-cff0b85b1aab)

**Comment by pkcakeout** [comment]
Not quite sure if we are tagging on too much stuff now, but I also found a problem:

![image](https://github.com/comic/grand-challenge.org/assets/11632379/5eb661c8-570f-4aa5-b3b6-5ec51eb608ac)

If you want to cherry-pick a single item, to add to a reader-study, it is a lot of work! It always is a click-party _or_ you need to hold backspace until all images are deleted.

I think this page would better be served by a checkmark + list view. That allows one to use `Ctrl+F` to find an item and then click the single item. Add a select all/invert selection/deselect all button, and it would be awesome, I think. I am daring to copy paste an example from wordpress here, which I think better when it comes to this feature:

![image](https://github.com/comic/grand-challenge.org/assets/11632379/0b0b4d2b-953e-4b68-8128-61f252a9dcb6)

(that comes from my wordpress plugin, but I think this is a great design for this function. (notice the search-users field in the top right as well!)

**Comment by pkcakeout** [comment]
Ok, nvm then! I hid my post to reduce noise!
