### ISSUE TITLE
Datatables.js broken for Algorithm/Archive permission requests

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#2892]
See errors in JS console on the permission request list pages.

**Comment by james-milburn-crowe** [comment]
related to this - https://stackoverflow.com/questions/28454203/jquery-datatables-cannot-read-property-adatasort-of-undefined

Error vanishes if you set order to 7 in 
``` $(document).ready(function () {
    $('#usersTable').DataTable({
        order: [[8, "asc"], [0, "desc"]], ```

in permission_request_displaytable.mjs

looks like we have 8 columns, and an off-by one error
