### ISSUE TITLE
Add anchors to section titles in Documentation

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#2895]
It would be nice to link to specific sections of the docs.

**Comment by chrisvanrun** [comment]
Would it be possible to create them in the rendering, and add them to header tags by default? Adding <a id=...> is cumbersome and actually doesn't work quite as nicely since you can't get it to align perfectly with the headers.

**Comment by chrisvanrun** [comment]
Suggestion we should use the permalink option in the markdown extension toc:
https://python-markdown.github.io/extensions/toc/

Quick test shows:
```Python
>>> markdown.markdown("### A Title", extensions=[TocExtension(permalink=True)])
'<h3 id="a-title">A Title<a class="headerlink" href="#a-title" title="Permanent link">&para;</a></h3>'
```

**Comment by jmsmkn** [comment]
Yes that looks like exactly what we need.
