### ISSUE TITLE
Clear old question types *_LINE_TEXT

### ISSUE THREAD

**Issue by chrisvanrun** [comic/grand-challenge.org#2907]
With the introduction of:
- https://github.com/DIAGNijmegen/rse-roadmap/issues/165

Some old question types can/should be removed once CIRRUS `v2023.06.x ` is the previous release.

A two-staged approach should happen:

## 1. Remove from options and (manually migrate)
- [x] Ensure `AnswerType.SINGLE_LINE_TEXT` and `AnswerType.MULTI_LINE_TEXT` are no longer selectable options in **production**.
- [x] Ensure users get an error when saving, suggesting AnswerType.TEXT as an alternative.

 Migrate data manually via the following commands.
- [x] `Question.objects.filter(answer_type=Question.AnswerType.SINGLE_LINE_TEXT).update(answer_type=Question.AnswerType.TEXT, widget=QuestionWidgetKindChoices.TEXT_INPUT)`
- [x] `Question.objects.filter(answer_type=Question.AnswerType.MULTI_LINE_TEXT).update(answer_type=Question.AnswerType.TEXT, widget=QuestionWidgetKindChoices.TEXT_AREA)`
- [x] `Question.objects.filter(answer_type=Question.AnswerType.MULTIPLE_CHOICE_DROPDOWN).update(answer_type=Question.AnswerType.MULTIPLE_CHOICE, widget=QuestionWidgetKindChoices.SELECT_MULTIPLE)`

##  2. Remove model members
- [x]  Remove `AnswerType.SINGLE_LINE_TEXT` and `AnswerType.MULTI_LINE_TEXT` and all references to them from the models.
- [x]  Rename `'Number input'` serialisation for `QuestionWidgetKindChoices.NUMBER_INPUT` to `'Number Input'` (Note capitalization of the 'i'). CIRRUS supports both 'input' and 'Input' but the latter is in common style.
- ~Make `QuestionWidgetKindChoices.NUMBER_INPUT" the default for `NUMBER`~
- ~Make `QuestionWidgetKindChoices.CHECKBOX_SELECT_MULTIPLE` the default for `MULTIPLE_CHOICE`~
- [x]  Make `QuestionWidgetKindChoices.RADIO_SELECT` the default for `CHOICE`

**Comment by chrisvanrun** [comment]
Quick note, reading the pitch I am reminded that the above instructions should also include something for:
* Deprecating `multiple choice dropdown` (and migrate to `multiple choice` + `select` widget)
* Making radio buttons default for choice

**Comment by chrisvanrun** [comment]
Because of support issues `v2023.06.x ` hasn't been made the previous release this cycle.

**Comment by jmsmkn** [comment]
@chrisvanrun can this be done now?

**Comment by jmsmkn** [comment]
>  Make QuestionWidgetKindChoices.NUMBER_INPUT" the default for NUMBER`
 Make QuestionWidgetKindChoices.CHECKBOX_SELECT_MULTIPLE the default for MULTIPLE_CHOICE

These currently allow an empty choice ("---") for the widget which is always the default. Do we want to force a choice of widget here?

**Comment by chrisvanrun** [comment]
CIRRUS has defaults for the widgets, so it is not presently required:

https://github.com/DIAGNijmegen/rse-cirrus-core/blob/e057461fde48470254adff7d6f396c9d369ebb6f/src/cirrus/DIAG/CIRRUSCore/WebDevelopment/src/components/QuestionWidgets/index.js#L14-L23

 Albeit it'll be cleaner to 'always have a widget selected'.

**Comment by jmsmkn** [comment]
Okay, I see that as a separate issue from removing the `_TEXT` options, so I will not enforce widget selection for those types.

**Comment by jmsmkn** [comment]
> Question.objects.filter(answer_type=Question.AnswerType.MULTIPLE_CHOICE_DROPDOWN).update(answer_type=Question.AnswerType.MULTIPLE_CHOICE, widget=QuestionWidgetKindChoices.SELECT_MULTIPLE)

Is multiple choice dropdown also deprecated?
