### ISSUE TITLE
Invalid output messages too cryptic

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#2912]
If an algorithm produces a segmentation or json object that fails validation the user just gets told that it is invalid, but not why or how to go about fixing it.

**Comment by jmsmkn** [comment]
@amickan please could you tackle this? Some users are having problems with invalid tiff files being produced for a challenge.

**Comment by amickan** [comment]
I think the least we can do here is add the validation error messages to the job's error messages. I'll create a PR for that. 

If image import fails (i.e. panimg can't read the created file), I'm less sure if we want to dump the entire file error dictionary that panimg outputs into the error message - quite a lot of unnecessary information and it would be difficult to format nicely on the job detail page. If we do want that information, I think we might want to add a new json field `error_details` to the job model that can optionally contain the import errors.
