### ISSUE TITLE
Generating predictions.json without making a submission

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#2917]
Challenge editors are finding it difficult to write evaluation code without predictions.json, and the current workflow of generating one is cumbersome.

**Comment by chrisvanrun** [comment]
Would a button that creates a 'fake' submission be interesting?

**Comment by jmsmkn** [comment]
Actually not sure if this belongs here or in the CLI. With the CLI you could generate a complete fake submission including all of the outputs (files or images).
