### ISSUE TITLE
Schema of json files from algorithm upload page is unclear

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#2919]
As an algorithm creator, what should these json files look like?

<img width="1039" alt="Screenshot 2023-07-06 at 10 47 00" src="https://github.com/comic/grand-challenge.org/assets/12661555/e3cf5b5d-bd2c-4ce6-87b5-221a2b90c035">

**Comment by chrisvanrun** [comment]
We could add maybe an example field (JSON) to the component interface, check it with the schema itself, and if present+valid show it as a downloadable link in above overview?

**Comment by jmsmkn** [comment]
Yes good idea I think, would help with dummy submissions too.

**Comment by ammar257ammar** [comment]
I am willing to work on this issue, but since it is open for more than a year, I want to check if the implementation suggestion is still the best way to do it now. So, add a new field to the model (JSON example) and validate on model.save() with make appropriate changes to forms, templates, tests ..etc
Am I correct?

**Comment by jmsmkn** [comment]
Yes, that is still the way to do it.

1. Add the new field (`example_value`) with validation. No forms or views should need to be updated for this as the only changes to interfaces happens in the Django admin. The validation should be done on the model ([see the Django docs about how to do this](https://docs.djangoproject.com/en/5.0/ref/models/instances/#validating-objects)). As this affects more than one field on the model (the example and the schema) it should be done in `clean`. It should follow exactly the same validation path as an `InterfaceValue` does, so should be a straightforward call to that.
3. The algorithm detail and interface list views should then be updated to display the example value.

**Comment by ammar257ammar** [comment]
> 2\. The algorithm detail and interface list views should then be updated to display the example value.

To my understanding, the instructions in input/ouput json files appear in the container upload view (AlgorithmImageCreate) and not algorithm details. Is that what is implied by the point "The algorithm detail" view should be updated?

**Comment by ammar257ammar** [comment]
This is a draft example of how it may look like to output the example_value in the view to "Create An Algorithm Container Image"

![Screenshot 2024-08-05 at 10 39 43](https://github.com/user-attachments/assets/e90b8118-cb81-4618-83e5-7ff68f280b9a)

I see James, it is better to be moved to the interface list. But then it is better to output the actual value in the table or make a downloadable link to the example. Also, I was exploring what would be the best way to download the example. It can be encoded as base64 and then use data href to make it downloadable (a JavaScript function can be created for that, but also a template filter to use the b64encode function). What do you think?

Example of downloadable link with text date:

`<a href="data:application/octet-stream;charset=utf-16le;base64,//5mAG8AbwAgAGIAYQByAAoA">Download</a>`

**Comment by ammar257ammar** [comment]
> It might be too much information there. Most important place is the interface list, probably cleaner to link to that.

I agree, I just put a screenshot of what I have now on the container upload page since I already have it and want to ask further questions about it.
