### ISSUE TITLE
Cannot Delete Display Sets

### ISSUE THREAD

**Issue by chrisvanrun** [comic/grand-challenge.org#2921]
![MicrosoftTeams-image (7)](https://github.com/comic/grand-challenge.org/assets/7871310/cdee1219-af7d-4c4d-9c02-873a34e3034e)

Likely this is because of the new strict in-line JS prevention.

**Comment by jmsmkn** [comment]
That code was moved to a JS module in #2891, I guess that method needs to be included in the global scope.
