### ISSUE TITLE
Form to turn phase into algorithm phase

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#2942]
Automatic creation of phases was removed in #2941 due to problems with validation, and they would all be called "challenge". The setup for an algorithm phase is quite involved. This can all be automated with a form that collects:

- The source phase
- The input and output interfaces

It would then automatically create the archive, add the challenge editors to that archive, set the phases submission type, verification status and interfaces.

**Comment by jmsmkn** [comment]
I don't know if an admin action is sufficient, a new form view may be better as then you could collect:

- Multiple Phases (MultipleChoiceField)
- Multiple Input interfaces (MultipleChoiceField)
- Multiple Output interfaces (MultipleChoiceField)

Then you can set up multiple phases that have the same IO at the same time e.g. for a test and validation task. I don't think this is possible with an admin action. Admin action would be quicker though.

If you do go down this route a new global permission on the Phase object would be enough.

**Comment by amickan** [comment]
We would also want to automatically create and link the challenge archives. If an archive with the phase name exists, the updating should fail. 

Similarly, do we want to allow submitting the form multiple times with possibly different settings, or do we say that once a phase is configured as an algorithm phase (ie has inputs, outputs and an archive attached), we don't allow redefining those? I would say the latter.

**Comment by jmsmkn** [comment]
> If an archive with the phase name exists, the updating should fail.

You can have archives with the same name, the slugs need to be unique though. You do not want to reveal information about other archives that exist that have a certain name.

> we don't allow redefining 

This, it is a one-time action for prediction submission phases. Then if you want to update settings it is done in the usual way.
