### ISSUE TITLE
Clicking on header links in documentation opens up a new tab

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#3003]
The link should open in the same tab.

E.g. https://grand-challenge.org/documentation/gc-api-for-archives/ then click on a header

**Comment by jmsmkn** [comment]
Huh, I cannot seem to reproduce this...

**Comment by chrisvanrun** [comment]
Strongly suspect this was caused by the md2html fix in this PR:
- https://github.com/comic/grand-challenge.org/pull/3031

**Comment by jmsmkn** [comment]
Definitely! This would have been near impossible to find. I wonder if there is something in Django that can monitor settings to ensure that they're unchanged after being initially set.
