### ISSUE TITLE
Cannot create new Archive Items from non-image files via the web iterface 

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#3008]
Must use the API if you have say mp4 only input.

**Comment by jmsmkn** [comment]
@miriam-groeneveld any preference?

**Comment by jmsmkn** [comment]
Also related is #2869 which could be solved at the same time.

**Comment by amickan** [comment]
We could also go for an inbetween solution: keep the cards, but do display set updating in a seperate view. In any case, it should be the same for archive items and display sets.

**Comment by miriam-groeneveld** [comment]
Table sounds good to me too.
