### ISSUE TITLE
Indicate which phase submission pages and leaderboards are not public

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#3020]
Sometimes hard to find.

**Comment by amickan** [comment]
Yes, this is for admins. Participants can only see public phases, so they don't need this extra bit of information. 
I like the proposal you made, adding the eye symbols to the phase settings. I think just the symbol (with a tooltip, showing Public/Not public on hover) would be enough so as to not overcrowd the tab. It might also be good to add that information to the leaderboard detail and submission detail pages.

**Comment by ammar257ammar** [comment]
Thanks for the clarification Anne.

I implemented the same logic for submissions and leaderboards where the non-public ones can be seen without accessing details like this:

![Screenshot 2024-07-29 at 14 59 23](https://github.com/user-attachments/assets/5e151992-be53-40b6-a1e6-60e0677407e8)

![Screenshot 2024-07-29 at 14 59 28](https://github.com/user-attachments/assets/306039fc-eb20-4e04-8957-6e1badebcc64)

What do you think?

**Comment by amickan** [comment]
Looks great (I assume the tabs are still clickable, right?!

**Comment by ammar257ammar** [comment]
Ah, actually not. But now I think about it, they should, since this is the admin anyway.

**Comment by amickan** [comment]
Yes, the phase settings should remain accessible and the submit page and the leaderboard page as well, even though it is only for admins.
