### ISSUE TITLE
Users confused by responsive wide table information hiding

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#3028]
It's behind the blue cross. Both leaderboard and admin panels. Maybe limit wide tables to 10 rows and then use just the bootstrap responsive. Also allow word breaks?

**Comment by miriam-groeneveld** [comment]
Why not increase the max width of the container to for example 1400 px?

**Comment by jmsmkn** [comment]
That just kicks the can down the road. We have plenty of tables that do not fit into 1400px and not all users have viewports that wide (e.g. mobile, tablets, using windows side-by-side). It needs a fundamental fix. Maybe something like https://github.com/Amphiluke/floating-scroll.

**Comment by jmsmkn** [comment]
You also loose the ability to sort on the hidden columns if they end up in the fold, e.g. for visibility here 
![Screenshot 2024-06-21 at 11 28 04](https://github.com/comic/grand-challenge.org/assets/12661555/8a087a11-c84a-4972-9e48-aaf227400dbd)

**Comment by pkcakeout** [comment]
I feel the need to comment with these pictures to comment on "kick the can down the road" comment:

![image](https://github.com/comic/grand-challenge.org/assets/11632379/c1c4eabb-5f04-4b5c-a02b-de66198f1156)

vs

![image](https://github.com/comic/grand-challenge.org/assets/11632379/4ba28e27-91c6-4de4-a518-2743fdf0bbdc)

From what I heard/read about design, data tables designs between mobile vs desktop layouts and interactions are _squarely opposed to each other_. So this is not a trivial thing to solve at all. Sort of this: On mobile phones the general advise goes against using data tables at all while on Desktop, Excel is still the king of all applications for many users.

**Comment by chrisvanrun** [comment]
Implemented this in: 

- https://github.com/comic/grand-challenge.org/pull/3516

Using handy-scroll. However, it's ramifications are to large to be tested/reviewed in a cooldown week.
