### ISSUE TITLE
Unclear how to view own challenge request

### ISSUE THREAD

**Issue by chrisvanrun** [comic/grand-challenge.org#3060]
As far as I can tell it is currently not possible to review your own challenge request.

## Current
Current workflow, as a potential challenge organizer:
- Click 'Host your own Challenge'
- Answer all fields
- Hit Save
- Get dropped at the challenge list page

## Suggestion

Twofold: 
1. add a 'my challenge requests' button that allows a user to see all created requests by the user. Make sure to include the state in the overview.
2. add a configurable URL redirect after the save, and configure it in production to the 'https://grand-challenge.org/documentation/create-your-own-challenge/#from-challenge-request-to-challenge-launch'. Update the docs slightly to make it a nicer redirect land.
3. Update the sent email to include a link to the created request.

**Comment by amickan** [comment]
Why do you want this special configurable URL after save instead of just redirecting to the "my challenge requests" overview?

**Comment by jmsmkn** [comment]
> Why do you want this special configurable URL after save instead of just redirecting to the "my challenge requests" overview?

I think this is good.

**Comment by amickan** [comment]
For now, I'm planning on only adding a list view without a link to the detail view of the request. 

For the latter, we'd need to introduce object-level permissions for the requests, rather than the global permission we currently use, and then we'd need to introduce a reviewer's group to grant the view and change permission to upon creation of a new request, if I'm not mistaken since I don't think we would want to mix object and global permissions, am I right?

**Comment by jmsmkn** [comment]
Object permissions are not that much work to add. I did it the other day for the challenge model (#3082). Workflow is:

- Add the 2 object permissions tables if they don't exist (https://github.com/comic/grand-challenge.org/pull/3082/files#diff-8c0effdb6a1ca968ff90f59f887c6dfb8dd252e63d9386dbddcb18f8eb9db02bR730-R735)
- Add a method that adds the permissions (https://github.com/comic/grand-challenge.org/pull/3082/files#diff-8c0effdb6a1ca968ff90f59f887c6dfb8dd252e63d9386dbddcb18f8eb9db02bR447-R463)
- Update the save method to call that new method (https://github.com/comic/grand-challenge.org/pull/3082/files#diff-8c0effdb6a1ca968ff90f59f887c6dfb8dd252e63d9386dbddcb18f8eb9db02bR427)
- Add tests :-)

For a static group you can create that automatically and then assign the permission too storing the name in the settings. Look at the registered users group.

**Comment by amickan** [comment]
Ok, clear, and for consitency, I should also update all other request-related views to use objects permissions instead of global permissions, right?

**Comment by jmsmkn** [comment]
> I should also update all other request-related views to use objects permissions instead of global permissions, right? 

Yes, go for object based permissions

> And we will need a management command to retrospectively grant permission to the new reviewer group to all existing requests.

That should be:

```
for request in Request.objects.all():
  request.assign_permissions()
```

Doesn't even need to be a management command, can run it manually.

**Comment by chrisvanrun** [comment]
> Why do you want this special configurable URL after save instead of just redirecting to the "my challenge requests" overview?

I thought it'd be nice to redirect requestees to something that shows the progress of the request (or at least the steps involved and where they are at). We could 'hard-code' these steps but we already have them in the docs. Hence I thought: why not just get them there?

MVP does not involve this though. Just get it viewable.
