### ISSUE TITLE
Visible submission statistics 

### ISSUE THREAD

**Issue by chrisvanrun** [comic/grand-challenge.org#3066]
At MICCAI I've had reports of challenge hosts finding it difficult to get an overview of the number of submissions / failed submissions about the limits that are in place. It was also unclear if failed submissions count towards the total number of submissions allowed.

Not sure if it is valid: are these items visible to them in any way?

**Comment by jmsmkn** [comment]
This is no longer valid as we limit challenges by compute costs and budget rather than submissions.

**Comment by chrisvanrun** [comment]
Are the compute costs and budget visible for the participants?

**Comment by jmsmkn** [comment]
No but they get a warning when they're approaching the limits.
