### ISSUE TITLE
Updating publications fails when an arxiv paper gets published, and the DOI was already added elsewhere

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#3077]
We can get the situation where:

- User adds an arxiv paper (A) and links it to objects
- The arxiv paper is published, gets a DOI, and an(other) user adds the new publication (B) with that new DOI
- When we run the periodic task to update the publications arxiv tells us there's a new DOI, so we update publication A with the new DOI, but we cannot save publication A as the DOI already exists

We need a way to update publication B with all of the links to the objects (challenges, algorithms, etc) in our database from publication A (including handling any new ones where we may introduce an object -> publication relationship) and then deleting publication A.

**Comment by jmsmkn** [comment]
The nightly periodic task fails consistently with this so the error should be easy to find.

**Comment by pkcakeout** [comment]
I also know that it is also possible on, for example, zenodo to request a DOI for a code-publication that actually was not published yet. So updating seems to be a hard requirement, indeed!

**Comment by jmsmkn** [comment]
Yes we anyway update the metadata for each publication each night, it's only the ID merging that needs to happen here.
