### ISSUE TITLE
Add a markdown extension to embed youtube videos 

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#3094]
Use www.youtube-nocookie.com, requires iframes.

**Comment by chrisvanrun** [comment]
Quick example: https://blog.bhanuteja.dev/embed-you-tube-videos-into-your-markdown-editor

Scoping the Markdown extension parsing to `<video>` with `src=` that matches a youtube URL that includes `/watch` or `/embed` is likely safe enough.

The alternative is matching a youtube URL on a singular line (with an empty line above and below) to make it even more intuitive. But that might make it a bit unsafe.

**Comment by jmsmkn** [comment]
I think it would be nicer to use the image selector, so a user would write `![alt text](https://youtu.be/dWx7GlG3whM?feature=shared)`.

**Comment by jmsmkn** [comment]
Looking at some markdown demos (https://www.digitalocean.com/community/markdown) this is the selector from Digital Ocean:

```
Embedding a YouTube video (id, height, width):

[youtube iom_nhYQIYk 225 400]

_Both the width and height are optional, with the defaults being 480 and 270 respectively._\
_The width/height set are treated as maximums -- the video will scale down to fit the available space, maintaining the aspect ratio._
```

I think width and height are unnecessary.

**Comment by jmsmkn** [comment]
If you set `sandbox` and add the correct domain to `CSP_FRAME_SRC` you should be good. If `sandbox` is insufficient then only allow exactly what is needed. Check the existing usage in the products blog post.

**Comment by chrisvanrun** [comment]
> If you set `sandbox` and add the correct domain to `CSP_FRAME_SRC` you should be good. If `sandbox` is insufficient then only allow exactly what is needed. Check the existing usage in the products blog post.

Adding `sandbox` is a good additional security! I didn't know of its existence. We are allow-listing the addition of an `<iframe>` it can also be defined as HTML in the markdown itself:

```HTML
<iframe src="evilcorp.com" allow="clipboard-read"></iframe>
```

The `CSP_FRAME_SRC` _should_ block this during runtime.  I would argue it is even better to keep it from entering HTML in the first place.

**Comment by jmsmkn** [comment]
That should be removed by `bleach` right? `iframe` is not in the list of allowed elements.

**Comment by chrisvanrun** [comment]
> That should be removed by `bleach` right? `iframe` is not in the list of allowed elements.

They should, but we'll allow `<iframe>`s for page-like entries such as reader-studies introductions and information from host challenges. We need to or else we can't embed youtube since it is markdown->HTML->bleach. As such, they 'could' add an `<iframe>` with a malicious `src`. Only relying on the CSP to block it feel thin.

I have a PR nearly ready. Filtering on src isn't very complex.

**Comment by jmsmkn** [comment]
CSP is designed to handle that situation so you shouldn't implement anything for it! However, we have the larger problem that it is report only right now. So this should be parked until we can set the CSP away from report only.

**Comment by chrisvanrun** [comment]
> CSP is designed to handle that situation so you shouldn't implement anything for it! However, we have the larger problem that it is report only right now. So this should be parked until we can set the CSP away from report only.

Good point! I forgot that we had CSP on the report modus only now.

**Comment by jmsmkn** [comment]
Done in #3100
