### ISSUE TITLE
Validation errors on upload content should return a 4xx

### ISSUE THREAD

**Issue by chrisvanrun** [comic/grand-challenge.org#3138]
Was working on testing an upload script and got back the following:

<img width="1088" alt="image" src="https://github.com/comic/grand-challenge.org/assets/7871310/fa039f1d-ad38-4414-947a-7325b005dbe5">

IMHO a client-side error is more appropriate here: for instance [415 Unsupported Media Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415)

**Comment by jmsmkn** [comment]
Err, 500 error means that you broke it and there will be an unhandled exception, probably this (https://grand-challenge.sentry.io/issues/4725383151/?project=303639&query=%21logger%3Acsp+is%3Aunresolved&referrer=issue-stream&statsPeriod=30d&stream_index=1)? There are other similar ones there. Can you provide a test in GC to reproduce?

**Comment by jmsmkn** [comment]
The problem is likely that the validation error is raised in the incorrect place, is then unhandled. A test would reveal it.

**Comment by chrisvanrun** [comment]
Possibly sidely related to:
- #3139

**Comment by amickan** [comment]
Yes, common issue. For display sets, this is solved by doing validation for file type interfaces in an async task in an atomic block. If validation fails, we send a notification to the user with the error message and the CIV does not get created. For archives items and algorithm jobs, we do the validation synchronously, but don't catch the validation error appropriately. 

One way of validating files would be good. As such I think this ties in with https://github.com/DIAGNijmegen/rse-roadmap/issues/274  

I'm now wondering if doing this asynchronously is really necessary. It would arguably be more user friendly if we validate the file contents against any possible json schema synchronously and return the error to the user in the form. That should be fast enough to do synchronously. For non json files we don't validate anything (except for checking wether the upload is complete), so no need for an asynch task for this either. Am I missing something?

**Comment by jmsmkn** [comment]
It needs to be async for multi-X JSON files as you can have things with millions of entries, you could DOS the API layer with that if it were in place. Same for things in values as we allow large inputs at the HTTP layer.
