### ISSUE TITLE
Validation errors on job creation are not handled

### ISSUE THREAD

**Issue by amickan** [comic/grand-challenge.org#3139]
https://grand-challenge.sentry.io/issues/4667838707/?project=303639&query=%21logger%3Acsp+is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0

**Comment by jmsmkn** [comment]
We are seeing this a lot, important to fix.

**Comment by amickan** [comment]
PR to fix this for archive items is about ready, but for algorithm jobs I was hoping to get the open PR from before Christmas merged first because it is contingent on it. I can also make a quick fix if necessary in the meantime, but it won't use the same code as display sets and archive items (yet).

**Comment by jmsmkn** [comment]
OK, no need to do something separate, I'll review #3125 as soon as I can.

**Comment by jmsmkn** [comment]
I have a big PR that touches on algorithm job creation right now, so best to hold off a few days on a fix for this.

**Comment by amickan** [comment]
Good that say that. I was just going to start looking at this.
