### ISSUE TITLE
Missing styling on the google-login page

### ISSUE THREAD

**Issue by pkcakeout** [comic/grand-challenge.org#3141]
When using the "login with Google" option on grand-challenge.org, the intermediate page that is shown for the redirect to google is completely unstyled:

![image](https://github.com/comic/grand-challenge.org/assets/11632379/625f734f-332b-499b-ad48-cfb621b82822)

Network tab reveals that no attempt at loading any stylesheet is being made:

![image](https://github.com/comic/grand-challenge.org/assets/11632379/ac739447-b16d-4c96-aeb2-414ae1b6f037)

**Comment by jmsmkn** [comment]
Hint: many of the template names changed in https://github.com/pennersr/django-allauth/commit/ff1a6a38e14b0542a23362e650eb8d88e8edd73a#diff-9d7989b4e4a4f0901f83235eba1094e764959f7b85f7c78e2c0799527144c49c. It's not quite clear to me how to go about migrating there. The advice in the docs is to copy everything over? Doesn't seem sensible to me given future potential mass changes like this https://docs.allauth.org/en/0.59.0/common/templates.html

**Comment by chrisvanrun** [comment]
Ran into this locally on the post registration page. 

Might be related:
<img width="1363" alt="image" src="https://github.com/comic/grand-challenge.org/assets/7871310/0d19dc6f-169f-41b6-818d-01a3aebbb464">

**Comment by jmsmkn** [comment]
Following these instructions https://docs.allauth.org/en/latest/common/templates.html
