### ISSUE TITLE
Users create a secondary account for verification

### ISSUE THREAD

**Issue by chrisvanrun** [comic/grand-challenge.org#3145]
I've seen a lot of verification requests with a user set that has a secondary account with an official email.

- A user first creates an account using their regular personal email.
- Try to submit an algorithm, but realise they need to verify officially <- Likely
- They then create a secondary account with an official email and go through the verification steps.

We then end up with an odd verification (user-set has a false positive) and having to deactivate their first account.

**Comment by chrisvanrun** [comment]
Maybe adding a checkbox to make it the primary email on the verification page is the quickest solution:
<img width="1451" alt="image" src="https://github.com/comic/grand-challenge.org/assets/7871310/0c0fc4f3-2231-4a96-a040-d02400e7bd24">

Also, is there any rationale for not linking the email manage page anywhere? (i.e. https://grand-challenge.org/accounts/email/)

**Comment by chrisvanrun** [comment]
The email manage page should have it's 'Verification' replaced by 'Confirmation'.

**Comment by jmsmkn** [comment]
I don't think this is a problem. The verification page is clear about the steps to take. 

> Also, is there any rationale for not linking the email manage page anywhere?

https://github.com/DIAGNijmegen/rse-grand-challenge-admin/issues/220
