### ISSUE TITLE
Make number of GPU hours and data stored clear on budget request page

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#3149]
I have heard that users are often surprised by the numbers produced by the budget request. We should make clear the number of on-demand GPU hours and size of the data they are predicting to help them understand the numbers.

**Comment by pkcakeout** [comment]
> I have heard that users are often surprised by the numbers produced by the budget request.

Positively or negatively? I assume the latter?

**Comment by jmsmkn** [comment]
Yes, they don't really have a sense of scale of what they're predicting, so are surprised by the numbers.
