### ISSUE TITLE
Bulk delete option for display sets 

### ISSUE THREAD

**Issue by amickan** [comic/grand-challenge.org#3169]
Request from Colin through teams: https://teams.microsoft.com/l/message/19:6daf914d105b412989baaffa5b066dfa@thread.tacv2/1705501050956?tenantId=b208fe69-471e-48c4-8d87-025e9b9a157f&groupId=97a88c45-447f-4147-9e80-5e7c013f7501&parentMessageId=1705501050956&teamName=DIAG&channelName=Grand%20Challenge&createdTime=1705501050956&allowXTenantAccess=false

We allow the user to delete display sets, but don't have a bulk delete option through the UI. It would be nice to have a button to delete all display sets of a reader study. 

This should only be possible for display sets without answers.

Do we want the same for archive items? We currently don't allow deleting of archive items at all.

**Comment by jmsmkn** [comment]
> Do we want the same for archive items? We currently don't allow deleting of archive items at all.

I think we want the two things to behave in the same way, so yes.

**Comment by snorthman** [comment]
The gcapi documentation is no longer valid. https://grand-challenge.org/documentation/gc-api-for-reader-studies/ (at the bottom):

```python
display_sets = client.reader_studies.display_sets.iterate_all(
    params={"reader_study": rs["pk"]}
)
while True:
    ds = next(display_sets)
    client.reader_studies.display_sets.delete(ds["pk"])
```
example:

```python
client = gcapi.Client(token=gcapi_token)
client.reader_studies.display_sets.delete('6e1e49b8-bc36-40eb-98fe-25bc90d934a2')

httpx.HTTPStatusError: Client error '405 Method Not Allowed' for url '[https://grand-challenge.org/api/v1/reader-studies/display-sets/6e1e49b8-bc36-40eb-98fe-25bc90d934a2/'](https://grand-challenge.org/api/v1/reader-studies/display-sets/6e1e49b8-bc36-40eb-98fe-25bc90d934a2/%27)
For more information check: https://httpstatuses.com/405
```

Any alternative way to bulk delete display_sets via gcapi? @amickan

**Comment by amickan** [comment]
At the moment there is no alternative, sorry, but I'm hoping to get to this this cycle.

**Comment by chrisvanrun** [comment]
I see that the docs have also been updated. Jeej! 🥳
