### ISSUE TITLE
Signed requests from cloudfront for downloading jpg and png(?) images have content-type `binary/octet-stream`

### ISSUE THREAD

**Issue by pkcakeout** [comic/grand-challenge.org#3193]
**Describe the bug**

Accessing an uploaded jpeg like via the signed url to cloudfront (and probably a png), like:

```
https://d1u59nsmjqjziz.cloudfront.net/components/componentinterfacevalue/e1/94/1827220/aab.jpg?[signature]
```

returns a data stream, but the data-stream has content type `binary/octet-stream` and therefore cannot be displayed in an `<img>` HTML element as required for thumbnail viewing. Here the full response header dump from my CURL query:

~~~~~~~~~
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
< HTTP/2 200 
< content-type: binary/octet-stream
< content-length: 14787
< date: Tue, 23 Jan 2024 15:45:25 GMT
< last-modified: Tue, 23 Jan 2024 14:46:52 GMT
< etag: "e9e7e40fb914e382cfab3a49934eacd7"
< x-amz-server-side-encryption: AES256
< x-amz-version-id: 2..eFp2Yq.Z6Fzc8uyQZQ2Cd.2QQi6o5
< accept-ranges: bytes
< server: AmazonS3
< x-cache: Hit from cloudfront
< via: 1.1 28b2547a012b744c90796693b582d83c.cloudfront.net (CloudFront)
< x-amz-cf-pop: AMS58-P6
< x-amz-cf-id: qol3zoMYONL5k-GVr5wJ9pfc_SSSQxV40qD9pXpBhnt0kcXPxrZf6w==
< age: 9
< 

~~~~~~~~~

**To Reproduce**

Sorry, a bit sloppy here: "curl a jpg like the one I linked above"

**Expected behavior**

The content type for jpeg and png images should be set correctly

**Comment by jmsmkn** [comment]
What is the content type if you use a local instance of GC?

**Comment by chrisvanrun** [comment]
Not sure how data streams should work, but a possible fix would be to first fetch it in JS:
https://stackoverflow.com/a/37510957

**Comment by pkcakeout** [comment]
I do not know, I did not spin up one yet. The easiest recipe for creating one of those links it to upload a thumbnail component interface to an archive.

I can do that if you want! Will take me a short bit though. Need to switch context for that!

**Comment by pkcakeout** [comment]
> Not sure how data streams should work, but a possible fix would be to first fetch it in JS:
https://stackoverflow.com/a/37510957

I know, but this is quite an ugly workaround. I wrote that in the teams-chat already... I can think of many ways to workaround this issue. But I think we should not workaround it!

**Comment by jmsmkn** [comment]
No we should set the headers, but first need to work out where it is going wrong - with both local GC and the instance at grand-challenge.org, or just the instance at grand-challenge.org.

**Comment by pkcakeout** [comment]
Cross-posting from the Teams-channel: There was another issue with the thumbnails. The thumbnails now work:

![image](https://github.com/comic/grand-challenge.org/assets/11632379/c1afa0df-6c6b-4dc0-9e1a-7cdfa988cf21)

The content-type still is incorrect though. But seemingly the `<img>` tag did not care afterall.
