### ISSUE TITLE
Importing of containers exported with Docker 25.0.0 fails

### ISSUE THREAD

**Issue by pkcakeout** [comic/grand-challenge.org#3195]
**Describe the bug**

I tried to import a viewer on grand-challenge right now, and it does not work:

![image](https://github.com/comic/grand-challenge.org/assets/11632379/f3684884-a283-4cbc-9697-e35323ceeaf6)

The failed images after the green, imported one are the ones I tried to upload:

- 1&2 are builds and clean re-builds of a dev branch
- 3 is a build of the CIRRUS main branch
- 4 is a known-good downloaded image from aws codebuild

None of them are importing right now, all fail with:

~~~~~~~~~~~~
Validation Errors
    blobs/sha256/e73667bff9013e92f65a7074744cbabffd2ce629e3da19adab4.json not found at the root of the container image file. Was this created with docker save?
~~~~~~~~~~~~

I manually opened the uploaded containers and the blobs are there. The files are also importing fine into docker. So I think that this time I have an actual grand-challenge issue at hand!

**To Reproduce**

Take a known-good image from aws-code build and try to upload to a viewer on grand-challenge.

**Expected behavior**

The image imports sucessfully.

**Comment by pkcakeout** [comment]
Failures are logged here: https://grand-challenge.org/viewers/pkg-demo/

**Comment by pkcakeout** [comment]
Ok... I think I found something:

![image](https://github.com/comic/grand-challenge.org/assets/11632379/0872b90b-eb2e-44d4-a611-d4e4bfa39d14)

I suspect that docker had some sort of update and exported blob-json files do not get the `.json` suffix attached anymore with a newer docker version... trying to confirm this now!

**Comment by pkcakeout** [comment]
I think that I tracked down the code that _would_ need to update:

https://github.com/comic/grand-challenge.org/blob/7536b1e0361f0d9adf2b3afa0ecee3d9efe5c67e/app/grandchallenge/components/tasks.py#L451-L453

I now need to confirm that this is actually what needs to happen...

**Comment by pkcakeout** [comment]
I can confirm that the manifest-format itself has changed over time/recently(?):

![image](https://github.com/comic/grand-challenge.org/assets/11632379/8eaa5c8a-8ea3-427c-8bf4-ad15420002d0)

The left side shows a freshly exported image, the right-hand side shows an old, stored image...

**Comment by pkcakeout** [comment]
For references, I am using this docker version:

~~~~
paul@dingo-linux:~$ docker version 
Client: Docker Engine - Community
 Version:           25.0.0
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        e758fe5
 Built:             Thu Jan 18 17:09:49 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.0
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       615dfdf
  Built:            Thu Jan 18 17:09:49 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

~~~~

**Comment by pkcakeout** [comment]
Aaand found the related issue that was fixed in version 25.0.0:

https://github.com/moby/moby/pull/44598

**Comment by pkcakeout** [comment]
You are on it, James? I saw yout self-assignment. Then I stop my snails pace fixing adventure that I embarked on right now! :D

**Comment by jmsmkn** [comment]
Yes should be an easy enough fix. You can work around it by using an older version of Docker but we should support the new stuff too.

**Comment by pkcakeout** [comment]
> Yes should be an easy enough fix. You can work around it by using an older version of Docker but we should support the new stuff too.

Yes, big thanks! I will do some _local_ release testing CIRRUS for now then. That typically finds obvious issues as well! If really necessary, downgrading docker is no problem either!

**Comment by pkcakeout** [comment]
> Importing of containers ~built~ exported(!) with Docker 25.0.0 fails

If you `docker save` an old image, the new manifest gets written as well!

**Comment by pkcakeout** [comment]
Hey James! Big thanks for fixing!

**Comment by pkcakeout** [comment]
Quick link for issue-tracking purposes to this commit: https://github.com/comic/grand-challenge.org/commit/16047f98f90c81961a5b24a76497cbd08d4c97e2
