### ISSUE TITLE
Updating or creating new display sets and adding non-image component interface values fails silently

### ISSUE THREAD

**Issue by pkcakeout** [comic/grand-challenge.org#3199]
**Describe the bug**

When I do either of these:
- create a new display set
- edit an existing display set
- delete all display sets and recreate all of them

Non-image component interface values are silently rejected.

**To Reproduce**

1. Go to a reader study
2. Create a new display set by clicking "Add Display Set (Single)"
3. Add and image, `fixed-image` and `generic-medical-image` are the ones I tested. Upload data.
4. Add a `text-report` (and some thumbnail, and some video - if you want) and upload valid data.
5. Click "save"

After some time, the images appear as part of the new display set. But the text-report, and video, and thumbnails do not. A message informs the uploader that they should check the notifications for errors, but no notifications are generated.

**Expected behavior**

Either an error is communicated or the upload succeeds (as they did before).

**Comment by amickan** [comment]
The related sentry error: https://grand-challenge.sentry.io/issues/4912004402/?project=303639&query=%21logger%3Acsp+is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0

**Comment by pkcakeout** [comment]
I am not in tomorrow, but if you follow my recipe on https://grand-challenge.org/reader-studies/cirruscoreweb-release-specialized-views/display-sets/ it should be 100% reproducible!

**Comment by amickan** [comment]
I can replicate it, copying of the file from the uploads bucket to the civ bucket on S3 fails with a permission denied error. I don't see any changes to permissions in recent commits on our infrastructure repos, maybe @jmsmkn knows what's going on?

**Comment by jmsmkn** [comment]
The work is being done in `add_file_to_object`. What queue type does it use? Did that task recently switch queues? Do the workers for that queue have permission to do what you want?

**Comment by amickan** [comment]
Ah, yes, we switched from `2x-large` to `micro-short` and the latter queue does not have the write permissions

**Comment by jmsmkn** [comment]
Okay, the permissions for the acks-late-micro-short workers have been updated with read write permissions on the protected bucket.

**Comment by amickan** [comment]
Oh, you beat me to it

**Comment by amickan** [comment]
As for catching errors other than ValidationErrors: do we think that is necessary? If so, I think we wouldn't want to show the exact error message to the user but rather just "an unexpected error occurred" and then raise the exception again so that we see it in sentry.

**Comment by jmsmkn** [comment]
Yes, never show a random error to a user.
