### ISSUE TITLE
Unsupported upload interface type breaks later file uploads widgets

### ISSUE THREAD

**Issue by chrisvanrun** [comic/grand-challenge.org#3256]
I have a reader study with a 3d-liver-model interface (.obj kind). The following likely also extends to archive items.

We don't support uploading these via the UI.

However, when one of these interfaces is present all subsequent file upload widgets are not loaded on page: https://grand-challenge.org/reader-studies/chris-test-reader-study-the-second-coming/display-sets/create-single/

![image](https://github.com/comic/grand-challenge.org/assets/7871310/7b167978-def3-46b3-b301-ecb9cda7b24e)

I've since removed the display set with the interface to quickly do a workaround.

Not sure if this needs to be fixed or is so corner case that we can safely ignore it.

**Comment by amickan** [comment]
Looking at it quickly, I think this might have to do with the fact that the interface name starts with a number.

**Comment by amickan** [comment]
The same happens with the 2D liver contours interface, which is a json file interface, which we do support normally. I'll work on a fix next week.
