### ISSUE TITLE
Reader study admins do not have access to upload-session of mask answers.

### ISSUE THREAD

**Issue by chrisvanrun** [comic/grand-challenge.org#3268]
**Describe the bug**
Upload sessions are giving back "Not Found" when trying ViewAsUser.

This was reported by a user on Teams, but duplicated by @pkcakeout . It was first blocked by a pure CIRRUS error (incorrect UUID sent).

The `https://grand-challenge.org/api/v1/cases/upload-sessions/<UUID>/` returned:
```JSON
{
    "detail": "Not found."
}
```

GCAPI entry point that CIRRUS uses is `raw_image_upload_sessions.detail(session_pk)` (for a status check) and a query on `images.list(
                params={"origin": session_pk}
            )` for the actual images.

The first fails.
         

**To Reproduce**

Steps to reproduce the behaviour:
- you create a reader study with a mask question
- you let someone else enter an answer with a mask-question
- you try to "viewAsUser" the answers of that person
- You do not have permissions to view the upload session for the mask-answer

**Comment by jmsmkn** [comment]
Why do you need access to the upload session for that? The image is attached to the answer, right?

**Comment by chrisvanrun** [comment]
Status checking:
 https://github.com/DIAGNijmegen/rse-cirrus-core/blob/c5904b365f590ed876e60dc70e49a8e0f10cdd10/src/cirrus/DIAG/CIRRUSCore/Modules/Scripts/python/cirrus/workstations/core_web/app_logic/readerstudy/app_logic.py#L1471-L1494

**Comment by jmsmkn** [comment]
I still do not see why an admin will need access to that. `answer.image` will check the latest version of the mask that is saved.

**Comment by pkcakeout** [comment]
Ok... got it! Yes, you are right, James. It seems we mis-identified the issue. I found an answer that does  have an `upload_session_pk` but does not have a `answer_image` set.

In these cases, CIRRUS tries to inspect the `upload_session_pk` to see if it can extract the image from there and/or obtain the state of the import itself. But this does not work in the view-as-user state.

What I/we do not know: Should this happen at all? I will share the UUID of the answer on teams to not share it on this public forum.

**Comment by pkcakeout** [comment]
Thanks for closing, james!
