### ISSUE TITLE
It is no longer possible to have an image with multiple overlays defined per viewport.

### ISSUE THREAD

**Issue by miriam-groeneveld** [comic/grand-challenge.org#3271]
**Describe the bug**
It is no longer possible to have an image with multiple overlays defined per viewport.

Introduced in this pr:
https://github.com/comic/grand-challenge.org/pull/3188

**To Reproduce**
1. Go to https://grand-challenge.org/archives/cirrus-core-release-test-archive/
2. Click on 'Update Settings'
3. Click on Save (no need to make changes)
4. See error:
![image](https://github.com/comic/grand-challenge.org/assets/51329283/6c27107b-ccfc-4ec4-a218-b52cbb6942ac)

**Expected behavior**
The validation should be done on the number of interfaces of Interface Kind Image, not all image types. Having multiple segmentations or heatmaps per viewport is a supported feature in Cirrus.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jmsmkn** [comment]
That was not my understanding from the Roadmap item:

> Cirrus already ignores additional images when multiple images are added to a single viewport.

https://github.com/DIAGNijmegen/rse-roadmap/issues/282

**Comment by miriam-groeneveld** [comment]
That wasn't worded accurately then, additional CIV of kind `Image` are ignored. Multiple CIVs of kind `Segmentation` and/or `Heatmap` can be added to a single viewport.

**Comment by jmsmkn** [comment]
Okay - so the limitations are:

- There can only be at most one non-segmentation or non-heatmap
- There is no limitation on the number of segmentations or heatmaps
