### ISSUE TITLE
Cannot delete notifications

### ISSUE THREAD

**Issue by amickan** [comic/grand-challenge.org#3293]
**Describe the bug**
It is no longer possible for the user to delete their notifications. 

**To Reproduce**
1. Go to https://grand-challenge.org/notifications/
2. Select notifications
3. Click on "Delete selected"
4. Nothing happens
5. The console reveals that the CSRF token is missing

**Expected behavior**
The notifications should get deleted. The CSRF token should automatically be sent along with the ajax request. 

This used to work not too long ago. I can't readily identify what happened that broke this. Also couldn't fix it quickly. Needs some more investigation.

**Comment by chrisvanrun** [comment]
Same holds for Mark as read.
