### ISSUE TITLE
Possible to upload the same sha256 to an algorithm

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#3297]
Upload the same container to an algorithm, the second import should fail and the user pointed to activating an old image instead.

**Comment by ammar257ammar** [comment]
Just to clarify, checking for the same sha256 can happen on different levels: system-wide, user-level, algorithm-level.

Is the goal here to fail uploading the same algorithm image to a single algorithm?

**Comment by amickan** [comment]
Ammar and I discussed this in our meeting on Monday, but I think it's best to wait for James' input here before he goes off and spends development time on this. 

Given that we limit ground truth and algorithm model uploads based on their sha system-wide, I think we would want to do the same for algorithm images. We do not want this for methods though (a challenge admin should be able to upload the same exact image to multiple phases), so careful here where / how you add the check for this.

**Comment by jmsmkn** [comment]
Related to #3455

**Comment by jmsmkn** [comment]
Fixed in #3493
