### ISSUE TITLE
Mismatch in evaluation jobs when challenge admin pre-runs algorithm on cases from the phases archive

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#3302]
`create_algorithm_jobs_for_evaluation` exits successfully but the evaluation remains in the executing algorithm state. Occurs when the challenge admin uses the try out algorithm page and selects an image from the archive linked to the phase. Probably the jobs need filtering by creator?

**Comment by amickan** [comment]
I remember that we had this issue once before. I would have thought that we fixed it then... but I guess not. I will see if I can find our conversation back tomorrow.

**Comment by amickan** [comment]
Can't find anything... only that we used to filter by creator, but removed that here: https://github.com/comic/grand-challenge.org/commit/10fa528855b986914a76e0071b637c9780852a6e#diff-3de0492fca47670a7223a3218b626d8a5ae21bddebf88c6fc58499e64447eecd 
I think we just need to add that filter back.

**Comment by amickan** [comment]
I think this happened again for submission `e4d72823-3013-4c5a-a45f-7d848e107554` and evaluation `a883a7ff-052d-4593-b348-9cebb512d55e`. How do we fix this? Delete the algorithm job?

**Comment by jmsmkn** [comment]
I think that would work.

**Comment by amickan** [comment]
I'll create an admin issue for it.

**Comment by jmsmkn** [comment]
This happened again - is there a reason why we cannot add the filter back?

**Comment by amickan** [comment]
Not that I know. I don't know why it was removed in the first place.

**Comment by jmsmkn** [comment]
Me either - I removed it [in this commit](https://github.com/comic/grand-challenge.org/pull/2780/commits/42b640a720ad3a982746befa872d107a1cf125a0#diff-3de0492fca47670a7223a3218b626d8a5ae21bddebf88c6fc58499e64447eecd) which was removing batch job creation, unrelated to the evaluation. Think it must have been a mistake.

**Comment by amickan** [comment]
Let's put it back then. We will find out soon enough if there was a reason, I guess.

**Comment by amickan** [comment]
I can create a PR

**Comment by jmsmkn** [comment]
This occurred yet again.
