### ISSUE TITLE
Google logins broken with django-allauth 0.62+

### ISSUE THREAD

**Issue by pkcakeout** [comic/grand-challenge.org#3329]
# Recipe

- Open incognito window (just in case it matters)
- Navigate to grand-challenge.org
- Click Third party auth -> Google to login
 
![image](https://github.com/comic/grand-challenge.org/assets/11632379/c699412c-c522-4c78-a86b-df9ba27b66cb)

- Acknowledge that you are sent to a "third party" by clicking continue on the next page.

![image](https://github.com/comic/grand-challenge.org/assets/11632379/b361b622-4065-4fa8-ac7e-9c3ecf72b12e)

# Result

![image](https://github.com/comic/grand-challenge.org/assets/11632379/f830f3d0-b3d9-4408-a37a-9b62f82c185e)

> Unexpected Error

No login possible.

@amickan reported that no sentry errors are being recorded. I cannot login, presumably many other people cannot login either.

**Comment by jmsmkn** [comment]
I suspect this is related to the upgrade of allauth, so pinned it as a speculative fix.

**Comment by jmsmkn** [comment]
The exception appears to be:

```
24 April 2024 at 15:56 (UTC+2:00)	File "/opt/poetry/.venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix	web
24 April 2024 at 15:56 (UTC+2:00)	raise NoReverseMatch(msg)	web
24 April 2024 at 15:56 (UTC+2:00)	django.urls.exceptions.NoReverseMatch: Reverse for 'google_callback' not found. 'google_callback' is not a valid view function or pattern name.
```

**Comment by jmsmkn** [comment]
In allauth the social account dependencies were separated out in 0.62.0 (https://github.com/pennersr/django-allauth/commit/8172ea9fba7d899323ab53069afb80c31fa9f3c3) but the backwards incompatibility notice was later moved to 0.60.1 (https://github.com/pennersr/django-allauth/commit/80088ce319b03a9df79f8a9d0cf49dad7ef50dc4). So, we upgraded thinking that we didn't have to do anything.

**Comment by jmsmkn** [comment]
The upgrade still has the problem of reversing for "google_callback". This works if we use the top level provider. For some reason we have our own Gmail provider which was added in #1713 and modified in #1715. Not sure why, we only modify the uid.

**Comment by jmsmkn** [comment]
`"gmail_callback"` can be found, I will need to do some more digging tomorrow.

**Comment by pkcakeout** [comment]
Cool... thanks for digging this up... probably not the easiest to debug given that we have no sentry and it requires google<->client communication via domain names...

**Comment by jmsmkn** [comment]
Following instructions:

- https://docs.allauth.org/en/latest/socialaccount/providers/google.html
- https://developers.google.com/identity/protocols/oauth2

To create developer credentials. Downside is that Google does not allow using gc.localhost as the authorised domain, so have to get this working on 127.0.0.1.

**Comment by jmsmkn** [comment]
Okay, found the problem, it was due to a refactoring in allauth.
