### ISSUE TITLE
Allow scheduling jobs with existing CIVs through API

### ISSUE THREAD

**Issue by amickan** [comic/grand-challenge.org#3368]
At the moment, when scheduling a job through the API, new CIVs are created for all inputs, even if an existing image is provided as input. The behavior when scheduling a job should match what we do on the "Try out algorithm" page, where we reuse CIVs when possible. 

This relates to https://github.com/comic/grand-challenge.org/issues/3139 - both require a heavy refactoring of civ creation and validation around algorithm jobs.

**Comment by amickan** [comment]
I might give this a try this week, although it is a short week with DIAG day on Wednesday and the AWS workshop on Thursday, so might not get to making a PR.

**Comment by jmsmkn** [comment]
Yes I will do it.

**Comment by amickan** [comment]
Closing this in favour of: https://github.com/comic/grand-challenge.org/issues/3576 which is a more concise description of what is still missing for the API views.
