### ISSUE TITLE
Submission unfindable

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#3374]
> I accidentally submitted that algorithm before I uploaded the evaluation container, and now it’s stuck as a “ghost submission”. It doesn’t show up as a submission anywhere, but I also cannot submit it again.

The submission is visible on `/evaluation/submissions/`, but the admin does not have a way of getting to the submission detail page. The title "Submissions and Evaluations" of `/evaluation/<slug>/admin/` is misleading, as it's only the evaluations. Why is admin also in the url?

**Comment by amickan** [comment]
How is it even possible to submit if there is no method container yet?

**Comment by amickan** [comment]
Ah, it's possible! Maybe we should add a check for that to othe submission form

**Comment by jmsmkn** [comment]
Definitely!
