### ISSUE TITLE
Question choice options do not get stored on initial save

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#3403]
To reproduce:

- Create a reader study
- Add a question, set the type to Choice, Add an option
- Click save
- Click on edit question, notice that the options are gone. Adding them here works.

**Comment by jmsmkn** [comment]
I've had a look at this and the implementation of the dynamic choice fields was a mess. Doing all sorts of validation and redirection in `form_valid`. I've refactored this to do everything in its correct place on the form, and to use standard crispy forms for rendering. Trying to add back the dynamic adjustments was a massive rabbit hole.

**Comment by pkcakeout** [comment]
Hit this during today's demo for the PI-RADs project from Amsterdam UMC. Was an short unfortunate moment, but I was able to recover!

**Comment by jmsmkn** [comment]
A PR just needs to be finished up (#3421), will be done before the end of the week.
