### ISSUE TITLE
Option needed to filter algorithm images on `active` images only.

### ISSUE THREAD

**Issue by miriam-groeneveld** [comic/grand-challenge.org#3410]
**Is your feature request related to a problem? Please describe.**
It's not possible to determin which algorithm image is the `active` one when using gcapi. 

**Describe the solution you'd like**
Either a filter option or a dedicated endpoint to retrieve only active algorthm images.

**Describe alternatives you've considered**
There is no alternative besides using the UI interface of GC

**Additional context**

**Comment by jmsmkn** [comment]
Why is this needed for GCAPI?

**Comment by miriam-groeneveld** [comment]
It was a misunderstanding, indeed not needed.
