### ISSUE TITLE
Tiff files are duplicated in Archive view

### ISSUE THREAD

**Issue by miriam-groeneveld** [comic/grand-challenge.org#3412]
**Describe the bug**
See teams issue https://teams.microsoft.com/l/message/19:6daf914d105b412989baaffa5b066dfa@thread.tacv2/1720013617880?tenantId=b208fe69-471e-48c4-8d87-025e9b9a157f&groupId=97a88c45-447f-4147-9e80-5e7c013f7501&parentMessageId=1720013617880&teamName=DIAG&channelName=Grand%20Challenge&createdTime=1720013617880

Probably a matter of showing the correct filenames?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chrisvanrun** [comment]
Ah, I forgot the splitting that sometimes occurs when processing TIF files.

Adding a simple (current) suffix is good enough here. Mix in a counter if len>1.
