### ISSUE TITLE
Unique together no longer valid for submissions

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#3437]
The unique_together constraint on the Submission of `unique_together = (("phase", "predictions_file", "algorithm_image"),)` is no longer valid. Valid combinations are:
    - Phase=P, preds=None, ai=A, model=None
    - Phase=P, preds=None, ai=A, model=M
    - Phase=P, preds=Pr, ai=None, model=None

I think given this adding algorithm_model to this is okay but I am not 100% sure, are there any I'm missing?

This is from a submission from Joeran who was submitting an algorithm with a model.

**Comment by amickan** [comment]
I think adding algorithm_model to this covers it. We don't want to include the creator in the unique together as that would allow multiple users to submit the exact same stuff. 

Note that the unique_together constraint doesn't check that only either a predictions file or an algorithm image is provided. That is currently checked in the form. We could add a check to the model's clean method if we really want to, but I think the form check is sufficient. What do you think?

**Comment by jmsmkn** [comment]
It's a good idea not to repeat ourselves with validators so I think most belong on the model, but then you might lost any field association with the validation error. So, up to you! As long as it's tested then it doesn't really matter.

**Comment by jmsmkn** [comment]
This was one of the first models I implemented, so didn't know back then that just doing the validation on the form would result in a lot of duplication...

**Comment by amickan** [comment]
Having form field specific errors is generally the most user friendly in my eyes, but in this case, a general error would be fine I guess. However, since there are tests for the submission form fields and since there is other more urgent stuff to do at the moment, I will only update the unique_together for now and refrain from refactoring the validation logic.

**Comment by jmsmkn** [comment]
Good prioritisation!
