### ISSUE TITLE
Potential issues with model submission

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#3438]
I think there is a potential bug in `clean_algorithm` in `SubmissionForm`. I think the assumption is that a particular image would either always be submitted in isolation, or always submitted with a model. But of course an algorithm image can be submitted with or without a model. I think if `algorithm.active_model` is `False` we should add:
 
```python
            extra_submission_filter = {
                "algorithm_model__isnull": True
            }
            extra_evaluation_filter = {
                "submission__algorithm_model__isnull": True
            }
```

to https://github.com/comic/grand-challenge.org/blob/b085188e6f13cde718cf8fe4b3b1912c9c592da7/app/grandchallenge/evaluation/forms.py#L473.
 
Then if so, I notice there is a comment warning about `set_evaluation_inputs`. I think there we also need a filter for the active model or None in two places:

https://github.com/comic/grand-challenge.org/blob/28296b2689744798e309352536f4c7005891601a/app/grandchallenge/evaluation/tasks.py#L277 

and

https://github.com/comic/grand-challenge.org/blob/28296b2689744798e309352536f4c7005891601a/app/grandchallenge/evaluation/tasks.py#L319 
 
If so, there might also be something missing from `create_algorithm_jobs`, but I'm not sure there.

**Comment by amickan** [comment]
You are right. I'm working on a PR to fix this

**Comment by amickan** [comment]
I made a PR. I also searched for other places in the code base where the model subquery might be missing or where it might be incorrectly implemented. I found a few places, which don't take the model into account yet, but which probably should:

- `public_test_case`
- `get_jobs_limit`
- `spent_credits`
- `set_credits_per_job`

Want to confirm before tackling these cases.

**Comment by amickan** [comment]
Another place that needs the addition: `filter_civs_for_algorithm`

**Comment by amickan** [comment]
I made a PR that addresses the remaining places. If I understand things correctly, `spent_credits` and `set_credits_per_job` do not need to be updated after all. In `spent_credits` we take all jobs that a user has created in a specific period, no matter for which algorithm or alg image or model.
