### ISSUE TITLE
`remove_inactive_container_images` doesn't take into account that a method can be attached to multiple phases

### ISSUE THREAD

**Issue by amickan** [comic/grand-challenge.org#3455]
**Describe the bug**
A method container image can be attached to multiple phases. When a challenge admin uploads an updated method container to one of the phases, the previous method will be deactivated and its image will be removed from the registry. If the method is still the active method for another phase, submissions to that phase will fail since the image is no longer in the registry. 

**To Reproduce**
1. Add the same method container to two challenge phases. 
2. Upload a new method container to 1 of those phases. 
3. Run `remove_inactive_container_images` (or wait a day, in production it runs at night)
4. Make a submission to the phase where you did not update the method container. 
5. Submission will fail because the corresponding method container image was removed from the registry 

**Expected behavior**
The image should not have been removed since it's still the active image for a phase.

**Comment by amickan** [comment]
This can't be replicated in development actually. And looking at the code I'm confused that this happened. We delete the `original_repo_tag` from the registry, which is unique per image object, so deactivating one method and deleting its container image should not affect other method objects and their images in the registry. Needs further investigation. It's not an issue that arises often, so not super critical.

**Comment by amickan** [comment]
Related sentry event: https://grand-challenge.sentry.io/issues/5634431220/?project=303639&query=%21logger%3Acsp+is%3Aunresolved&referrer=issue-stream&statsPeriod=7d&stream_index=1 

This is from the ACOUSLIC-AI challenge. The issue has been resolved, Sofia uploaded an updated method container to the preliminary phase. We still need to figure out what went wrong here and how to prevent it from happening in the future.

**Comment by amickan** [comment]
I learned a bit about `crane` and ECR today. To avoid redundancy, image layers and the manifest are saved only once. Tags are just a reference to the image's digest. Pushing an identical image will just add another tag associated with the already existing digest. So in the case of 1 method container being uploaded to 2 phases, ECR will contain the image digest once with 2 reference tags, one for each method object. 

When we remove inactive images, we do `crane delete <image>:<tag>@<digest>`, which is equivalent to doing `crane delete <image>@<digest>`: the tag is ignored and the digest is deleted even though there are other tags referencing it. I wonder if that is what we want? Seems to me that we would only want to remove the digest if there are no more tags referencing it, right? 

Before deleting, I think we would need to check in our database if there are other images with the same sha256 and `in_registry=True` and if so only do `crane delete <image>:<tag>`, leaving the digest in place.

**Comment by amickan** [comment]
This happened again. This time for algorithm images. A user uploaded the same container image twice to the same algorithm and then, for some reason, switched the active version back to the first of those two, which deleted the image from the registry. 

In general, maybe we should prevent uploading the same image twice, like we do for models and ground truths. 
But other than that, same fix I proposed above. I hope to get some time to implement this tomorrow. For now, the fix for the user is to upload the container once again, so not too big an issue.

**Comment by amickan** [comment]
This is becoming quite a nuisance. Sofia has the same container for both phases. She uploaded it 3 times in total, so there is one method with that image which is not an active method currently and for which the digest was deleted from the registry over night. Now uploading the container again will fix it for today, but will result in the image being deleted again next night. This really needs a fix.

**Comment by jmsmkn** [comment]
Similar to #289, likely has the same root cause from the container deletion.

**Comment by jmsmkn** [comment]
I've had a look at the PR and don't think that it's quite the right solution. We should not have to rely on the state in the GC database as that can get out of date with ECR. We also have to be careful about leaving dangling layers. I will work on this after my meetings on Monday.

**Comment by jmsmkn** [comment]
This was likely introduced in #3221
