### ISSUE TITLE
Add link to linked archive in Challenge Phase admin overview

### ISSUE THREAD

**Issue by miriam-groeneveld** [comic/grand-challenge.org#3531]
**Is your feature request related to a problem? Please describe.**
As a challenge admin, it is not obvious which archive is linked to which phase. 

**Describe the solution you'd like**
It would be convenient to have the archive title/link displayed on the Phase settings page

**Describe alternatives you've considered**

**Additional context**

**Comment by jmsmkn** [comment]
That information is available and linked to on the Create Submission page, gives the admins a lot of information already:

<img width="1116" alt="Screenshot 2024-09-10 at 11 47 03" src="https://github.com/user-attachments/assets/e926f5b9-8a3a-46a6-84a8-e8aade1368c9">

**Comment by amickan** [comment]
I think repeating this in the admin, specifically the phase settings, would be worth it though because it is quite hidden on the submission page.

**Comment by jmsmkn** [comment]
Sure - but it should only be for information which is not controlled by that form (e.g. the start date or end date) to prevent inconsistencies.

**Comment by amickan** [comment]
Yes, either in an info banner or a button "Go to archive for this phase"

**Comment by chrisvanrun** [comment]
> Yes, either in an info banner or a button "Go to archive for this phase"

"Go to input archive for this phase"*

One thing we observed in the dry run of the workshop is that "input"/"output" are good terms to use to make things clear for challenge admins and should be preferred to "interfaces".

**Comment by amickan** [comment]
Proposed fix: https://github.com/comic/grand-challenge.org/pull/3640
