### ISSUE TITLE
Phase settings validation errors obscured by warnings

### ISSUE THREAD

**Issue by chrisvanrun** [comic/grand-challenge.org#3548]
We have a potentially impressive list of warnings/errors at the head of all phase admin pages.

When changing settings, the validation errors are often missed, or miss interpreted. Binding the validation errors to the fields does not go well with the different Tabs.

The warnings are all important and should not be hidden. I like them being 'in the face' when one opens up a phase-related page. Not sure what options we have.

**Comment by chrisvanrun** [comment]
I don't think there is appetite to tackle this atm.

**Comment by jmsmkn** [comment]
I added [the unsaved form mixin](https://github.com/comic/grand-challenge.org/blame/60245529ba881f592740301a1542d66bdfba9d92/app/grandchallenge/evaluation/templates/evaluation/phase_form.html#L42-L43) so users get a popup when they try to navigate away from the page with unsaved data in #3616. So this should be solved.
