### ISSUE TITLE
Displaysets not editable when Json-kind Interface is used

### ISSUE THREAD

**Issue by miriam-groeneveld** [comic/grand-challenge.org#3565]
**Describe the bug**

**To Reproduce**
1. Go to a reader study that has a display set with a Json CIV.
2. Edit a display set that doesn't have a value for the Json CI
3. Save the display set
4. Now the displayset shows an added Json CI, but the value is null, causing a server error when trying to edit the display set.
5. See video and sentry error: https://grand-challenge.sentry.io/issues/5910158018/?project=303639&query=%21logger%3Acsp%20is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=0

**Expected behavior**
Display set should remain editable

**Screenshots**
https://github.com/user-attachments/assets/34d4a6eb-5abe-4d59-b66b-89aabf67a34f

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by amickan** [comment]
This is a general issue with the `InterfaceFormField` and how we handle/pass initial data to it. This is fixed by the refactoring done in https://github.com/comic/grand-challenge.org/pull/3465
