### ISSUE TITLE
Missmatch answer / raw session upload

### ISSUE THREAD

**Issue by chrisvanrun** [comic/grand-challenge.org#3590]
A task `add_image_to_answer` for a reader study failed because `"Upload session for an answer does not match"`.

**Comment by chrisvanrun** [comment]
Quick check. This seems a double save by a reader study participant, which was correctly resolved to have the newer one.

Another later upload + `add_image_to_answer` got JUST ahead of this upload, both task timestamped on `Oct. 7, 2024, 4:51 p.m.` 

The one linked to the actual answer correctly superseded the unlinked one.

**Comment by jmsmkn** [comment]
Indeed! System is working correctly. Probably we no longer need to get notified about that anymore.
