### ISSUE TITLE
Sagemaker backend not properly initialized(?)

### ISSUE THREAD

**Issue by chrisvanrun** [comic/grand-challenge.org#3614]
Sentry [issue](https://grand-challenge.sentry.io/issues/5977074731/?project=303639&query=%21logger%3Acsp%20is%3Aunresolved&referrer=issue-stream&statsPeriod=4d&stream_index=0): `'>=' not supported between instances of 'int' and 'NoneType'`

Offending line:
https://github.com/comic/grand-challenge.org/blob/595da02742b89110a2121bf506be746411f38c9a/app/grandchallenge/components/backends/amazon_sagemaker_base.py#L554

The initial direct route I saw is that the `COMPONENTS_MEMORY_LIMIT` env is empty, but that would not cast to int:

```Python
COMPONENTS_MEMORY_LIMIT = int(os.environ.get("COMPONENTS_MEMORY_LIMIT", "4"))
```

Not sure what is causing this.

**Comment by jmsmkn** [comment]
Doesn't matter, the task is being removed in #3601

**Comment by jmsmkn** [comment]
Issues that are specific to the instance of Grand Challenge at https://grand-challenge.org belong in https://github.com/DIAGNijmegen/rse-grand-challenge-admin/issues.
