### ISSUE TITLE
Monkey Challenge - crashing leaderboard

### ISSUE THREAD

**Issue by chrisvanrun** [comic/grand-challenge.org#3615]
When scouring the challenges to get some screenshots for a presentation I noticed:
![image](https://github.com/user-attachments/assets/4567fd95-21ce-4da9-9bc4-fbc34123551c)

The phase 'Live leaderboard Evaluation' _should_ be open.

**Comment by chrisvanrun** [comment]
nvm, temp deployment + permissions settings.

**Comment by jmsmkn** [comment]
Issues that are specific to the instance of Grand Challenge at https://grand-challenge.org belong in https://github.com/DIAGNijmegen/rse-grand-challenge-admin/issues.
