### ISSUE TITLE
If archive is part of a phase, the initial interfaces should be selected already

### ISSUE THREAD

**Issue by chrisvanrun** [comic/grand-challenge.org#3638]
This happens for existing items in the challenge. Existing interfaces are preselected. It should also work for phases.

**Comment by jmsmkn** [comment]
Users should be uploading data using the upload scripts provided from the challenge pack, not manually one by one. The things in the archive item also do not have to be consistent with each other, and an archive can be used for many phases. Like you said, once they do one, they get them filled out. I don't think the complexity this feature would add is worth it.

**Comment by chrisvanrun** [comment]
Generally, I/we tell any new challenge admin to start with the debug phases setup. Upload one or two cases using the UI, and then work with the example algorithm and example evaluation before uploading all the data. 

Not having to explain that one needs to upload the files, under UI, using a specific interface to 'label' the data is one less step on the steep learning curve.

The rough initial plan was a very simple implementation: just source the list of phase inputs of linked challenges and add them to the initial interface widget list.

Alternatively, we need to fix a bug before the workshop, where the following happens. Quick recipe:
- User A opens create Archive Item create page (Archive is empty)
- User B opens create Archive Item create page (Archive is empty)
- User A selects interface X via 'Add Interface', and submits: creating the archive item.
- User B, not having added any interface widget yet, tries to add interface X, but widget cannot be added: the server incorrectly assumes it is already present. User B needs to refresh the page to get the widget.

A workshop workaround here is adding a singular Archive Item already. @amickan

**Comment by jmsmkn** [comment]
> A workshop workaround here is adding a singular Archive Item already.

I think that's a fine way to solve this.
