### ISSUE TITLE
Users get confused by spinning status

### ISSUE THREAD

**Issue by chrisvanrun** [comic/grand-challenge.org#3639]
An observation form the case study: 'A workshop dry-run'. They seem to call it a problem on GC, and refreshing sometimes helps.

Perhaps we should remove the spinner, or actually make it auto-update?

**Comment by amickan** [comment]
Which spinner are you referring to here?

**Comment by jmsmkn** [comment]
We have a way of doing this now - make the component job status button a HTMX component. Would need the correct permissions etc. @koopmant I think this would be a nice thing for you to do for Algorithm and Evaluation tasks after you are done with the new page edit views.

**Comment by chrisvanrun** [comment]
> Which spinner are you referring to here?

Several. Non-exhaustive list on the top of my head:
- Several job states
- Container Image states

User in this case was referring to the job states.

**Comment by amickan** [comment]
That would be very nice to get before the workshop on November 7.

**Comment by jmsmkn** [comment]
We discussed splitting this into several PRs:

1. Get the existing algorithm job status buttons rendered with HTMX when the page loads/when they are visible. Add a detail view to return this from a template and ensure the permissions are tested. Check where the current badges are rendered, we think that they're an include, if not, they should be.
2. Update the button to auto-refresh if the job is in a non-final state (success, failed, cancelled)
3. Repeat the same for evaluation jobs, using the fact these are both component jobs.
4. Do 1+2 for container image imports.
5. Make the pre-requisite jobs list an auto-refreashing htmx table.

**Comment by koopmant** [comment]
I believe this is complete now. We have auto-refresh badges using the following new views:

Job status:
JobStatusDetail
EvaluationStatusDetail

Build status:
AlgorithmImageBuildStatusDetail

Import status:
AlgorithmImageImportStatusDetail
AlgorithmModelImportStatusDetail
WorkstationImageImportStatusDetail
MethodImportStatusDetail
EvaluationGroundTruthImportStatusDetail

The badges reload every 30s until in a final state. 

The pre-requisite jobs table in the evaluation detail now also automatically refreshes every 3 minutes. When there are no jobs left, the table disappears.

**Comment by jmsmkn** [comment]
Indeed, @chrisvanrun and @amickan please check that everything is working as expected ASAP.

**Comment by amickan** [comment]
I tried out uploading an algorithm image just now and running a job - status spinners update nicely! 

But I did notice on the algorithm image page that the "Inactive" badge at the top does not update. That might be a bit confusing: an import succeeds but the image still appears inactive (until you refresh the page). Could that be changed?

**Comment by amickan** [comment]
And a similar thing holds for algorithm jobs: when they fail, you'd expect to see an error message and if they succeed you'd expect to see the outputs and the view in viewer button. None of these things auto-update currently.

**Comment by amickan** [comment]
Maybe trigger a full page refresh when the status is final?

**Comment by jmsmkn** [comment]
I think that would be quite complicated - you would need to track when a full page refresh would need to be done. That would need to happen on some pages (e.g. the detail page) but not others (e.g. the list view where you would only want the row to refresh).

**Comment by jmsmkn** [comment]
I'm also not sure that a full page refresh would be the right approach as you could have a button in another tab (e.g. the containers page) but the user might have "navigated" away to the detail page, and suddenly they are being refreshed. So you would need to track which elements would need to respond. I think this leads to a very deep rabbit hole that we should not go down right now. Just refresh the page.

**Comment by amickan** [comment]
Yeah, for the list views this is indeed problematic. For the detail views, I think a full page refresh would work well. But ok, I will just keep the instructions at "make sure you refresh the page".

**Comment by miriam-groeneveld** [comment]
Nice! Is it the same issue as https://github.com/comic/grand-challenge.org/issues/2829?

**Comment by jmsmkn** [comment]
Yes! I was trying to find that yesterday. Amazing how HTMX has taken something that would have been a tremendous amount of work down to a couple hundred lines of code, fantastic library.
