### ISSUE TITLE
Large json file causes MemoryError and failing job

### ISSUE THREAD

**Issue by miriam-groeneveld** [comic/grand-challenge.org#3656]
**Describe the bug**
The algorithm that fails creates a Multiple Point annotation outputfile, with a point annotation for every detected lymphocyt. For this particular job it seems that the size of the Json file causes a MemoryError when parsing this Json file, hence failing the job.

**To Reproduce**
Rerunning the job will reproduce the error. 
Algorithm: tiger_til
Algorithm job that failed: https://grand-challenge.org/algorithms/tiger_til/jobs/243c4b7e-23f8-4f47-b32f-da78e0a9a2b3/
Sentry Error: https://grand-challenge.sentry.io/issues/5874676870/?project=303639&query=%21logger%3Acsp%20is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=0

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by amickan** [comment]
Given that the algorithm ran just fine in the past with the current image, I'm guessing this is an issue specific to the input file for this job - possibly just an insane amount of lymphocytes in the image. A temporary fix is to increase the memory of the 2xlarge worker that does the output parsing. We can then reschedule the job and revert the increase afterwards.

**Comment by pkcakeout** [comment]
Any idea "how big" that json data is? We see this pattern very often, we also had it in CIRRUS. The polygon-data that we store in CIRRUS is also very very "bloated". I do not want to make things more complicated, but I would actually be happy to discuss the introduction of a binary format for some of these list-type questions. We are leaving a lot of space on the table in general. Check this out:

```
# Size of a [1000, 3] float array, either json printed, or using memory dumps in various settings

Size of pretty printed json array: 96812 bytes
Size of densly printed json array: 62810 bytes
Size of gzipped densly printed json array: 28284 bytes
Size of base64 memory dump: 16000 bytes
Size of memory dump: 12000 bytes
Size of gzipped memory dump: 10776 bytes
```

<details>
<summary>Program source code</summary>

```
import numpy as np

import json
import base64
import gzip

array_data = np.random.rand(1000, 3).astype(np.float32)

size = len(json.dumps(array_data.tolist(), indent=4))
print(f"Size of pretty printed json array: {size} bytes")

size = len(json.dumps(array_data.tolist()))
print(f"Size of densly printed json array: {size} bytes")

size = len(gzip.compress(json.dumps(array_data.tolist()).encode()))
print(f"Size of gzipped densly printed json array: {size} bytes")

size = len(base64.b64encode(array_data.tobytes()))
print(f"Size of base64 memory dump: {size} bytes")

size = len(array_data.tobytes())
print(f"Size of memory dump: {size} bytes")

size = len(gzip.compress(array_data.tobytes()))
print(f"Size of gzipped memory dump: {size} bytes")

```
</details>

Even simple base64-encoding of the binary raw array without compression is more effective than json ever could be by a HUGE factor.
