### ISSUE TITLE
Banner ungainly large when editing pages

### ISSUE THREAD

**Issue by chrisvanrun** [comic/grand-challenge.org#3674]
Banner takes up 50% of the screen, I think the banner might need some restrictions on size:

![image](https://github.com/user-attachments/assets/c6e05f02-ba74-46a6-8dfa-190e5aa6ac9c)

**Comment by chrisvanrun** [comment]
It's a pretty neat editor now, well done @koopmant!

**Comment by jmsmkn** [comment]
The banner can be removed completely in this view.
