### ISSUE TITLE
Switching view of JSON editor fails with empty content

### ISSUE THREAD

**Issue by chrisvanrun** [comic/grand-challenge.org#3698]
**Describe the bug**

When on the try-out page of an Algorithm, the JSON editor can crash. That leads to a partially broken form where you do not have feedback on what might be missing. The form does still work if you re-fill all the values.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://grand-challenge.org/algorithms/pi-cai-pubpriv-pimed/jobs/create/
2. In the JSON editor, swap to code mode
3. Remove the null content
4. Switch back to tree
5. Try to save.

**Expected behaviour**

To have several 'is required' validation errors.

**Screenshots**

![image](https://github.com/user-attachments/assets/f896e785-22b2-4e60-9ba8-638bd689df39)

**Additional context**

![image](https://github.com/user-attachments/assets/fca18d67-a05a-48ba-927e-fa8594a65e03)

**Comment by jmsmkn** [comment]
This is the relevant bit:

<img width="469" alt="Screenshot 2024-11-14 at 11 48 51" src="https://github.com/user-attachments/assets/d0f1762a-f944-47da-96bc-994bd9d75f30">

All internal, and occurs on every instance of the json editor. The one we deploy is kindof old. Have you tried upgrading it?

**Comment by chrisvanrun** [comment]
Fyi. Quick update to `10.1.1` (now `9.5.2`) didn't address this.

**Comment by jmsmkn** [comment]
Can you replicate it in a codepen?

**Comment by chrisvanrun** [comment]
Not sure, I'll try.
