### ISSUE TITLE
Minio setup error during installation

### ISSUE THREAD

**Issue by rashindrie** [comic/grand-challenge.org#3700]
**Describe the bug**
Getting an error during minio setup when running `make runserver`

`mc: <ERROR> Unable to make user/group policy association. The specified policy change is already in effect. (Specified policy update has no net effect).
Exception while running run() in 'scripts.minio'`

**To Reproduce**
1. Run the installation steps at https://comic.github.io/grand-challenge.org/development.html 
`git clone https://github.com/comic/grand-challenge.org`
`cd grand-challenge.org`
`make runserver`
2. See error

**Expected behavior**
Expected to be able to go to https://gc.localhost/ to see the development site.

**Screenshots**
<img width="1772" alt="image" src="https://github.com/user-attachments/assets/8fe4586c-e777-4ae1-afba-3ae6886a1eac">

**Desktop (please complete the following information):**
 - OS: Mac OS M2 - Ventura 13.4
 - Browser chrome

**Additional context**
When following the i[nstallation steps](https://comic.github.io/grand-challenge.org/development.html) on MacOS, the below command was skipped and DOCKER_GID was set manually to 1000. 

`echo DOCKER_GID=`getent group docker | cut -d: -f3` > .env`

**Comment by chrisvanrun** [comment]
`minio`, our local S3 object storage for development, is quite finicky with being run multiple times. It's not very idempotent.

From the migration steps I can see that the local development instance is not starting from scratch: there would be lot more migrations happening.

You could try to:
- bring everything down with `docker-compose down`, or via the Docker application select the stack to delete the containers.
- This should also delete existing volumes, but to be sure you can selectively prune them or just prune all of ehm with `docker volume prune`

Good luck!
