### ISSUE TITLE
Development Fixtures error while installation

### ISSUE THREAD

**Issue by imnishat** [comic/grand-challenge.org#3708]
**Describe the bug**
Getting an error after minio setup successfully and while creating development fixtures.

Beginning: 🔨 Creating development fixtures 🔨 throws
Exception while running run() in 'scripts.development_fixtures'

and

  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/bin/sh', '-c', 'docker build --build-arg BUILD_TIME=2024-11-19T18:15:52.177637+00:00 --platform linux/amd64 --tag fixtures-algorithm-io:latest /app/tests/resources/gc_demo_algorithm']' returned non-zero exit status 1.
make: *** [development_fixtures] Error 1

**To Reproduce**
1. Run the installation steps at https://comic.github.io/grand-challenge.org/development.html
2. git clone https://github.com/comic/grand-challenge.org
3. cd grand-challenge.org
4. echo DOCKER_GID=`getent group docker | cut -d: -f3` > .env
5. make runserver

**Expected behavior**
Expected to be able to go to https://gc.localhost/ to see the development site

**Screenshots**
<img width="1363" alt="Screenshot 2024-11-19 at 7 47 40 PM" src="https://github.com/user-attachments/assets/787f8e42-f832-4245-ada6-17959ba422c7">

**Desktop (please complete the following information):**
 - OS: 1. Ubuntu 22.04 Jellyfish, 
           2. macOS Sonoma 14.5 (Having exactly same error)

**Additional context**
DOCKER_GID was set manually to 999. I have tried to clean the docker by the command: docker-compose down and make the server run again. But it is showing same error again and again. I am unable to find a way to solve this error. My minio is set up correctly and migration is completed successfully.

**Comment by jmsmkn** [comment]
The error message is telling you:

> subprocess.CalledProcessError: Command '['/bin/sh', '-c', 'docker build --build-arg BUILD_TIME=2024-11-19T18:15:52.177637+00:00 --platform linux/amd64 --tag fixtures-algorithm-io:latest /app/tests/resources/gc_demo_algorithm']' returned non-zero exit status 1.

That means that the following command failed:

```
docker build --build-arg BUILD_TIME=2024-11-19T18:15:52.177637+00:00 --platform linux/amd64 --tag fixtures-algorithm-io:latest /app/tests/resources/gc_demo_algorithm
```

It means that docker cannot build a container. You can see the line on which it failed (`File "/app/grandchallenge/components/backends/docker_client.py", line 32, in _run_docker_command`), you can could the error and inspect what is going wrong.

> DOCKER_GID was set manually to 999

Is that the correct docker group? Please check your docker installation.
