### ISSUE TITLE
Hanging Protocols JSON field fails to validate properly and an exception is raised

### ISSUE THREAD

**Issue by ammar257ammar** [comic/grand-challenge.org#3724]
**Describe the bug**

When creating a new hanging protocol, any value that is an array with at least an object structure inside of it will raise an exception without going through proper validation, even though a schema check is in place.
The bug was discovered while working on https://github.com/DIAGNijmegen/rse-roadmap/issues/362

**To Reproduce**
1. Go to Hanging Protocol Create form
2. Enter a title and a value in the json field `[{}] `or `[{"test":1}]` (both of them are invalid according to the schema)
3. Click save

**Expected behavior**
A redisplayed form with validation error on the json field, as in the screenshot below.

![Screenshot 2024-12-02 at 15 54 31](https://github.com/user-attachments/assets/7f68ab49-4fc4-41e4-87eb-819df6cb79d5)

**Screenshots**
However, I get the following error

![Screenshot 2024-12-02 at 15 56 08](https://github.com/user-attachments/assets/dea394cf-dcbe-4b84-84c8-6afd7f165999)

**Desktop (please complete the following information):**
 - OS: [ iOS]
 - Browser [e.g. chrome]

**Comment by ammar257ammar** [comment]
The exception raised is coming from [this field cleaning function ](https://github.com/comic/grand-challenge.org/blob/main/app/grandchallenge/hanging_protocols/forms.py#L60)

I did some tests to check the order of things.
If I comment the logic inside the function and just return the json, the validation is performed and I get a proper form redisplay with validation error, as desired.

What is happening is that the clean_json() is called before the field validation happens. That causes the exception to be raised before JSONValidator has the chance to validate the field against the schema.

The fix of the error can be done like the following:
from 
`viewport_names = [x["viewport_name"] for x in json]`
to
`viewport_names = [x["viewport_name"] for x in json if "viewport_name" in x]`

This will cause the function clean_json() to work without error and then the validation will triggered and I get back the form with validation errors

![Screenshot 2024-12-02 at 15 54 31](https://github.com/user-attachments/assets/3b6d3ce0-c91f-469f-9227-9b8463a22da2)

**Comment by ammar257ammar** [comment]
I tried to call the validation before doing the cleaning, using:
`super().clean()` 
at the start of the `clean_json`() function but that did not help, the exception is still raised.

Is the proposed solution acceptable? or the validator should be triggered before the field cleaning function is performed?

**Comment by amickan** [comment]
I thought that any field level validation has already happened before the form specific clean methods are called and that a schema-inconsistent json value would then not be part of `cleaned_data` dictionary... 
Ideally that is the order we want things to happen in, I would say. Running the extra validation on faulty json data makes no sense, right? 
Why do we allow submitting faulty json anyway? The editor catches the schema violations client-side. Can we prevent form submission until the json passes validation?

**Comment by jmsmkn** [comment]
> The editor catches the schema violations client-side. Can we prevent form submission until the json passes validation?

The server-side validation should be able to handle invalid data, for security reasons we cannot rely on client side checks.

**Comment by amickan** [comment]
Ok, then I guess Ammar's solution is the way to go. The clean_json function won't do anything the first time around, the schema error will be thrown, the user will fix it and resubmit and then the clean_jon function will run again.

**Comment by ammar257ammar** [comment]
> Ok, then I guess Ammar's solution is the way to go. The clean_json function won't do anything the first time around, the schema error will be thrown, the user will fix it and resubmit and then the clean_jon function will run again.

Indeed, that is what I intended with the fix. The clean function won't do anything if the JSON has a problem allowing the validator to raise Validation error.
