### ISSUE TITLE
Datatable default initialization issues

### ISSUE THREAD

**Issue by amickan** [comic/grand-challenge.org#3742]
I saw a few sentry errors related to DataTables defaults initialization. They all happened on the `VerificationCreateView`. I cannot reproduce them locally or in production and I have seen verification requests trickle, so I think we can probably ignore these issues, but maybe @chrisvanrun can comment?

**Comment by chrisvanrun** [comment]
Looking at the errors I don't quite see what could be going-on, the loading is consistent:

https://github.com/comic/grand-challenge.org/blob/069a6907e75a876bf603138b5b04cd697e418f9e/app/grandchallenge/core/templates/grandchallenge/partials/script.html#L11-L21

Having said that, I do notice the documentation has been updated since I implemented it and is now suggesting a slightly different call. I'll have it switch to that.

**Comment by jmsmkn** [comment]
Could it be loading stuff? `jquery.floatingscroll.min.js` is deferred on L8, the defaults are separate on L21. Maybe all three things can be compressed together?

**Comment by jmsmkn** [comment]
This also appears to be from a single user using a VPN. Feels like it could be issues with the Great Firewall so probably not worth spending much time on.

**Comment by chrisvanrun** [comment]
Another hit not an hour ago on the new construct. Likely the Great Firewall hitting things again.

**Comment by jmsmkn** [comment]
Did you try compressing everything together?

**Comment by jmsmkn** [comment]
Or does:

```
$.extend($.fn.dataTable.defaults, {
    scrollX: true,
    language: {
        paginate: {
            next: "Next",
            previous: "Previous",
        },
    },
    pagingType: "simple_numbers",
});
```

Need to be done on document ready?

**Comment by chrisvanrun** [comment]
> Did you try compressing everything together?

Sorry, I don't follow. Could you elaborate. What would be compressed?

**Comment by jmsmkn** [comment]
Compress puts everything into one js file and minimises it:

```
{# DataTables with colvis #}
{% compress js %}
    {# Floating scrollbar: floating-scroll, used by DataTables #}
    <script src="{% static 'vendored/floating-scroll/dist/jquery.floatingscroll.min.js' %}" defer></script>

    <script src="{% static 'vendored/datatables.net/js/dataTables.min.js' %}"></script>
    <script src="{% static 'vendored/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'vendored/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'vendored/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
    <script src="{% static 'vendored/datatables.net-buttons/js/buttons.colVis.min.js' %}"></script>

    {# Set global defaults for datatables #}
    <script type="module" src="{% static 'js/datatables.defaults.mjs' %}"></script>
{% endcompress %}
```
