### ISSUE TITLE
Several issues with tables update

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#3745]
The table alignments are off:

<img width="1217" alt="Screenshot 2024-12-12 at 12 48 27" src="https://github.com/user-attachments/assets/626ef5ab-6a3d-4624-a171-ce9d83804703" />

The elements are also all bunched up together, there use to be room around button groups, drop downs, search boxes, and the main table.

**Comment by jmsmkn** [comment]
This one has data that is right justified in the first column, it shouldn't be:

<img width="322" alt="Screenshot 2024-12-12 at 12 51 14" src="https://github.com/user-attachments/assets/8db8121c-efaa-49b4-ab93-ec2f63a2fde3" />

**Comment by jmsmkn** [comment]
This one has the previous/next buttons in the middle of the page:

<img width="1168" alt="Screenshot 2024-12-12 at 12 53 03" src="https://github.com/user-attachments/assets/9b85e2eb-e52c-4eeb-a16f-52c34cf17a5f" />

**Comment by jmsmkn** [comment]
The horizontal rule after the table data is not present in the non-data tables tables, the data table at the bottom should look mostly like the normal one at the top:

<img width="1134" alt="Screenshot 2024-12-12 at 12 54 56" src="https://github.com/user-attachments/assets/a168b397-b824-4e00-823e-418d3fe6122d" />

**Comment by jmsmkn** [comment]
The horizontal scroll does not appear after showing all metrics:

<img width="1232" alt="Screenshot 2024-12-12 at 12 56 58" src="https://github.com/user-attachments/assets/f3f3efc1-85ce-495a-a0c9-1591a13a0298" />

**Comment by chrisvanrun** [comment]
> The horizontal scroll does not appear after showing all metrics (tested on Safari and Firefox):

Fixed in an existing PR.

**Comment by chrisvanrun** [comment]
Looking at the rest now.

**Comment by chrisvanrun** [comment]
> This one has data that is right justified in the first column, it shouldn't be:

Which page was that?

**Comment by jmsmkn** [comment]
Verification user set.

**Comment by chrisvanrun** [comment]
Several new 'features' of Datasets are changing the looks a bit. I have a changeset ready that addresses most of them. Will double check it tomorrow and create a PR.

**Comment by jmsmkn** [comment]
The cost overview page is ordered strangely, it should be double ordered by (1) should be open, (2) most recent submission date:

<img width="1106" alt="Screenshot 2024-12-17 at 10 48 46" src="https://github.com/user-attachments/assets/3f561c2a-0a70-42c5-a30c-f798f88fa188" />
