### ISSUE TITLE
Challenge request clarification questions show up when they should not

### ISSUE THREAD

**Issue by amickan** [comic/grand-challenge.org#3748]
**Describe the bug**
When making a challenge request, user now have to fill in the extra clarification questions ("Why are you not willing/able to support this challenge long-term?" and "Why are you not willing/able to use a CC-BY license for your data?") even when they check the corresponding checkboxes. I think this is related to a recent change in the default of the checkbox fields (them being opt-in now when they apparently were opt-out before). 

**To Reproduce**
1. Go to https://gc.localhost/challenges/requests/create/
2. Scroll down to see the "We agree to support this challenge for up to 5 years." checkbox question. It is not checked initially and because of that you see the "Why are you not willing/able to support this challenge long-term? " textfield underneath. 
3. Check the "We agree to support this challenge for up to 5 years." checkbox. The extra question should disappear, but it does not. 

**Expected behavior**
The textfield to explain why they do not want to support the challenge for 5 years should only be visible when the checkbox is unchecked. 

The same holds for the data license checkbox further below. 

![image](https://github.com/user-attachments/assets/741c8c4d-fa96-4c4e-86cc-161c721195f3)

![image](https://github.com/user-attachments/assets/90945ad3-1645-4f45-8999-d8c028708da7)

**Comment by amickan** [comment]
Users cannot submit the form without filling the extra text fields, so this should be fixed asap.

**Comment by jmsmkn** [comment]
The `static` tag in the template is also malformed:

```
<script type="text/javascript" src="{% static "js/challenges/challenge_request_dynamic_fields.js" type="module" defer %}"></script>
```

**Comment by jmsmkn** [comment]
These also need to be fixed but do not prevent the form from being submitted:

```
            "expected_number_of_teams": forms.NumberInput(
                attrs={"oninput": "validity.valid||(value='');"}
            ),
            "number_of_tasks": forms.NumberInput(
                attrs={"oninput": "validity.valid||(value='');"}
            ),
            "average_size_of_test_image_in_mb": forms.NumberInput(
                attrs={"oninput": "validity.valid||(value='');"}
            ),
            "inference_time_limit_in_minutes": forms.NumberInput(
                attrs={"oninput": "validity.valid||(value='');"}
            ),
            "phase_1_number_of_submissions_per_team": forms.NumberInput(
                attrs={"oninput": "validity.valid||(value='');"}
            ),
            "phase_2_number_of_submissions_per_team": forms.NumberInput(
                attrs={"oninput": "validity.valid||(value='');"}
            ),
            "phase_1_number_of_test_images": forms.NumberInput(
                attrs={"oninput": "validity.valid||(value='');"}
            ),
            "phase_2_number_of_test_images": forms.NumberInput(
                attrs={"oninput": "validity.valid||(value='');"}
            ),
            "budget_for_hosting_challenge": forms.NumberInput(
                attrs={"oninput": "validity.valid||(value='');"}
            ),
```

Got to leave now, back in the afternoon, PR can be reviewed and merged though.
