### ISSUE TITLE
Make banners and logos Image Fields

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#377]
The uploading to dropbox is too awkward, this can easily be avoided with https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.ImageField

**Comment by bramvanginneken** [comment]
For a challenge organizer, the dropbox option can be very handy, especially if you write your own scripts to control what files/html/images are shown on the site. Not sure if that would be easy to do with django.

**Comment by jmsmkn** [comment]
The majority of challenges do not do this and are only using Dropbox for the logo and banner field. This is easily solved in Django and would lessen the administrative and maintenance burden for me (or, another site admin if this is used elsewhere). This is only about those fields, and not the Dropbox link on grand-challenge.org, which will still exist to those that need it. Most other use cases (including image uploading, html, css, js and permissions) are covered in the Pages app. Now we have automated evaluation I expect that even less challenges will be using these sorts of scripts.
