### ISSUE TITLE
Problem with data download using dropbox

### ISSUE THREAD

**Issue by jbernoz** [comic/grand-challenge.org#470]
Hi,
I have been using COMIC framework for the management of sub-challenges part of EndoVis project (GIANA challenge, more specifically). Since two or three weeks ago, users cannot download any of the files that are uploaded (linked to a dropbox folder) as it gives a message such as this one:
The requested URL '/site/endovissub2017-giana/serve/datasets/cvc-videoclinicdbtrain/cvc-videoclinicdbtrain_valid.rar/' was not found on this server.
The files are in the correct folder and the html code i used is the same i was using since three years ago:
{% listdir path:datasets/CVC-VideoClinicDBtrain%}
Has anything changed within the configuration of the framework that i am not aware of?
Thanks in advance,

**Comment by jmsmkn** [comment]
It looks like a case sensitivity issue - could you try making all the paths in Dropbox lower case? Or, you could get the sharing links for each file directly from Dropbox and put them on your page, this is more reliable.

**Comment by jbernoz** [comment]
I do not think it has anything to do with case sensitivity as it worked perfectly (with the same paths and so) until 3 weeks ago. Anyway, maybe it's better just to use directly Dropbox links as you suggest


Thanks!


Jorge


________________________________
De: James <notifications@github.com>
Enviado: viernes, 4 de mayo de 2018 15:04
Para: comic/grand-challenge.org
Cc: Jorge Bernal del Nozal; Author
Asunto: Re: [comic/grand-challenge.org] Problem with data download using dropbox (#470)


It looks like a case sensitivity issue - could you try making all the paths in Dropbox lower case? Or, you could get the sharing links for each file directly from Dropbox and put them on your page, this is more reliable.

**Comment by jmsmkn** [comment]
Changing the paths to lowercase fixes this, due to 8e4d0add06ee1a8dd81399d794005fa6448c3f9f
