### ISSUE TITLE
How to download dataset 

### ISSUE THREAD

**Issue by canhnp** [comic/grand-challenge.org#474]
Dear all,

I have already login but I can not download dataset of this challenge
https://iciar2018-challenge.grand-challenge.org/dataset/

When I click "CLICK HERE TO REQUEST DATASET". I see logs as below:

This page can only be viewed by participants of this project to view this page please make sure of the following:
First, log in to grand-challenges by using the 'Sign in' button at the top right.
Second, you need to join / register with the specific project you are interested in as a participant. The link to do this is provided by the project organizers on the project website.

**Comment by jmsmkn** [comment]
That challenge is closed. You need to ask the organisers if they are releasing the data to users who did not participate. Their email address is iciar2018.histochallenge [at] gmail.com
