### ISSUE TITLE
Create an image importer allowing users to safely upload new images

### ISSUE THREAD

**Issue by pkcakeout** [comic/grand-challenge.org#479]
This task consists of several different subtasks:

- [x] Implement a new image-aware data structure which encodes image and image meta data and archives containing images
- [x] Implement image loaders (sorter?) which can construct image arrays from loose image files.

Remaining TODOs continued in other issues
- Implement a user-facing archive-browser for presenting data in a useful way
    - Implement a modular image viewer framework (this probably will be continued in another issue)

**Comment by pkcakeout** [comment]
Currently, I am focusing on the upload mechanism for new images ("image-aware data structures"). I analyzed the process a bit together with Karel, and we came to the conclusion that the process for uploading images should consist of the following steps:

1. One uploads raw files into a staging-bucket
2. Different algorithms are applied to the staging bucket to convert different image formats to mhd/mha itk files (the "sorter"). This is done by a celery task.
    - For now any available algorithm will be applied to all uploaded image files, but in the future it must probably be made possible to configure which/how image loaders should be applied to be able to disambiguate between ambiguities in certain image formats (like DICOM)
3. The consolidated mhd files then can be put into archives. Once imported in this way, we know that the data can be trusted and do not need to deal with weird image loaders anymore and can rely on the straight-forward ITK format.

**Comment by jmsmkn** [comment]
Can this bucket be the existing staging environment of the jqfile uploads? Maybe up the validity period of the files. I guess you will need 1 object to link together all of these uploaded files first.

**Comment by pkcakeout** [comment]
> Can this bucket be the existing staging environment of the jqfile uploads?

I think not directly, since software like our dicomloader cannot load data from raw Python file handles and want to ope a file-like system object themselves. Instead I was planning to construct the system like this:

![379design1](https://user-images.githubusercontent.com/11632379/41230556-8535d3ee-6d80-11e8-930d-84d440a7df59.png)

The JQFileUupload model provides the basis for holding the raw uploaded data. The guarantees that data is cleaned up when it is not yet consolidated. Upload sessions themselves, however also need to be cleaned up eventually, but since they do not hold any serious data, this cleanup can be done when a user visits their "uploads page" (or so).

The "consolidation" process attempts to extract valid image data from the uploaded set of files. This is a celery process which is spawned after the uploaded images have been "submitted". It takes the new "UploadSession" as input, which refers to the jq-files and:

1. reconstructs contiguous files on-disk in a temporary directory (deleted when the celery task finishes)
2. mounts it in a docker-container (or a serious of different docker containers) which then attempt to make sense of the files and translate them to mhd images
    - this is the eventual goal, but for now I will do this step for ITK only in the celery process itself. I am sure that you, James, can help me should we migrate to the dockerized process.
    - The dockerized process has the advantage that we can easily expand and add new volume builders and disambiguate between different volume builders for different projects, and updating a volume builder will also be a breeze without introducing dependency hell to the Django website itself. (Category: **possible future feature**)
3. After the mhd files are extracted by the celery process, they are written into the database as "Image" objects. These then can be integrated with the Patient/Study/Series structure that we discussed and directly be displayed in the viewer we have, since they will all be standardized mhd files.

**Comment by jmsmkn** [comment]
2 - I agree, uploading and executing new containers is relatively ok now, but keep it as a celery process to start out. You will need to define a similar API as we have for algorithms and the evaluations.

**Comment by pkcakeout** [comment]
- [ ]  Files with identical filenames can still be uploaded, but there is no general way to disambiguate between them. Add a check and reject duplicate filenames.

**Comment by pkcakeout** [comment]
There is one last error that is left:

- [ ] Upload sessions are not tracked correctly on the server. When starting a second upload session, for example, by pressing F5 on the upload page, the list of uploaded files is cleared, but the filename deduplication code still finds the old uploads. This is happening, because the csrf-token is not renewed. Usually, this was not a problem because the list of uploaded files was created on the client only, but now this is an issue since it prevents people fro uploading a file. Must be fixed.

**Comment by jmsmkn** [comment]
I think that this is complete now.
