### ISSUE TITLE
Create viewer framework allowing users to display uploaded images

### ISSUE THREAD

**Issue by pkcakeout** [comic/grand-challenge.org#484]
The viewer framework should implement the following features:

- [ ] Selection of a viewer for a given image
- [ ] Have a user configurable default-viewer for certain types of image
- [ ] Opening the viewer and actually displaying an image

This shall be done with special care so that we can integrate our in-house viewer software at a later stage as a module. For now, we will refine and reuse the AMI.js-based prototype and create two types of viewers:

- [ ] 2D JavaScript viewer
- [ ] 3D JavaScript viewer

**Comment by jmsmkn** [comment]
Closing as this issue is too broad. This is on our roadmap.
