### ISSUE TITLE
Create processing tasks from uploaded images

### ISSUE THREAD

**Issue by pkcakeout** [comic/grand-challenge.org#485]
After images can be uploaded and managed by a user, a user must be able to select images for processing with a given algorithm. I do not yet know how this works, but it likely involves reactivating the old `Case` objects from the grandchallenge cases-app and integrating them with the algorithm-app again. 

This must be expanded upon once the other tasks of this milestone have moved further along.

**Comment by jmsmkn** [comment]
This is done
