### ISSUE TITLE
Create results browser for processing results on user images

### ISSUE THREAD

**Issue by pkcakeout** [comic/grand-challenge.org#486]
Algorithms can produce all kinds of results. In our current prototype, we are limited to showing raw json. It would be nice if we can make this more structured.

Interesting question: What if a processing task results in images of its own? Shall we make them available as new images?

**Comment by jmsmkn** [comment]
Yes, I will work on permissions. Initially it will be the algortihm + image creator but we should have groups like the participants of a challenge, etc.

**Comment by pkcakeout** [comment]
I wanted to add a permission system for images+users as part of #483. I thought that maybe we would not even set permissions on the image level, so that images become free-floating data packets that we do not need to worry about. Let's discus that on issue #483 though.

**Comment by jmsmkn** [comment]
Done
