### ISSUE TITLE
Run image_builder algorithms in separate containers

### ISSUE THREAD

**Issue by pkcakeout** [comic/grand-challenge.org#487]
Currently, image builders are run in a celery task. However, this is likely to be relatively insecure in comparison to running them in a separate docker container entirely. We should do this, because:

- The libraries used to read medical image files potentially cannot be trusted because Medical image files are complex niche image files, which are likely not thoroughly tested for malicious tampering. Likewise, the libraries reading those files are probably flawed.
- Containerizing our `image_builder` algorithm standardizes the interface we need to support if we want to support more file formats.

**Comment by jmsmkn** [comment]
A separate container entirely (and detached from the django stack) or in another celery worker? If the latter, see how to do this with the evaluation queue https://github.com/comic/grand-challenge.org/blob/master/app/config/settings.py#L428

**Comment by pkcakeout** [comment]
I though about the evaluation pipeline. The nice thing about this would be that we could just upload docker images to an internal docker registry (where only trusted images would go!) and use these images to add or update ways building images from raw files. This would be very flexible and allow us to add more "private"/internal algorithms as well (thinking about our DICOM reader here).
