### ISSUE TITLE
Include arXiv link to leader board

### ISSUE THREAD

**Issue by poely** [comic/grand-challenge.org#504]
We would like to have the possibility to add a link to an arXiv paper on the leaderboard. So, the page of ‘Evaluation Settings’ would have the following additional options:
•	Allow arXiv link
•	Require arXive link
•	Allow any URL
This would show a link on the leaderboard that takes you directly to that link when you click on it.

**Comment by jmsmkn** [comment]
@poely - this has been deployed now. Send me an email if you would like to add a URL to an existing submission.
