### ISSUE TITLE
Refresh the UI

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#506]
We will have to decide what to do with the existing css options, especially for the heavily modified challenges such as tadpole. 

Suggestions:
- [x] Upgrade bootstrap3 to bootstrap4
- [x] Sidebar for challenge pages rather than 2nd navbar

**Comment by HansPinckaers** [comment]
@jmsmkn I will work on the layout of the (data)tables next, making sure they fit the new design.

**Comment by jmsmkn** [comment]
To fix:
- [ ] Banners (see changes to jumbotron)

**Comment by HansPinckaers** [comment]
I pushed some more fixes to the bootstrap4 branch but didn't reference this issue. Mainly small stylistic changes.

**Comment by HansPinckaers** [comment]
@jmsmkn I  think I fixes _'The left padding around the logos on the all challenges page is a little odd'_ as well, but not sure what you exactly meant there. Did you mean the icons of the challenges?

**Comment by jmsmkn** [comment]
> @jmsmkn I think I fixed _'The left padding around the logos on the all challenges page is a little odd'_ as well, but not sure what you exactly meant there. Did you mean the icons of the challenges?

Yes, I'll take a look on the branch. Make sure it's tested with wide and tall logos too.

**Comment by HansPinckaers** [comment]
Ok with the last commit I think it looks ok for wide / tall logos.

**Comment by jmsmkn** [comment]
TODO when merging:
- Rows in pages must have .no-gutters
- Fix tabs
