### ISSUE TITLE
Improvement suggestions results page 

### ISSUE THREAD

**Issue by schelv** [comic/grand-challenge.org#540]
Hi,

I have some suggestions for the page where the results of the challenge are displayed.
Hopefully they can help with the results page becoming less messy.

- Add the ability to modify a user submission. example 1: someone submitted their predictions file as the supplementary file. I want to remove this file, but not the submission itself. example 2:  a submission with 'Hai' as the comment.
- Add a display settings for the score, to change the number of digits after the dot that are displayed.
Now there are 4 decimal digits after the dot (e.g. 0.7400). I want to limit this number of digits, and attempt to avoid/limit participants overfitting on the leaderboard. I currently round the score in the evaluation container. Doing this in the challenge settings would be nicer and avoid the trailing zeros.
- Submission time does not show the correct times for my timezone. Can't find an account setting to change this.

**Comment by jmsmkn** [comment]
Thanks for the suggestions.

I will implement the significant figures option and improvement of the submission time as part of a UI refresh this month. We won't implement a submissions editing form - please email support [at] grand-challenge.org with any changes that you want to make.

**Comment by jmsmkn** [comment]
@schelv - I have set the number of decimal places on the score to 2 for prostatex.
