### ISSUE TITLE
Challenge submission improvements

### ISSUE THREAD

**Issue by schelv** [comic/grand-challenge.org#543]
I have suggestions for the submission process.

- [x] Do not count a failed evaluation as a submission. I now see people first making two incorrect submissions and then making a new account to avoid the 24 hour waiting time.
- [x] When I was testing the failed-evaluation-counts-as-a-submission-thingy I noticed that the 'Choose file' button not only chooses the file but automatically makes the submission. It would be nice if users get to check and confirm what they submit. And also still give them the possibility to add the algorithm description and add a comment.
- [ ] Maybe make it possible to disable emails for these kind of failed evaluations: `evalutils.exceptions.ValidationError: Predictions missing: you did not submit predictions for ['ProstateX-0212-2', 'ProstateX-0213-1', 'ProstateX-0214-1']`. I get too much of these messages in my mailbox

**Comment by jmsmkn** [comment]
Done
