### ISSUE TITLE
"Require supplementary file" does not require "Allow supplementary file"

### ISSUE THREAD

**Issue by poely** [comic/grand-challenge.org#546]
The box "Allow supplementary file"  (under Admin->Evaluation Settings) is not required when you you check the box "Require supplementary file". I think that "Allow supplementary file" should be automatically be mandentory when you require a supplementary file. Otherwise, it would be possible to require a supplementary file without allowing a supplementary file.

**Comment by jmsmkn** [comment]
I agree. I will turn this into a choice field with "off" (default), "Allowed" and "Required".
