### ISSUE TITLE
Not showing horizontal scrollbar in firefox when content is too wide

### ISSUE THREAD

**Issue by emrekavur** [comic/grand-challenge.org#569]
Hi,

In "Registration Requests" page the Accept/Reject column does not appear. Therefore it is impossible to reach accept or reject buttons on this column:

![resim](https://user-images.githubusercontent.com/36921909/47420787-eb1e7a00-d787-11e8-82aa-c9d0b38ca4e2.png)

I can see the column and reach the buttons if I manipulate width of the DIV via `style="width:1200px;"` code as shown below:

![resim](https://user-images.githubusercontent.com/36921909/47420982-4ea8a780-d788-11e8-9764-8d53064f6da1.png)

I do not use additional .css file, everything is on default parameters.

**Comment by emrekavur** [comment]
Update: Partially, I found a solution. If I use Mozilla Firefox, I cannot see the horizontal sliding bar at the end of the page. However I can see it in Google Chrome. I can reach the Allow/Reject button by using this sliding bar. I think it is a browser issue. Sorry for inconvenience.

**Comment by HansPinckaers** [comment]
The horizontal scrollbar should be visible in firefox too, I will reopen this issue and investigate.

**Comment by jmsmkn** [comment]
Hi @HansPinckaers! Please continue this in #571
