### ISSUE TITLE
sign in does not bring you back to the page you came from

### ISSUE THREAD

**Issue by bramvanginneken** [comic/grand-challenge.org#604]
If you are at https://grand-challenge.org/Create_your_own_challenge/ and you are not logged in it shows:

![image](https://user-images.githubusercontent.com/1818749/48259456-469f6780-e418-11e8-9152-031c7e045e25.png)

If you now click sign in and sign in, you end up at the home page. Same when you are on a page and decide to sign out, you go back to the home page. It would be better if you go back to the page you were on.

**Comment by jmsmkn** [comment]
Fixed the sign in button on that page.
