### ISSUE TITLE
Support for 4DCT images

### ISSUE THREAD

**Issue by pkcakeout** [comic/grand-challenge.org#614]
Midas asked about support for 4DCT images on grand-challenge and allow processors to process them. In particular the goals should be to:

- Allow uploading DICOM files so that algorithms can be tried out by regular clinicians
- Processors must be able to read extra image attributes

# 4D-MHD file converison

The 4DCT group has written Python software that can assemble numpy ndarrays from loose DICOM images and extract the required DICOM tags. We can repurpose this code and implement it as an image assembler that creates MHD files. Extra image attributes can be directly written into the MHD files themselves.

Sil made an itk image reader/writer that supports a limited subset of features of the MetaIO file format, but can write correct 4D ITK images. The problem with this custom reader/writer is that it does not support the full set of features that an mhd file does support, most notably it does not support writing and reading extra attributes. When this module was created SimpleITK did not support 4D Images. Recently, thanks to changes in SimpleITK, this module _can_ be used to load and write 4D images:

~~~~~~~~~~
# Using SimpleITK 1.1.0 on Linux(!)

import numpy as np
import SimpleITK as sitk
import SimpleITK._SimpleITK as _sitk

a = np.ndarray([20, 20, 500, 500], dtype=np.float32)
a[1, 2, 3, 4] = 400
img = sitk.Image(a.shape[::-1], sitk.sitkFloat32, 1)
_sitk._SetImageFromArray( a.tostring(), img )

print("Equal?", (a == sitk.GetArrayViewFromImage(img)).all())

# Extra disclaimer: For some reason this does not seem to work on Windows with python2.7. It works on Linux and on repl.it: https://repl.it/@PKCakeout/FatalLatestApplet
~~~~~~~~~~

It is slightly hacky and might warrant a pull request to SimpleITK so that they add the proper "SetImageFromArray" function to their API - It is there just not exposed directly via the API.

There is not need to port Sil's itk reader for this reason, and we can rely on SimpleITK to do the saving instead. 

# Action points

- [x] Modify the [model](https://github.com/comic/grand-challenge.org/blob/master/app/grandchallenge/cases/models.py) to support 4D.
- [x] Modify existing [mhd image builder](https://github.com/comic/grand-challenge.org/blob/master/app/grandchallenge/cases/image_builders/metaio_mhd_mha.py) to support 4D images
- ~~Create an [image builder](https://github.com/comic/grand-challenge.org/tree/master/app/grandchallenge/cases/image_builders) from 4DCT-groups's dicom reader. The reader should use SimpleITK and can add required dicom tags as image attributes to the mhd files.~~ This issue can be found here #962.

**Comment by jmsmkn** [comment]
Sounds good to me, I would like to fix this issue before we add any more loaders: #487

**Comment by MidasM** [comment]
Shortly discussed with Paul, I have used his solution to load DICOM to 4D MHD. My implementation is below:
``` python
import os
import numpy as np
import dicom
import SimpleITK as sitk
import SimpleITK._SimpleITK as _sitk
import time
print(np.__version__, sitk.Version_VersionString())

localTemp = '/mnt/synology/neuro/temp/midas'
d = os.path.join(localTemp,'AnonymizedDicom')
c = os.path.join(localTemp,'AnonymizedITK')

# Get DICOM file list (1 dicom file == 3D volume, in this case 19 volumes)
dicomFileList = [os.path.join(d,i) for i in sorted(os.listdir(d))]

# Read first DICOM file for dimension, spacing etc. 
Ref_Dicom = dicom.read_file(fileList[0])

# Load dimensions based on the number of rows, columns, and slices (along the Z axis)
ConstPixelDims = (len(dicomFileList), int(Ref_Dicom.NumberOfFrames),int(Ref_Dicom.Rows), int(Ref_Dicom.Columns))

# Load spacing values (in mm)
x_i,y_i = [float(i) for i in RefDs.SharedFunctionalGroupsSequence[0].PixelMeasuresSequence[0].PixelSpacing]
z_i = float(RefDs.SharedFunctionalGroupsSequence[0].PixelMeasuresSequence[0].SliceThickness)

# (t,z,y,x)
ConstPixelSpacing = (1, z_i, y_i, x_i)

# Create zeros array to fill from DICOM
DicomArray = np.zeros(ConstPixelDims, dtype=RefDs.pixel_array.dtype)
# Additional Meta data Contenttimes and Exposures
ctimes = []
mAs = []

# Loop through all the DICOM files
print 'Reading {0} DICOM files...'.format(len(fileList)),
t0 = time.time()
for dicomFile in dicomFileList:
    # store the raw image data
    ds = dicom.read_file(dicomFile)
    DicomArray[dicomFileList.index(dicomFile), :, :, :] = ds.pixel_array
    ctimes.append(ds.ContentTime)
    mAs.append(ds.PerFrameFunctionalGroupsSequence[0].CTExposureSequence[0].ExposureInmAs)
print 'Done! ({0:.1f}s)'.format(time.time()-t0)

print 'Converting to SimpleITK...',
t0 = time.time()
img = sitk.Image(ArrayDicom.shape[::-1], sitk.sitkInt16, 1)
_sitk._SetImageFromArray(ArrayDicom.tostring(), img )
print 'Done! ({0:.1f}s)'.format(time.time()-t0)

# Set Image Spacing, Origin and Direction
sitk_origin = tuple([float(i) for i in ds.PerFrameFunctionalGroupsSequence[0].PlanePositionSequence[0].ImagePositionPatient])+(0.0,)
sitk_direction = tuple(np.eye(4,dtype=np.float).flatten())
sitk_spacing = ConstPixelSpacing[1:][::-1]+(1.0,)
print 'Setting image properties and MetaData...',
t0 = time.time()
img.SetDirection(sitk_direction)
img.SetSpacing(sitk_spacing)
img.SetOrigin(sitk_origin)

# Set Additional Meta Data
img.SetMetaData('ContentTimes',' '.join(ctimes))
img.SetMetaData('mAs',' '.join([str(e) for e in mAs]))
print 'Done! ({0:.1f}s)'.format(time.time()-t0)

print 'Writing...',
t0 = time.time()
sitk.WriteImage(img,c+'/cta4d_itk_meta.mhd',True)
print 'Done! ({0:.1f}s)'.format(time.time()-t0)
```

This probably could more optimized, but this works for me :-)

**Comment by jmsmkn** [comment]
This is required by the RTC by the end of 2019.

**Comment by AjayPatel86** [comment]
There are now multiple RTC projects that require this input and therefore some apps will be needing this feature sooner than the end of the year.
