### ISSUE TITLE
Show kaggle as hosting platform, and maybe covalic

### ISSUE THREAD

**Issue by bramvanginneken** [comic/grand-challenge.org#617]
Right now the all challenges cards have a "hosted on" field that can show grand-challenge or codalab. Would be nice if this could include kaggle. This works by parsing the url I suppose?

Would also be good if we go over the challenge listed on https://challenge.kitware.com/#challenges, I think a few are missing in our overview and have recent submission, e.g. https://challenge.kitware.com/#phase/5b1c1aa756357d41064da300 has a submission july 2018.
We could also list these as hosted on challenge.kitware.com

**Comment by jmsmkn** [comment]
> This works by parsing the url I suppose?

That's how it should work, but thats not how it was implemented... I'll sort it along with #611

**Comment by jmsmkn** [comment]
Done in #611
