### ISSUE TITLE
Send containers from other branches to docker hub

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#619]
- Add an identifier for master

**Comment by rzinkstok** [comment]
Do you want to make it possible to send containers from any branch to docker hub whenever someone thinks it is useful, or do you want to have a list of branches for which every successful build results pushing the containers?

**Comment by jmsmkn** [comment]
Only specific branches, otherwise we will end up with 1000s of images

**Comment by rzinkstok** [comment]
My thinking too, I'll see if I can get that to work. Might need your help at some point though...

**Comment by jmsmkn** [comment]
Ok, it's on master now. The branches we deploy from are controlled in travis.yml, you will need to add the branch name to the deploy_id in your deployment scripts.

**Comment by rzinkstok** [comment]
Wow, thanks! Am I correct that the branches that will be pushed are the ones for which a deploy provider is present in travis.yml?

**Comment by jmsmkn** [comment]
That's right
