### ISSUE TITLE
question

### ISSUE THREAD

**Issue by bramvanginneken** [comic/grand-challenge.org#620]
is it possible to indicate that you want to approve submissions, and only after approving submissions, they are shown on the leaderboard. we could not find it in the menus/settings.

**Comment by jmsmkn** [comment]
There's the "Auto Publish New Results" option on the Scoring tab ("If true, new results are automatically made public. If false, the challenge administrator must manually publish each new result."). I can clean that help text up, "new results are automatically made public" => "new results are automatically published on the leaderboard".

**Comment by bramvanginneken** [comment]
Right, found it, I thought it was there. I did not find it because we did not scroll all the way down to below this long table. I think it is quite clear. Closing.
