### ISSUE TITLE
Local development with Django devserver in PyCharm

### ISSUE THREAD

**Issue by rzinkstok** [comic/grand-challenge.org#630]
In order to work with the PyCharm debugger etc it would be nice to be able to run the django development server in PyCharm itself instead of using the full docker-compose setup locally. It also makes for a quicker reload of the code in the server. We propose the following:
- creation of a .env.dev file containing all the environment variables needed for local development
- adding env vars for POSTGRES_HOST and CELERY_TASK_ALWAYS_EAGER
- adding a docker-compose_dev.yml file that contains only the database service; the postgres data folder is a folder in the repo (ignored in .gitignore) which is loaded as a volume to the DB container; the postgres port is shared with the host 
- setting CELERY_TASK_ALWAYS_EAGER removes the need for the celery workers and redis; caching is not needed either
- adding documentation to instruct people how to setup the local dev environment in PyCharm

Of course it is still possible to run the full docker-compose system, and that would still be needed to run all the tests.

**Comment by rzinkstok** [comment]
You can see our changes in the eyra-dev branch (https://github.com/comic/grand-challenge.org/tree/eyra-dev)

**Comment by jmsmkn** [comment]
Ok, all of the test that rely on celery are broken on that branch right now, my guess is that it's because `CELERY_TASK_ALWAYS_EAGER` should be None by default. Setting `CELERY_TASK_ALWAYS_EAGER` is not sufficient if you also want to not run redis and the workers, you also need to set the propagation, broker url and backend, eg:

```
        settings.task_eager_propagates = (True,)
        settings.task_always_eager = (True,)
        settings.broker_url = ("memory://",)
        settings.backend = "memory"
```

Note that you then lose the integration with celery so any views that have long tasks associated with them will then fail. There is also coupling between nginx and django as some extra routing is done there. 

Why do you need to maintain an exhaustive list of default environment variables? Defaults are handled with `os.environment.get`, so only store the ones that you explicitly need to override for running in this mode and don't pass through your system environment vars.

**Comment by rzinkstok** [comment]
The failed tests we did anticipate (sorry!), this was just meant for showing you the idea. Your comments are very useful, and in fact we think we can make things a bit easier. We can actually use the existing docker-compose.yml together with running the dev server in PyCharm. This would mean there are two web servers running at the same time (the one in a docker container and the dev server in PyCharm, but they should not interfere. The only thing that would be needed is exposing the db port. Of course the celery stuff is still an issue: then again, there are at least two options in combination with running the server in PyCharm. First, we could use celery_task_always_eager (and the rest of the necessary settings), and not use asynchronous task execution. Second, we could expose the redis port of the docker container to the host as well, and connect the dev server to redis  and thus the workers running in docker. Of course, this would still mean cycling the containers when code changes, but it does help a lot I think. 

The issues with the nginx-django coupling we will look at as well, thanks for pointing that out. 

Regarding the environment variables, you are right about the defaults in the settings file. Again, this was a little bit quick and dirty. We'll clean up the env vars file and see where we end up.

Are you in general inclined to go along with our thinking?

**Comment by jmsmkn** [comment]
No worries, you can break anything you like as long as it's not master :-)

I prefer running the entire docker compose stack, this way there is less chance of hitting any integration issues as there is more parity between development and production. The django dev server does not do live reloading (IIRC), but html changes are directly loaded. You can speed up the reloading by taking out:

```
      && python manage.py migrate
      && python manage.py check_permissions
      && python manage.py initcomicdemo
```

from the startup command, and moving those to one time jobs in cycle_docker_compose, but you will have to handle any startup issues.

**Comment by rzinkstok** [comment]
Thanks James! Based on your comments we've decided to make it a bit simpler. We'll run the normal docker-compose.yml, but we've added port mapping for the postgres and redis ports. In this way, you can either use the web service of the docker-compose setup or the PyCharm Django dev server (or the Django dev server started from a regular terminal). As the dev server runs on port 8000 there is no port conflict with the web service of the docker-compose setup.

The exposed ports in the docker-compose file did cause the travis build to fail, as travis (apparently) has both postgres and redis already running on the build host, leading to port conflicts. So we added two statements stopping those services to the travis config.

See https://github.com/comic/grand-challenge.org/tree/eyra-dev for the changes. If you like it, we can open a pull request.
