### ISSUE TITLE
Request supplementary file type

### ISSUE THREAD

**Issue by poely** [comic/grand-challenge.org#632]
Today (November 29, 2018), I received a submission to HC18 from ybrong. ybrong has added a csv file as an algorithm description. This csv file does not contain the algorithm description, but the result of the submitted system. Would it be possible to request a supplementary file type, for example a pdf, to prevent people from (mistakenly) submitting the prediction file as the algorithm description?

**Comment by jmsmkn** [comment]
This is already enabled, people can only upload either text or pdf: https://github.com/comic/grand-challenge.org/blob/master/app/grandchallenge/evaluation/models.py#L382 - it is quite difficult to check if a file is plain text vs csv in the response time of the web app, so I don't think this is something we want to do.
