### ISSUE TITLE
Math equations on webpage

### ISSUE THREAD

**Issue by Borda** [comic/grand-challenge.org#635]
Is it possible to have a mathematical equation on the web page, I would find it very convenient since we are describing an evaluation metric.

I tried some standard tags from HTML5 like `<sub>` but it does not work. 
* https://www.w3.org/MarkUp/HTMLPlus/htmlplus_45.html

I found that there is a friendly javascript render - MathML or AsciiMath, would it be possible to add it to the website?
* https://accessibility.oit.ncsu.edu/putting-math-on-the-web-using-mathml-and-html5
* http://asciimath.org/

**Comment by jmsmkn** [comment]
Good idea. I think MathJax is a good option, I will add it with the `TeX-MML-AM_CHTML` and `safe` config. We can officially support tex and asciimath, allowing MathML would cause too much overhead as we need to add all of the possible tags to the blech allowlist.

**Comment by jmsmkn** [comment]
This has been deployed and the documentation updated. Please let me know if you have any issues.
