### ISSUE TITLE
Add submission deadline for challenge?

### ISSUE THREAD

**Issue by bramvanginneken** [comic/grand-challenge.org#646]
We can now set a date for a workshop, but some challenges do not have a workshop but they do have a deadline for submitting results. Would be nice if we can enter that date and would be on the overview cards as

Deadline for submissions: Mar 12, 2019

**Comment by jmsmkn** [comment]
Should we introduce something like challenge phases? We could do things like have leaderboards associated with each phase, different evaluations and data associated with each. Seems like something that was missing with the decathlon challenge, but I'm not too sure how much it really is needed.

**Comment by jmsmkn** [comment]
Continued in #738
