### ISSUE TITLE
make results hidden

### ISSUE THREAD

**Issue by bramvanginneken** [comic/grand-challenge.org#682]
Every page has permission, so you can set it to only registered users. But the Results page is an automatically created page, see e.g. https://lola19.grand-challenge.org/evaluation/results/

Is it possible to also make this page visible only to registered users. Would also be nice if you can make one setting to set all pages to visible to registered users only.

**Comment by prash-p** [comment]
I second this request :)

**Comment by jmsmkn** [comment]
This has now been deployed - if a challenge is set to `hidden` then the published evaluations will only be visible to the challenges participants group.
