### ISSUE TITLE
Search button for adding admins

### ISSUE THREAD

**Issue by ecemlago** [comic/grand-challenge.org#690]
Currently, when a user wants to add a new admin, it shows a list which consists of entire participants of grand challenge, which is extremely hard to scroll down. We should add a search button for this.

**Comment by jmsmkn** [comment]
This package looks promising for it - https://github.com/yourlabs/django-autocomplete-light

Would you like to have a go at integrating it?

**Comment by ecemlago** [comment]
Sure!

**Comment by jmsmkn** [comment]
Great! Thanks.

I think all this need is:

- Install the package using `pipenv`
- Add 'dal' and 'dal_select2' before django admin in the settings file for the installed apps (`app/config/settings.py`) (https://django-autocomplete-light.readthedocs.io/en/master/install.html#configuration). We already ship jquery so no need to add that.

Then to update the challenge admin form:

I think the relevant section of the docs is here: https://django-autocomplete-light.readthedocs.io/en/master/tutorial.html#use-the-view-in-a-form-widget

See the code block "Another way to do this is directly in the Form.Meta.widgets dict, if overriding the field is not needed"

Let me know if you need any help.
