### ISSUE TITLE
Site hangs if you go to code view

### ISSUE THREAD

**Issue by bramvanginneken** [comic/grand-challenge.org#697]
I edit a page:

![image](https://user-images.githubusercontent.com/1818749/52792466-c4a08980-306b-11e9-8a99-900e458ac486.png)

If I click to the code view button (</>) I see a screen with code, but the site hangs, nothing works anymore, I cannot go back or continue.

**Comment by jmsmkn** [comment]
Oh wow. It just happens on that page. Someone base64 encoded the image and put it straight into the html (??!). I've removed it. Please check that it works now.
