### ISSUE TITLE
editing not in WYSIWYG mode

### ISSUE THREAD

**Issue by bramvanginneken** [comic/grand-challenge.org#698]
If you edit a page I do not see how to switch to editing html instead of a WYSIWYG editor.

I also do not understand why I see images twice in the editor (on the page they are there only once).

![image](https://user-images.githubusercontent.com/1818749/52792730-66c07180-306c-11e9-8337-736ebdaf5de0.png)

**Comment by jmsmkn** [comment]
Please check if it's fixed with #697 - only this page is affected

**Comment by bramvanginneken** [comment]
Yes, you were right. Works fine. But stupid you cannot go full screen once you are in code view, this button is then disabled, but that's probably not something you can fix, and not so important.

**Comment by jmsmkn** [comment]
Wait - it seems like there is a bug with this. The base 64 encoded image came back again. I will go back to an earlier version of the editor.
