### ISSUE TITLE
Retina feature request: total annotated area

### ISSUE THREAD

**Issue by Daniel-EMC** [comic/grand-challenge.org#700]
@HarmvZ Total drusen area and area within (certain parts of) the Grid needs to be displayed in the Workstation.

**Comment by HarmvZ** [comment]
Implemented partially in #725. It is implemented very superficially because the exact pixel spacing is not known for the current images in the workstation. Therefore, the pixel size (both horizontal and vertical) has been set to a fixed value (0.016253 mm) as indicated by Timo.
