### ISSUE TITLE
Retina workstation: disable editing option of small lesions

### ISSUE THREAD

**Issue by Daniel-EMC** [comic/grand-challenge.org#713]
Squares for resizing of the annotation appear after annotation. These squares make it more difficult to check the annotation. Probably, it would be better to only implement the resizing option for larger areas. Instead, it should be easy to quickly remove smaller annotations by selecting them and pressing delete.

**Comment by HarmvZ** [comment]
In #725 all editing option of lesions is removed in order to improve performance. This will be reimplemented as described in #731.
