### ISSUE TITLE
Add evaluation phases

### ISSUE THREAD

**Issue by ecemlago** [comic/grand-challenge.org#738]
Enabling users to create multiple leaderboards can be useful for educational challenges where different research group create their own leaderboard for their students, and also useful for challenges which contain several sub-challenges (different tasks).

**Comment by jmsmkn** [comment]
This would be a big change as we have a 1-1 relationship between a challenge and {evaluation config, method, submission, result} as we assumed that 1 challenge would have 1 task. We run in to this limitation somewhat frequently.

This assumption would need to be split and added to an intermediate model instead. I would suggest adding a challenge Phase here, where a Phase can have different deadlines, run concurrently, can contain different tasks, methods and results. It's definitely possible but given the magnitude of the change I would prioritise other features right now.

**Comment by hjoonjang** [comment]
@jmsmkn 

1. Could you please elaborate the details of 'adding a challenge Phase'? Is there any specific way to make it? I'm facing a similar issue above.

2. In addition, please let me know if the challenge organizers can have multiple parallel leader boards by a single evaluation metric with the same JSON output.

**Comment by jmsmkn** [comment]
This is implemented and available by asking support to enable multiple phases for your challenge. We need to work on permissions, the layout and documentation before rolling this out more generally.

**Comment by bramvanginneken** [comment]
Excellent. Should Kiran create documentation? Should we have some example challenge set up to refer to in the documentation?

**Comment by jmsmkn** [comment]
No, it's ok, this is one of the things I'm going to present at the workshop and will create documentation as part of the prep for that.
