### ISSUE TITLE
Add django select2 to the user list on the legacy submission page

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#748]

**Comment by Borda** [comment]
The list of participants should be ordered, ideally alphabetically for easier navigation.
Also, there are probably missing some participant from the list, for example, IMW user at ANHIR challenge (he has the challenge at his profile page but he is missing at the challenge participants list)
see: https://grand-challenge.org/accounts/lMW and https://anhir.grand-challenge.org/participants

**Comment by jmsmkn** [comment]
The participant is not missing - note that their username is `lMW` (with a lower case `L`) and not `IMW` (with an upper case `i`).

**Comment by Borda** [comment]
@jmsmkn I see, but could it be rather ordered selection?
