### ISSUE TITLE
 Abdominal Organ Segmentation

### ISSUE THREAD

**Issue by RuiruiKang** [comic/grand-challenge.org#834]

**Comment by RuiruiKang** [comment]
hello
I want to join in CHAOS and download the abdominal data. I hope my request
can be approved
Thank you very much.
Best regards.

James <notifications@github.com> 于2019年6月13日周四 下午3:39写道：

**Comment by RuiruiKang** [comment]
Challenge Description
Understanding prerequisites of complicated medical procedures plays an important role on the success of the operations. To enrich the level of understanding, physicians use advanced tools such as three dimensional visualization and printing, which require extraction of the object(s) of interest from DICOM images. Accordingly, the precise segmentation of abdominal organs (i.e. liver, kidney(s) and spleen) has critical importance for several clinical procedures including but not limited to pre-evaluation of liver for living donor based transplantation surgery or detailed analysis of abdominal organs to determine the vessels arising from and entering them for correct positioning of a graft prior to abdominal aortic surgery. This motivates an ongoing research to achieve better segmentation results and overcoming countless challenges originating from both highly flexible anatomical properties of abdomen and limitations of modalities reflected to image characteristics.
In this context, the proposed challenge has two separate but related aims:

Segmentation of liver from computed tomography (CT) data sets, which are acquired at portal phase after contrast agent injection for pre-evaluation of living donated liver transplantation donors.
Segmentation of four abdominal organs (i.e. liver, spleen, right and left kidneys) from magnetic resonance imaging (MRI) data sets acquired with two different sequences (T1-DUAL and T2-SPIR).
There will be five competition categories in which the participating teams can take place and submit their result(s):

Liver Segmentation (CT-MRI)
Liver Segmentation (CT only)
Liver Segmentation (MRI only)
Segmentation of abdominal organs (CT+MRI)
Segmentation of abdominal organs (MRI only)
Due to above mentioned significance of the problem, the challenge will serve several purposes:

In the last decade, not only the number of segmentation methods increased significantly, but also applicability is aimed to be extended to multiple segmentation tasks (For instance, a single deep network, which can segment multiple organs [category 4] or more rarely, a system that can segment the same organ(s) from different modalities [category 1 and 5]).
On the other hand, it is known that many new architectures significantly depend on the training data set, which yields to poor generalization capability. Besides physicians, who are the final user of the medical segmentation methods, even experienced researchers still struggle at choosing appropriate techniques or tweaking optimal model parameters for a particular problem.
Thus, by providing data sets from two different modalities, the participants are encouraged to develop a system that would work on both (The data sets from CT and MR databases are acquired from different patients).
Nevertheless, organ segmentation from abdominal MRI sets is being proposed as a challenge for the first time and therefore, systems that would only work on a single modality (e.g. MRI or CT) are also accepted.

**Comment by jmsmkn** [comment]
Please contact the organisers of that challenge with your query: https://chaos.grand-challenge.org/Organization_Team/
