### ISSUE TITLE
Let administrators control multiple submissions at once

### ISSUE THREAD

**Issue by hjoonjang** [comic/grand-challenge.org#856]
Hi,

I'd like to implement double stages sequentially on my challenge site;
* **Stage1:** Open leaderboard (auto-publishing new results) with dataset A
* **Stage2:** Closed leaderboard (manual-publishing new results) with dataset B
(**Stage2**'s leaderboard, by which final ranks will be determined, will be opened after the corresponding conference session ends.)

If so, it currently seems that we should follow the steps like below; (because we cannot make the leaderboard invisible solely, without affecting submission functions.)
1. At the end of **Stage1**, grab every single submission job with dataset A and make it invisible respectively/manually.
1. Turn the *auto-publish new results* option off.
1. Upload a new docker image dedicated for **Stage2**.
1. At the end of **Stage2**, grab every single submission JSON result with dataset B and collect them invisibly (and of course, manually) for sorting the results' ranks.
1. At the end of the hidden period of **Stage2**, (e.g. after conference week, etc.) grab every single submission job with dataset B  and publish them all respectively/manually.
1. Turn the *auto-publish new results* option on again.

I would appreciate if step 1, 4, and 5 could be supported by **controlling as a bundle** features possibly on the challenge administrator's view.

For examples;
1. It might be visible/invisible toggle (or setup) button with checkboxes. (for step 1 & 5)
1. It might be CSV (or whatever) formatted download (i.e. export) button with checkboxes. (for step 4)

Would it be possible for you to implement those features?
Thanks for all your supports.

Hyungjoon

**Comment by jmsmkn** [comment]
Yes, I think that this is quite a unique use case so is better done manually. Email us at support at grand-challenge.org with the dates that you would like steps 1, 4 and 5 done and we can do it for you.
