### ISSUE TITLE
Zenodo link for data

### ISSUE THREAD

**Issue by bramvanginneken** [comic/grand-challenge.org#880]
**Is your feature request related to a problem? Please describe.**
Several challenges have all their data stored on Zenodo or have another type of data url. 

**Describe the solution you'd like**
We could have a field Data URL associated with challenges, also external ones. Would be nice to make an overview to list challenges that use one particular data set, with a CC license.

**Comment by jmsmkn** [comment]
Also see #978 - these should be solved together.

**Comment by jmsmkn** [comment]
With #1533 it is now possible to add a publication with the zenodo DOI, then associate that publication with a challenge.
