### ISSUE TITLE
Reader study order randomization for images

### ISSUE THREAD

**Issue by pkcakeout** [comic/grand-challenge.org#890]
**Describe the solution you'd like**
There should be a flag on the reader-studies page that randomizes the order of scans presented to a reader.

**Additional context**
Randomized trials are standard scientific method to counteract biases in answers. We should have that feature.

**Comment by pkcakeout** [comment]
(How do I add these to our project again? I do not remember how we do this)

**Comment by jmsmkn** [comment]
Not too sure where this responsibility should lie. The front end could also do a `random.choice` from the unanswered hangings, with maybe a boolean to turn this functionality on and off on the backend.

**Comment by jmsmkn** [comment]
Maybe use the username for the seed of the shuffler? Use a fixed algorithm for generating the shuffle?

**Comment by jmsmkn** [comment]
Possibly use numpy for this, which guarantees compatability across versions: https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.random.RandomState.html#numpy.random.RandomState
