### ISSUE TITLE
Create a management command to remove a complete archive with all related patients, studies, images, annotations, registrations, etc

### ISSUE THREAD

**Issue by HarmvZ** [comic/grand-challenge.org#900]
The current "Rotterdam Study 1" archive has to be removed and reuploaded. Although this might not happen often, doing this manually in the admin is not time efficient and error-prone. Therefore, I think we should develop a way in which this can be done easier. There are a few difficulties when doing this because of the way the models are set up:

- Removing an `Archive` will leave all other data intact.

- Removing a `Patient` or `Study` is not possible when it has related images since the study foreign key field on an image contains `on_delete=models.PROTECT`.

- Removing an `Image` will also remove all related annotations, but not any related `Study`/`Patient`/`Archive`/`ImageFile`.

I think the best way to achieve this is to make a management command with `Archive.id` as input that removes the Archive and all of the related models.

**Comment by jmsmkn** [comment]
I'm not so sure about this - perhaps we should change the `PROTECT` statement and update the delete methods on the models so that everything is cleaned up?

**Comment by HarmvZ** [comment]
Just discussed this IRL. Conclusion:
- Change all the `on_delete` attributes on the relations to cascade. 
- Extend the `delete` method on an archive to find all related patients (through `image_set.study.patient`) and remove those. If all `on_delete` attributes are changed this should fire a cascading delete for all related `Study`/`Patient`/`Archive`/`ImageFile`/`Annotation` models

One thing to keep in mind: When removing an `Archive` we should make sure that all images belonging to it may be deleted, since they could also belong to other Archives which they will then also be removed from.
