### ISSUE TITLE
Integrating decathlon statistical ranking

### ISSUE THREAD

**Issue by ecemlago** [comic/grand-challenge.org#921]
Implementing statistical ranking scheme which was used in the decathlon challenge. It uses the Wilcoxon signed-rank test and ranks an algorithm by calculating the number of instances an algorithm performs significantly better than its competitors on a given subtask: http://medicaldecathlon.com/files/MSD-Ranking-scheme.pdf

In order to implement it, we need to access all of the metrics for all of the algorithms first. In order to have access to all algorithm results, this needs to be implemented in the grand challenge, here: https://github.com/comic/grand-challenge.org/blob/master/app/grandchallenge/evaluation/tasks.py#L49

**Comment by jmsmkn** [comment]
~2 years with no updates, assuming this is abandoned.
