### ISSUE TITLE
"View image" button in algorithm jobs table is blocked by overlay

### ISSUE THREAD

**Issue by nlessmann** [comic/grand-challenge.org#947]
When moving the cursor over the "view image" button or the "view overlay" button in the table with jobs for an algorithm, the button is only clickable at the very bottom because otherwise a gray overlay with the image dimensions blocks the button. This gray overlay actually flickers, so disappears and reappears. I think what happens is that the cursor is moved over the button, that makes the overlay appear under the cursor, that makes the overlay disappear again, ...

I'm using Chrome 77 on Windows.

![screenshot](https://user-images.githubusercontent.com/773597/66643687-89b51c80-ec1f-11e9-902c-dde49dcf7dc4.png)

**Comment by jmsmkn** [comment]
I saw this bug in development before, thought I solved it but obviously not. Best to remove the tooltips, make the buttons small, and add the text directly there. 

Workaround - use the overlay button to open the workstation and then remove `overlay=....` from the url.

@haimasree added overlay toggling and alpha level setting to the workstation yesterday but this has not yet been deployed.
