### ISSUE TITLE
Add a DICOM image builder

### ISSUE THREAD

**Issue by silvandeleemput** [comic/grand-challenge.org#962]
This issue was first raised in #614 as a sub-feature, but it was decided that it is better to separate the issue.

* [x] Create an [image builder](https://github.com/comic/grand-challenge.org/tree/master/app/grandchallenge/cases/image_builders) from 4DCT-groups's Dicom reader. The reader should use SimpleITK and can add required Dicom tags as image attributes to the MHD files.
  * [x] Parse headers to determine if a valid Dicom and determine the associated Dicom files
  * [x] Function to read image data from one or more Dicom files to SimpleITK format (.mhd)
  * [x] Function to extract additional image attributes like content times and mas and add those to the MHD file.

* It is desired to be able to upload DICOM files so that algorithms can be tried out by regular clinicians
* Processors must be able to read extra image attributes (what these are can probably be extracted from the example)

**Desired solution**
As a starting point, the 4DCT Dicom image loader should be added as an image builder. Later we could add support for other DICOM image formats as well.

**4D CT DICOM Loader code snippet**

This hands on code was provided by Midas and copied from #614:

```python
import os
import numpy as np
import dicom
import SimpleITK as sitk
import SimpleITK._SimpleITK as _sitk
import time
# numpy version == 1.15.4
# SimpleITK version == 1.1.0
# dicom version == 0.9.9
print(np.__version__, sitk.Version_VersionString(),dicom.__version__)

localTemp = '/mnt/synology/neuro/temp/midas'
d = os.path.join(localTemp,'AnonymizedDicom')
c = os.path.join(localTemp,'AnonymizedITK')

# Get DICOM file list (1 dicom file == 3D volume, in this case 19 volumes)
dicomFileList = [os.path.join(d,i) for i in sorted(os.listdir(d))]

# Read first DICOM file for dimension, spacing etc. 
Ref_Dicom = dicom.read_file(fileList[0])

# Load dimensions based on the number of rows, columns, and slices (along the Z axis)
ConstPixelDims = (len(dicomFileList), int(Ref_Dicom.NumberOfFrames),int(Ref_Dicom.Rows), int(Ref_Dicom.Columns))

# Load spacing values (in mm)
x_i,y_i = [float(i) for i in RefDs.SharedFunctionalGroupsSequence[0].PixelMeasuresSequence[0].PixelSpacing]
z_i = float(RefDs.SharedFunctionalGroupsSequence[0].PixelMeasuresSequence[0].SliceThickness)

# (t,z,y,x)
ConstPixelSpacing = (1, z_i, y_i, x_i)

# Create zeros array to fill from DICOM
DicomArray = np.zeros(ConstPixelDims, dtype=RefDs.pixel_array.dtype)
# Additional Meta data Contenttimes and Exposures
ctimes = []
mAs = []

# Loop through all the DICOM files
print 'Reading {0} DICOM files...'.format(len(fileList)),
t0 = time.time()
for dicomFile in dicomFileList:
    # store the raw image data
    ds = dicom.read_file(dicomFile)
    DicomArray[dicomFileList.index(dicomFile), :, :, :] = ds.pixel_array
    ctimes.append(ds.ContentTime)
    mAs.append(ds.PerFrameFunctionalGroupsSequence[0].CTExposureSequence[0].ExposureInmAs)
print 'Done! ({0:.1f}s)'.format(time.time()-t0)

print 'Converting to SimpleITK...',
t0 = time.time()
img = sitk.Image(ArrayDicom.shape[::-1], sitk.sitkInt16, 1)
_sitk._SetImageFromArray(ArrayDicom.tostring(), img )
print 'Done! ({0:.1f}s)'.format(time.time()-t0)

# Set Image Spacing, Origin and Direction
sitk_origin = tuple([float(i) for i in ds.PerFrameFunctionalGroupsSequence[0].PlanePositionSequence[0].ImagePositionPatient])+(0.0,)
sitk_direction = tuple(np.eye(4,dtype=np.float).flatten())
sitk_spacing = ConstPixelSpacing[1:][::-1]+(1.0,)
print 'Setting image properties and MetaData...',
t0 = time.time()
img.SetDirection(sitk_direction)
img.SetSpacing(sitk_spacing)
img.SetOrigin(sitk_origin)

# Set Additional Meta Data
img.SetMetaData('ContentTimes',' '.join(ctimes))
img.SetMetaData('mAs',' '.join([str(e) for e in mAs]))
print 'Done! ({0:.1f}s)'.format(time.time()-t0)

print 'Writing...',
t0 = time.time()
sitk.WriteImage(img,c+'/cta4d_itk_meta.mhd',True)
print 'Done! ({0:.1f}s)'.format(time.time()-t0)
```

**Comment by MikeOverkamp-diag** [comment]
@jmsmkn @AjayPatel86 I have noticed while testing this feature that uploading all associated files separately could cause some issues:
- The upload takes a lot longer, because 1) there are many more sessions and 2) the total file size can be reduced greatly by compressing all files into one.
- More importantly: my connection gets interrupted every now and again. As a result some of the uploaded files could be corrupt or missing, so data integrity might be lost in the upload process.

I therefore think it would be best to upload the files as a single .zip (or some other compressed file format). The question is: do we force the user to do so or do we merely suggest it in the help text? I'm not sure how cumbersome it would be for e.g. a clinician to zip the files before uploading them, which is why I'm asking the both of you for your input.

Another minor convenience of forcing the use of a zip file is that we could then use the filename as the image name, whereas otherwise we would have to use a generated one.

**Comment by jmsmkn** [comment]
There is an issue already requesting this #756, and the integrity should be fixed client side but re-tries are not being attempted right now #537 (we needed a new API to do this which is now done so can be fixed). If you want to tackle them, please do so in another PR, they're not as high priority as this.

**Comment by AjayPatel86** [comment]
@MikeOverkamp-diag 
Thanks for looking into this. I don't think asking clinicians to zip their input is a big problem.
