### ISSUE TITLE
"Request access" button for algorithms

### ISSUE THREAD

**Issue by wouterbulten** [comic/grand-challenge.org#968]
**Is your feature request related to a problem? Please describe.**
Accessing a public algorithm, without access, results in an uninformative forbidden page. The only option now is to email the owner of the algorithm.

**Describe the solution you'd like**

1. Users should have a way for requesting access to an algorithm. For example, a "request access" button.
2. Public algorithms should have a more user-friendly error page when you don't have access (yet). This page could include a request button.

**Comment by jmsmkn** [comment]
@MikeOverkamp-diag We have something link this implemented already for challenges using a `RegistrationRequest` model, not sure if that is the best approach but we could do something here. Requirements as I see it:

- A user who is not in the users group for an individual algorithm is able to request to join that algorithms users group
- When a new request is created all of the users in that algorithms editors group are emailed with a link that would allow them to accept or reject the request
- If one of the algorithm editors wants to reject a user they can optionally add a small text to explain why
- If the user is accepted, then they are added to that algorithms users group
- If the user is accepted or rejected, they receive an email
- If the user is rejected, they can request to join again
