### ISSUE TITLE
Add user options to algorithms

### ISSUE THREAD

**Issue by wouterbulten** [comic/grand-challenge.org#969]
**Is your feature request related to a problem? Please describe.**
The algorithm I'm creating now for Grand Challenge contains a heavy normalization step (taking roughly 85% of the processing time). For some cases this step is not needed. Users can however not indicate that they want to skip this step.

**Describe the solution you'd like**
A simple solution would be to make two algorithms (with two containers). But, this seems a bit cumbersome. It would be useful if algorithm developers could indicate (a set of) input variables that users can set. These can then be rendered on the "submit job" page and presented as ENV variables to the container.

For safety reasons and to make input sanitation easy, this could be limited to categorical variables only.

For example, the following config:
```
variables:
    normalization:
        label: "Run normalization step:"
        values:
            - Yes
            - No
```
Would render on the submit job page:

```html
<label for="var-normalization">Run normalization:</label>

<select id="var-normalization">
    <option value="yes">Yes</option>
    <option value="no">No</option>
</select>
```

and set something like  `ENV normalization=yes` for the container.

**Comment by jmsmkn** [comment]
Workaround for this - create another algorithm with that option as default.

**Comment by wouterbulten** [comment]
Yes, that will work. It's a nice-to-have. I'm also not sure if there are other algorithms that could make use of this functionality, or if it's limited to our case.
