### ISSUE TITLE
Terms and conditions for algorithms on upload page

### ISSUE THREAD

**Issue by wouterbulten** [comic/grand-challenge.org#981]
Technically, if grand challenge gets a Terms & Conditions page (see #980), algorithms itself do not need separate terms and conditions if they are covered by the site-wide one.

However, I think it would be still good to make people aware of this when submitting data to an algorithm. Especially when we want to use uploaded data for future research, it has to be crystal clear to users that we can use this data if they upload it.

A minimal version of this could be a single sentence like "By uploading data to this algorithm you agree with the T&C as defined [here]". It could be even beter if algorithms could define additional terms on top, but that is a nice to have.

**Comment by jmsmkn** [comment]
The terms also need to be added to the OpenAPI schema (`terms_of_service`)

**Comment by wouterbulten** [comment]
The chance in #1041 looks good. Any indication on when this could get deployed? We are starting to get access requests for the algorithm and it would be nice to have the terms present :)

**Comment by jmsmkn** [comment]
I'm planning on reviewing that today - no need to push me on this, I review PRs the next morning after I get them, but have been doing nothing but attending meetings the past 2 work days.
