### ISSUE TITLE
"Run algorithm" page is missing the breadcrumb bar

### ISSUE THREAD

**Issue by nlessmann** [comic/grand-challenge.org#997]
Maybe this is on purpose, but I find it confusing that the page that allows users to upload images and run an algorithm does not show the breadcrumb bar to get back to the algorithm overview page.

Example: https://grand-challenge.org/algorithms/vertebra-segmentation/run/

To be consistent with the job list the title of that page could also read "Run this algorithm" instead "Run an algorithm"

**Comment by jmsmkn** [comment]
Related: #994 - maybe review all breadcrumbs for these apps.

**Comment by nlessmann** [comment]
Also missing on the "add user" page: https://grand-challenge.org/algorithms/vertebra-segmentation/users/update/

**Comment by jmsmkn** [comment]
The fix does not quite work, the breadcrumbs are not correct for:

- algorithm_execution_session_create.html 
- algorithm_user_groups_form.html 
- algorithmimage_form.html 

```
       <li class="breadcrumb-item"><a
                href="{{ algorithm.get_absolute_url }}">{{ algorithm.title }}
        </a>
```

Is returning an empty string
